using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;
namespace DeadDistrict.Editor {
 public static class ChapterAtmosphereSetup {
  const string Folder="Assets/ZombieSurvival/Apocalypse/ChapterAmbience/";
  static Transform root;
  static Material Convert(Material source){string path=Folder+AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(source))+".mat";var m=AssetDatabase.LoadAssetAtPath<Material>(path);if(m)return m;m=new Material(Shader.Find("Universal Render Pipeline/Particles/Unlit"));var texture=source.HasProperty("_BaseMap")?source.GetTexture("_BaseMap"):source.HasProperty("_MainTex")?source.GetTexture("_MainTex"):null;m.SetTexture("_BaseMap",texture);m.SetColor("_BaseColor",Color.white);m.SetFloat("_Surface",1);m.SetFloat("_Blend",0);m.SetFloat("_SrcBlend",(float)BlendMode.SrcAlpha);m.SetFloat("_DstBlend",(float)BlendMode.OneMinusSrcAlpha);m.SetFloat("_ZWrite",0);m.SetFloat("_Cull",0);m.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");m.SetOverrideTag("RenderType","Transparent");m.renderQueue=3000;AssetDatabase.CreateAsset(m,path);return m;}
  static EnvironmentSite Site(string name,Vector3 position,string audio,float gain,float range=20,bool global=false){var go=new GameObject(name);go.transform.SetParent(root,false);go.transform.position=position;var s=go.AddComponent<EnvironmentSite>();s.gain=gain;s.range=range;s.global=global;if(audio!=null){s.clip=Resources.Load<AudioClip>("DeadDistrict/Ambience/"+audio);if(!s.clip)throw new Exception("Missing ambient clip "+audio);}return s;}
  // kind: rain, fog, sparks, steam, flare. Particle meshes and textures come from purchased assets.
  static void Effect(EnvironmentSite site,string name,int kind){var source=AssetDatabase.LoadAssetAtPath<GameObject>("Assets/PolygonApocalypse/Prefabs/FX/Prefabbed/"+name+".prefab");if(!source)throw new Exception("Missing environmental FX "+name);var go=UnityEngine.Object.Instantiate(source,site.transform,false);go.name=name;VisualUpgrade.Strip(go,true);go.transform.SetLocalPositionAndRotation(Vector3.zero,Quaternion.identity);go.transform.localScale=Vector3.one;
   foreach(var light in go.GetComponentsInChildren<Light>(true))UnityEngine.Object.DestroyImmediate(light);
   foreach(var p in go.GetComponentsInChildren<ParticleSystem>(true)){p.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);var m=p.main;m.loop=kind!=2;m.playOnAwake=false;m.prewarm=false;m.stopAction=ParticleSystemStopAction.None;m.simulationSpace=ParticleSystemSimulationSpace.World;m.scalingMode=ParticleSystemScalingMode.Hierarchy;m.useUnscaledTime=false;m.cullingMode=ParticleSystemCullingMode.Automatic;m.maxParticles=kind==0?90:kind==1?8:kind==2?7:kind==3?12:8;m.startLifetime=kind==0?.85f:kind==1?3.8f:kind==2?.28f:kind==3?1.8f:1.2f;m.startSpeed=kind==2?new ParticleSystem.MinMaxCurve(1,3):new ParticleSystem.MinMaxCurve(0);m.gravityModifier=kind==2?1:0;m.startSize3D=false;m.startSize=kind==0?.035f:kind==1?2.2f:kind==2?.055f:kind==3?.8f:.25f;m.startColor=kind==0?new Color(.7f,.82f,.9f,.4f):kind==1?new Color(.64f,.73f,.78f,.095f):kind==2?new Color(1,.65f,.2f,.8f):kind==3?new Color(.72f,.78f,.8f,.2f):new Color(1,.18f,.035f,.65f);
    var em=p.emission;em.enabled=true;em.rateOverTime=kind==0?100:kind==1?1.8f:kind==2?0:kind==3?5:4;em.rateOverDistance=0;em.SetBursts(kind==2?new[]{new ParticleSystem.Burst(0,7)}:new ParticleSystem.Burst[0]);
    var shape=p.shape;shape.enabled=true;shape.shapeType=kind==2?ParticleSystemShapeType.Sphere:ParticleSystemShapeType.Box;shape.position=Vector3.zero;shape.rotation=Vector3.zero;shape.radius=.12f;shape.scale=kind==0?new Vector3(12,.1f,14):kind==1?new Vector3(5,.08f,2):Vector3.one*.2f;
    var velocity=p.velocityOverLifetime;velocity.enabled=true;velocity.space=ParticleSystemSimulationSpace.World;velocity.x=kind==0?.45f:kind==1?.35f:.1f;velocity.y=kind==0?-7:kind==1?.01f:kind==3?.7f:.3f;velocity.z=.12f;velocity.orbitalX=velocity.orbitalY=velocity.orbitalZ=0;velocity.radial=0;velocity.speedModifier=1;
    var collision=p.collision;collision.enabled=false;var lights=p.lights;lights.enabled=false;var trails=p.trails;trails.enabled=false;var sub=p.subEmitters;sub.enabled=false;var force=p.forceOverLifetime;force.enabled=false;var noise=p.noise;noise.enabled=false;
    var tint=p.colorOverLifetime;tint.enabled=true;var gradient=new Gradient();gradient.SetKeys(new[]{new GradientColorKey(Color.white,0),new GradientColorKey(Color.white,1)},new[]{new GradientAlphaKey(0,0),new GradientAlphaKey(1,.18f),new GradientAlphaKey(0,1)});tint.color=gradient;var size=p.sizeOverLifetime;size.enabled=kind!=0;size.size=new ParticleSystem.MinMaxCurve(1,AnimationCurve.Linear(0,.6f,1,1.7f));
    var renderer=p.GetComponent<ParticleSystemRenderer>();renderer.sharedMaterials=renderer.sharedMaterials.Where(x=>x).Select(Convert).ToArray();renderer.shadowCastingMode=ShadowCastingMode.Off;renderer.receiveShadows=false;renderer.maxParticleSize=kind==1?.18f:.1f;
    if(kind==1||kind==3){renderer.sharedMaterial=AssetDatabase.LoadAssetAtPath<Material>("Assets/ZombieSurvival/Launcher/Polish/LauncherSmoke.mat");renderer.renderMode=ParticleSystemRenderMode.Billboard;renderer.alignment=ParticleSystemRenderSpace.View;renderer.allowRoll=false;var sheet=p.textureSheetAnimation;sheet.enabled=true;sheet.numTilesX=2;sheet.numTilesY=2;sheet.frameOverTime=0;sheet.startFrame=new ParticleSystem.MinMaxCurve(0,4);m.startRotation3D=false;m.startRotation=0;var rotation=p.rotationOverLifetime;rotation.enabled=false;var speedRotation=p.rotationBySpeed;speedRotation.enabled=false;if(kind==1){m.startSize3D=true;m.startSizeX=3.8f;m.startSizeY=.85f;m.startSizeZ=1;m.startColor=new Color(.72f,.79f,.83f,.19f);}}
    if(kind==0){renderer.renderMode=ParticleSystemRenderMode.Stretch;renderer.velocityScale=.035f;renderer.lengthScale=3;renderer.cameraVelocityScale=0;}
   }
  }
  static void Beacon(EnvironmentSite site){string path=Folder+"AmberBeacon.mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(path);if(!mat){mat=new Material(Shader.Find("Universal Render Pipeline/Unlit"));mat.SetColor("_BaseColor",new Color(1,.35f,.05f));AssetDatabase.CreateAsset(mat,path);}var bulb=GameObject.CreatePrimitive(PrimitiveType.Sphere);UnityEngine.Object.DestroyImmediate(bulb.GetComponent<Collider>());bulb.name="Slow amber warning lamp";bulb.transform.SetParent(site.transform,false);bulb.transform.localPosition=Vector3.up*.55f;bulb.transform.localScale=new Vector3(.2f,.28f,.2f);site.beacon=bulb.GetComponent<Renderer>();site.beacon.sharedMaterial=mat;site.beacon.shadowCastingMode=ShadowCastingMode.Off;}
  static void JunctionBox(EnvironmentSite site){
   string path=Folder+"WeatheredElectricalBox.mat";var mat=AssetDatabase.LoadAssetAtPath<Material>(path);if(!mat){mat=new Material(Shader.Find("Universal Render Pipeline/Lit"));mat.SetColor("_BaseColor",new Color(.24f,.3f,.32f));mat.SetFloat("_Smoothness",.12f);AssetDatabase.CreateAsset(mat,path);}
   foreach(var part in new[]{new Vector3(.08f,site.transform.position.y,.08f),new Vector3(.38f,.46f,.3f)}){var go=GameObject.CreatePrimitive(PrimitiveType.Cube);UnityEngine.Object.DestroyImmediate(go.GetComponent<Collider>());go.name=part.x<.1f?"Junction support":"Faulty electrical box";go.transform.SetParent(site.transform,false);go.transform.localPosition=part.x<.1f?Vector3.down*part.y*.5f:Vector3.zero;go.transform.localScale=part;go.GetComponent<Renderer>().sharedMaterial=mat;}
   site.beacon.transform.localPosition=Vector3.up*.36f;
  }
  public static void Apply(){Directory.CreateDirectory(Folder);AssetDatabase.Refresh();foreach(string file in Directory.GetFiles("Assets/ZombieSurvival/Resources/DeadDistrict/Ambience","*.wav")){var importer=(AudioImporter)AssetImporter.GetAtPath(file);importer.forceToMono=true;var settings=importer.defaultSampleSettings;settings.loadType=AudioClipLoadType.DecompressOnLoad;settings.compressionFormat=AudioCompressionFormat.Vorbis;settings.quality=.65f;importer.defaultSampleSettings=settings;importer.SaveAndReimport();}
   for(int chapter=0;chapter<3;chapter++){var scene=EditorSceneManager.OpenScene(ChapterCatalog.ScenePaths[chapter]);var old=GameObject.Find("Chapter ambience");if(old)UnityEngine.Object.DestroyImmediate(old);root=new GameObject("Chapter ambience").transform;
    Site("Open air wind",Vector3.zero,"Wind",chapter==0?.20f:.13f,20,true);
    if(chapter==0){var wrecks=GameObject.Find("Apocalypse atmosphere").GetComponentsInChildren<DistrictAtmosphere>().Where(s=>s.name=="Wreck embers");foreach(var w in wrecks)Site("Wreck crackle",w.transform.position,"Fire",.32f,16);foreach(var pos in new[]{new Vector3(-8,.2f,16),new Vector3(9,.2f,-16)})Effect(Site("Road warning flare",pos,null,0),"Fx_RoadFlare_01",4);}
    if(chapter==1){Site("Camp light rain",Vector3.zero,"Rain",.24f,30,false);foreach(float z in new[]{-7f,7f})Effect(Site("Open lane rain",new Vector3(0,5.8f,z),null,0,28),"FX_Rain_01",0);
     foreach(var pos in new[]{new Vector3(-25,1.25f,16),new Vector3(26,1.25f,-19)}){var site=Site("Generator vibration",pos,"Generator",.3f,19);Beacon(site);}
     foreach(var pos in new[]{new Vector3(-10,.2f,25),new Vector3(10,.2f,-27)})Effect(Site("Camp mist edge",pos,null,0),"FX_Fog_Flat_01",1);
     var sun=GameObject.Find("Late afternoon").GetComponent<Light>();sun.color=new Color(.83f,.91f,1);sun.intensity=1.2f;RenderSettings.ambientLight=new Color(.59f,.64f,.68f);
    }
    if(chapter==2){foreach(var pos in new[]{new Vector3(-30,.8f,-9),new Vector3(31,.8f,9)}){var steam=Site("Leaking pipe",pos,"Steam",.32f,18);Effect(steam,"FX_Smoke_Small_01",3);var spark=Site("Damaged electrical connection",pos+new Vector3(0,.5f,1.1f),"Electrical",.22f,15);spark.intermittent=true;Effect(spark,"Fx_Sparks_01",2);Beacon(spark);JunctionBox(spark);}
     foreach(var pos in new[]{new Vector3(-10,.12f,-7),new Vector3(10,.12f,8),new Vector3(-10,.12f,23),new Vector3(10,.12f,-24)})Effect(Site("Loading lane ground mist",pos,null,0,23),"FX_Fog_Small_01",1);
     var sun=GameObject.Find("Late afternoon").GetComponent<Light>();sun.color=new Color(.83f,.91f,1);sun.intensity=1.35f;
    }
    int budget=root.GetComponentsInChildren<ParticleSystem>().Sum(p=>p.main.maxParticles);if(budget>320||root.GetComponentsInChildren<Light>().Length>0||root.GetComponentsInChildren<Collider>().Length>0)throw new Exception("Atmosphere budget or physics "+chapter+" / "+budget);
    EditorSceneManager.SaveScene(scene);Debug.Log("CHAPTER_AMBIENCE_READY chapter="+(chapter+1)+" sites="+root.GetComponentsInChildren<EnvironmentSite>().Length+" particleCap="+budget);
   }
   File.WriteAllText(Folder+"Sources.txt","Visuals: PolygonApocalypse FX_Rain_01, FX_Fog_Flat_01, FX_Fog_Small_01, FX_Smoke_Small_01, Fx_Sparks_01, Fx_RoadFlare_01. Derived URP materials and limited scene instances; originals unchanged.\nAudio: Q6389 owned sound bundle; exact source/edit record in Resources/DeadDistrict/Ambience/Sources.json and work/prepare_atmosphere_audio_v54.py. Engine loop adapted as generator, boiling loop filtered as steam, welding as intermittent electric crackle.\nFixed sites, player-distance attenuation/culling; no realtime lights/collisions. Original chapter data, navmeshes and gameplay are unchanged.\n");PlayerSettings.bundleVersion=MobileBuild.Version;PlayerSettings.iOS.buildNumber="54";AssetDatabase.SaveAssets();
  }
  public static void ApplyAndBuild(){Apply();PrototypeSetup.Build();}
 }
}
