using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;
using UnityEngine.Rendering;
namespace DeadDistrict.Editor {
 public static class LauncherPolish {
  const string Folder="Assets/ZombieSurvival/Launcher/Polish/";
  const string Epic="Assets/Epic Toon FX/Prefabs/";
  static Material Convert(Material source){
   if(!source)return null;string path=Folder+"Materials/"+AssetDatabase.AssetPathToGUID(AssetDatabase.GetAssetPath(source))+".mat";
   var m=AssetDatabase.LoadAssetAtPath<Material>(path);if(m)return m;
   m=new Material(Shader.Find("Universal Render Pipeline/Particles/Unlit"));var texture=source.HasProperty("_BaseMap")?source.GetTexture("_BaseMap"):source.HasProperty("_MainTex")?source.GetTexture("_MainTex"):null;m.SetTexture("_BaseMap",texture);m.SetColor("_BaseColor",Color.white);
   bool additive=source.name.Contains("ADD")||source.shader.name.Contains("Additive");m.SetFloat("_Surface",1);m.SetFloat("_Blend",additive?2:0);m.SetFloat("_SrcBlend",(float)BlendMode.SrcAlpha);m.SetFloat("_DstBlend",(float)(additive?BlendMode.One:BlendMode.OneMinusSrcAlpha));m.SetFloat("_ZWrite",0);m.SetFloat("_Cull",0);m.EnableKeyword("_SURFACE_TYPE_TRANSPARENT");m.renderQueue=3000;AssetDatabase.CreateAsset(m,path);return m;
  }
  static GameObject Effect(string path){var g=UnityEngine.Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>(Epic+path));VisualUpgrade.Strip(g);g.transform.SetPositionAndRotation(Vector3.zero,Quaternion.identity);g.transform.localScale=Vector3.one;
   foreach(var ps in g.GetComponentsInChildren<ParticleSystem>(true)){ps.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);var m=ps.main;m.playOnAwake=false;m.loop=false;m.useUnscaledTime=false;m.stopAction=ParticleSystemStopAction.None;m.scalingMode=ParticleSystemScalingMode.Hierarchy;var collision=ps.collision;collision.enabled=false;var trails=ps.trails;trails.enabled=false;var subs=ps.subEmitters;subs.enabled=false;var r=ps.GetComponent<ParticleSystemRenderer>();r.sharedMaterials=r.sharedMaterials.Select(Convert).ToArray();r.shadowCastingMode=ShadowCastingMode.Off;r.receiveShadows=false;}
   return g;
  }
  static void Burst(ParticleSystem p,int count,float size,float lifetime,Color color){var main=p.main;main.duration=.6f;main.startDelay=0;main.startLifetime=lifetime;main.startSize=size;main.startSpeed=0;main.startColor=color;main.maxParticles=count;main.simulationSpace=ParticleSystemSimulationSpace.World;var shape=p.shape;shape.enabled=false;var emission=p.emission;emission.rateOverTime=0;emission.rateOverDistance=0;emission.SetBursts(new[]{new ParticleSystem.Burst(0,(short)count)});var sizeOver=p.sizeOverLifetime;sizeOver.enabled=true;sizeOver.size=new ParticleSystem.MinMaxCurve(1,AnimationCurve.Linear(0,.25f,1,1));var alpha=p.colorOverLifetime;alpha.enabled=true;var gradient=new Gradient();gradient.SetKeys(new[]{new GradientColorKey(Color.white,0),new GradientColorKey(Color.white,1)},new[]{new GradientAlphaKey(1,0),new GradientAlphaKey(.8f,.25f),new GradientAlphaKey(0,1)});alpha.color=gradient;}
  static GameObject Save(GameObject g,string name){var saved=PrefabUtility.SaveAsPrefabAsset(g,Folder+name+".prefab");UnityEngine.Object.DestroyImmediate(g);return saved;}
  public static void Apply(){Directory.CreateDirectory(Folder+"Materials");AssetDatabase.Refresh();var pack=Resources.Load<PackVisuals>("DeadDistrict/PackVisuals");
   var blast=Effect("Combat/Explosions/SharpExplosion/SharpExplosionFire.prefab");blast.name="Launcher compact blast";
   foreach(var p in blast.GetComponentsInChildren<ParticleSystem>(true)){
    if(p.name=="Trail"||p.name=="Ring"){UnityEngine.Object.DestroyImmediate(p.gameObject);continue;}
    if(p.name=="Glow")Burst(p,1,3.1f,.12f,new Color(2,1.1f,.2f,.4f));
    else if(p.name=="Threads"){Burst(p,8,.16f,.32f,new Color(2.1f,1.05f,.15f,1));var m=p.main;m.startSpeed=new ParticleSystem.MinMaxCurve(3,7);var shape=p.shape;shape.enabled=true;shape.shapeType=ParticleSystemShapeType.Sphere;shape.radius=.12f;}
    else {Burst(p,6,.12f,.28f,new Color(2,1,.15f,1));var main=p.main;main.startSpeed=new ParticleSystem.MinMaxCurve(6,10);var shape=p.shape;shape.enabled=true;shape.shapeType=ParticleSystemShapeType.Sphere;shape.radius=.12f;}
   }
   var fireball=Effect("Combat/Explosions/FireballRoundExplosion/ExplosionFireballFire.prefab");foreach(Transform child in fireball.transform.Cast<Transform>().ToArray())UnityEngine.Object.DestroyImmediate(child.gameObject);fireball.name="Brief blast fireball";fireball.transform.SetParent(blast.transform,false);var flame=fireball.GetComponent<ParticleSystem>();Burst(flame,1,3.6f,.34f,new Color(1.5f,.85f,.32f,.9f));var flameRenderer=flame.GetComponent<ParticleSystemRenderer>();flameRenderer.sharedMaterial=Convert(AssetDatabase.LoadAssetAtPath<Material>("Assets/Epic Toon FX/Materials/Misc/Explosions/explosion_sharp_flat_3x3_AB.mat"));var sheet=flame.textureSheetAnimation;sheet.enabled=true;sheet.mode=ParticleSystemAnimationMode.Grid;sheet.numTilesX=3;sheet.numTilesY=3;sheet.animation=ParticleSystemAnimationType.WholeSheet;sheet.frameOverTime=new ParticleSystem.MinMaxCurve(1,AnimationCurve.Linear(0,0,1,1));sheet.startFrame=0;sheet.cycleCount=1;var flameSize=flame.sizeOverLifetime;flameSize.size=new ParticleSystem.MinMaxCurve(1,AnimationCurve.Linear(0,.65f,1,1));
   var dust=Effect("Environment/Dust/DustDirtyPoofSoft.prefab");dust.name="Brief impact dust";dust.transform.SetParent(blast.transform,false);
   foreach(var p in dust.GetComponentsInChildren<ParticleSystem>(true)){Burst(p,6,.65f,.6f,new Color(.48f,.38f,.23f,.24f));var main=p.main;main.startSpeed=new ParticleSystem.MinMaxCurve(.5f,1.5f);var shape=p.shape;shape.enabled=true;shape.shapeType=ParticleSystemShapeType.Sphere;shape.radius=.3f;}
   pack.launcherExplosion=Save(blast,"LauncherBlast");
   var gun=UnityEngine.Object.Instantiate(pack.launcherWeapon);foreach(var p in gun.GetComponentsInChildren<ParticleSystem>(true).ToArray())if(p)UnityEngine.Object.DestroyImmediate(p.gameObject);
   var flash=Effect("Combat/Muzzleflash/BulletMuzzle/BulletMuzzleFire.prefab");flash.name="Epic Muzzle";flash.transform.SetParent(gun.transform,false);flash.transform.localPosition=new Vector3(0,.11f,.71f);flash.transform.localRotation=Quaternion.identity;
   foreach(var p in flash.GetComponentsInChildren<ParticleSystem>(true))Burst(p,1,p.name=="Glow"?.7f:.9f,p.name=="Glow"?.075f:.11f,new Color(2.2f,1.1f,.18f,p.name=="Glow"?.5f:1));
   PrefabUtility.SaveAsPrefabAsset(gun,AssetDatabase.GetAssetPath(pack.launcherWeapon));UnityEngine.Object.DestroyImmediate(gun);
   var round=new GameObject("Direct-fire cannon round");var model=UnityEngine.Object.Instantiate(AssetDatabase.LoadAssetAtPath<GameObject>("Assets/TopDownEngine/Demos/Tanks/Prefabs/TankCannonBullet.prefab"),round.transform);VisualUpgrade.Strip(model,false);model.transform.SetLocalPositionAndRotation(Vector3.zero,Quaternion.identity);model.transform.localScale=Vector3.one;
   var renderers=model.GetComponentsInChildren<MeshRenderer>();if(renderers.Length==0)throw new Exception("Tank cannon mesh missing");var bounds=renderers[0].bounds;foreach(var r in renderers)bounds.Encapsulate(r.bounds);model.transform.localScale=new Vector3(.25f/bounds.size.x,.25f/bounds.size.y,.52f/bounds.size.z);bounds=renderers[0].bounds;foreach(var r in renderers)bounds.Encapsulate(r.bounds);model.transform.position-=bounds.center;
   string shellPath=Folder+"Shell.mat";var shell=AssetDatabase.LoadAssetAtPath<Material>(shellPath);if(!shell){shell=new Material(Shader.Find("Universal Render Pipeline/Lit"));AssetDatabase.CreateAsset(shell,shellPath);}shell.SetColor("_BaseColor",new Color(.9f,.48f,.12f));shell.SetFloat("_Metallic",.4f);shell.SetFloat("_Smoothness",.3f);foreach(var r in renderers){r.sharedMaterial=shell;r.shadowCastingMode=ShadowCastingMode.Off;}
   var glow=new GameObject("Hot projectile tip");glow.transform.SetParent(round.transform,false);glow.transform.localPosition=Vector3.forward*.15f;var ps=glow.AddComponent<ParticleSystem>();ps.Stop(true,ParticleSystemStopBehavior.StopEmittingAndClear);Burst(ps,4,.43f,.09f,new Color(2,.9f,.1f,.8f));var mainGlow=ps.main;mainGlow.loop=true;mainGlow.playOnAwake=false;mainGlow.simulationSpace=ParticleSystemSimulationSpace.Local;var em=ps.emission;em.SetBursts(new ParticleSystem.Burst[0]);em.rateOverTime=35;var gr=ps.GetComponent<ParticleSystemRenderer>();gr.sharedMaterial=Resources.Load<Material>("DeadDistrict/BulletGlow");gr.shadowCastingMode=ShadowCastingMode.Off;gr.receiveShadows=false;pack.launcherProjectile=Save(round,"LauncherRound");
   foreach(string name in new[]{"LauncherShot","LauncherBlast"}){var imp=AssetImporter.GetAtPath("Assets/ZombieSurvival/Resources/DeadDistrict/Audio/"+name+".wav") as AudioImporter;if(!imp)throw new Exception("Missing launcher audio "+name);imp.forceToMono=true;var settings=imp.defaultSampleSettings;settings.loadType=AudioClipLoadType.DecompressOnLoad;settings.compressionFormat=AudioCompressionFormat.Vorbis;settings.quality=.8f;imp.defaultSampleSettings=settings;imp.SaveAndReimport();}
   EditorUtility.SetDirty(shell);EditorUtility.SetDirty(pack);PlayerSettings.bundleVersion=MobileBuild.Version;PlayerSettings.iOS.buildNumber="50";AssetDatabase.SaveAssets();
   int max=pack.launcherExplosion.GetComponentsInChildren<ParticleSystem>(true).Sum(x=>x.main.maxParticles);if(max>40)throw new Exception("Launcher effect too expensive: "+max);File.WriteAllText(Folder+"Sources.txt","Projectile mesh: TopDownEngine/Demos/Tanks/Prefabs/TankCannonBullet.prefab\nExplosion: Epic Toon FX SharpExplosionFire + ExplosionFireballFire + DustDirtyPoofSoft (reduced bursts, no trail or billboard ring layer).\nMuzzle: Epic Toon FX BulletMuzzleFire. Burst atlas: Epic explosion_sharp_flat_3x3. Glow texture: existing Epic BulletGlow.\nAudio: TopDown TankCannonShot + Q6389 Sci Fi Grenade Launcher 2; Q6389 Explosion Grenade_02 + Epic etfx_explosion_bullet. See work/prepare_launcher_audio_v50.py for edit recipe.\nMax particles per blast: "+max+"; fixed pool: 4. No new realtime lights.\n");Debug.Log("LAUNCHER_POLISH_READY maxBlastParticles="+max);
  }
  public static void ApplyAndBuild(){Apply();LaterChapterDensity.Apply();PrototypeSetup.Build();}
 }
}
