using UnityEngine;
using UnityEditor;
using System.Linq;
namespace DeadDistrict.Editor {
 public static class SupplyAssets {
  const string Loft="Assets/TopDownEngine/Demos/Loft3D/";
  public static void Prepare(PackVisuals pack){
   pack.supplies=new[]{Medkit(),Purchased("SupplyAmmo","Prefabs/ItemPickers/LoftAmmoCrateAssaultRifle.prefab",.95f),Purchased("SupplyGrenade","Prefabs/Weapons/Projectiles/LoftGrenade.prefab",.65f),Armor()};
   pack.healPickup=PresentationUpgrade.Effect("SupplyHealFX","Prefabs/Interactive/Healing/HealOnceBurst.prefab",.65f,false);
   pack.supplyPickup=PresentationUpgrade.Effect("SupplyPickupFX","Prefabs/Interactive/Loot/ItemSparkleBurst/ItemSparkleBurstYellow.prefab",.45f,false);
   pack.armorAura=PresentationUpgrade.Effect("SupplyArmorAura","Prefabs/Combat/Shield/ShieldSoftBlue.prefab",.45f,true);
   foreach(var ps in pack.armorAura.GetComponentsInChildren<ParticleSystem>(true)){var m=ps.main;m.maxParticles=16;m.startLifetime=.6f;m.simulationSpace=ParticleSystemSimulationSpace.Local;var emission=ps.emission;emission.rateOverTime=4;emission.SetBursts(new ParticleSystem.Burst[0]);EditorUtility.SetDirty(ps);}
   EditorUtility.SetDirty(pack);AssetDatabase.SaveAssets();
   foreach(var prefab in pack.supplies){if(!prefab||prefab.GetComponentsInChildren<Collider>(true).Length>0)throw new System.Exception("Supply must be nonblocking");foreach(var r in prefab.GetComponentsInChildren<Renderer>(true))foreach(var mat in r.sharedMaterials)if(!mat||!mat.shader.name.StartsWith("Universal Render Pipeline"))throw new System.Exception("Supply material must support URP");}
   Debug.Log("SUPPLY_ASSET_CHECK_PASS four nonblocking supply prefabs and three Epic effects");
  }
  static GameObject Purchased(string name,string path,float size){VisualUpgrade.reused.Add(Loft+path);var src=AssetDatabase.LoadAssetAtPath<GameObject>(Loft+path);if(!src)throw new System.Exception("Missing supply model "+path);var root=new GameObject(name);var model=Object.Instantiate(src,root.transform);VisualUpgrade.Strip(model,false);foreach(var a in model.GetComponentsInChildren<Animator>())Object.DestroyImmediate(a);model.transform.localPosition=Vector3.zero;model.transform.localRotation=Quaternion.identity;model.transform.localScale=Vector3.one;VisualUpgrade.ConvertRenderers(model);var rr=model.GetComponentsInChildren<Renderer>();var b=rr[0].bounds;foreach(var r in rr)b.Encapsulate(r.bounds);model.transform.localScale*=size/Mathf.Max(b.size.x,b.size.y,b.size.z);b=rr[0].bounds;foreach(var r in rr)b.Encapsulate(r.bounds);model.transform.localPosition-=new Vector3(b.center.x,b.min.y,b.center.z);if(name=="SupplyGrenade"){var cap=Mat("Grenade hardware",new Color(.12f,.18f,.16f));BlockVisuals.Shape("Safety cap",PrimitiveType.Cylinder,root.transform,new Vector3(0,.67f,0),new Vector3(.16f,.045f,.16f),cap);var lever=BlockVisuals.Shape("Safety lever",PrimitiveType.Cube,root.transform,new Vector3(.1f,.6f,0),new Vector3(.06f,.27f,.07f),cap);lever.transform.localRotation=Quaternion.Euler(0,0,-20);}
   return VisualUpgrade.Save(root,name);}
  static Material Mat(string name,Color c){string p="Assets/ZombieSurvival/Materials/"+name+".mat";var m=AssetDatabase.LoadAssetAtPath<Material>(p);if(!m){m=new Material(Shader.Find("Universal Render Pipeline/Lit"));AssetDatabase.CreateAsset(m,p);}m.SetColor("_BaseColor",c);m.SetFloat("_Smoothness",.2f);EditorUtility.SetDirty(m);return m;}
  static GameObject Medkit(){var root=new GameObject("SupplyMedkit");var shell=Mat("Medical case",new Color(.85f,.91f,.88f));var mark=Mat("Medical cross",new Color(.1f,.68f,.46f));var dark=Mat("Supply trim",new Color(.10f,.17f,.2f));BlockVisuals.Shape("Case",PrimitiveType.Cube,root.transform,new Vector3(0,.25f,0),new Vector3(.78f,.5f,.52f),shell);BlockVisuals.Shape("Cross vertical",PrimitiveType.Cube,root.transform,new Vector3(0,.511f,0),new Vector3(.1f,.025f,.32f),mark);BlockVisuals.Shape("Cross horizontal",PrimitiveType.Cube,root.transform,new Vector3(0,.51f,0),new Vector3(.32f,.025f,.1f),mark);BlockVisuals.Shape("Handle",PrimitiveType.Cube,root.transform,new Vector3(0,.25f,-.3f),new Vector3(.35f,.1f,.08f),dark);return VisualUpgrade.Save(root,"SupplyMedkit");}
  static GameObject Armor(){var root=new GameObject("SupplyArmor");var steel=Mat("Armor plate",new Color(.17f,.43f,.62f));var white=Mat("Armor stripe",new Color(.65f,.85f,.95f));BlockVisuals.Shape("Armor vest",PrimitiveType.Cube,root.transform,new Vector3(0,.32f,0),new Vector3(.62f,.65f,.18f),steel);BlockVisuals.Shape("Left shoulder",PrimitiveType.Cube,root.transform,new Vector3(-.21f,.69f,0),new Vector3(.15f,.18f,.18f),steel);BlockVisuals.Shape("Right shoulder",PrimitiveType.Cube,root.transform,new Vector3(.21f,.69f,0),new Vector3(.15f,.18f,.18f),steel);BlockVisuals.Shape("Plate stripe",PrimitiveType.Cube,root.transform,new Vector3(0,.4f,-.1f),new Vector3(.45f,.06f,.025f),white);return VisualUpgrade.Save(root,"SupplyArmor");}
 }
}
