using UnityEngine;
using UnityEngine.UI;
namespace DeadDistrict {
 public sealed class ActionButtonView:MonoBehaviour {
  ActionGlyph glyph,ring;Image background,icon,lockGlyph,launcherMark,countPlate;Text badge,caption;Button button;
  static readonly Color Ready=new Color(.83f,.96f,1),Dim=new Color(.43f,.57f,.62f,.65f),Cyan=new Color(.35f,.85f,.91f),Amber=new Color(1,.69f,.28f);
  ActionGlyph Art(string name,Vector2 size,Vector2 position){var g=new GameObject(name,typeof(RectTransform),typeof(CanvasRenderer),typeof(ActionGlyph));g.transform.SetParent(transform,false);var r=g.GetComponent<RectTransform>();r.anchorMin=r.anchorMax=r.pivot=new Vector2(.5f,.5f);r.sizeDelta=size;r.anchoredPosition=position;var art=g.GetComponent<ActionGlyph>();art.raycastTarget=false;return art;}
  Image Icon(string name,Vector2 size,Vector2 position){var g=new GameObject(name,typeof(RectTransform),typeof(CanvasRenderer),typeof(Image));g.transform.SetParent(transform,false);var image=g.GetComponent<Image>();var r=image.rectTransform;r.anchorMin=r.anchorMax=r.pivot=new Vector2(.5f,.5f);r.sizeDelta=size;r.anchoredPosition=position;image.raycastTarget=false;image.preserveAspect=true;return image;}
  public void Initialize(Button target,Sprite circle,Font font){button=target;background=target.GetComponent<Image>();background.sprite=circle;background.color=new Color(.055f,.12f,.16f,.9f);var size=((RectTransform)transform).sizeDelta;
   var track=Art("Outline",size,Vector2.zero);track.Set(ActionSymbol.Ring,new Color(.33f,.55f,.61f,.35f));ring=Art("Availability ring",size,Vector2.zero);
   glyph=Art("Fallback action icon",size*.55f,new Vector2(0,12));glyph.gameObject.SetActive(false);
   icon=Icon("Action icon",size*.55f,new Vector2(0,12));lockGlyph=Icon("Locked",new Vector2(18,18),new Vector2(size.x*.37f,size.y*.32f));lockGlyph.sprite=ActionIconLibrary.Get(ActionSymbol.Lock);lockGlyph.color=Dim;lockGlyph.gameObject.SetActive(false);
   launcherMark=Icon("Launcher explosive symbol",size*.23f,new Vector2(size.x*.20f,4));launcherMark.sprite=ActionIconLibrary.Get(ActionSymbol.Grenade);launcherMark.gameObject.SetActive(false);
   countPlate=Icon("Count badge",new Vector2(40,28),new Vector2(size.x*.68f,size.y*.28f));countPlate.sprite=circle;countPlate.preserveAspect=false;countPlate.color=new Color(.045f,.085f,.11f,.98f);countPlate.gameObject.SetActive(false);
   var g=new GameObject("Count or cooldown",typeof(RectTransform),typeof(Text));g.transform.SetParent(transform,false);badge=g.GetComponent<Text>();badge.font=font;badge.fontSize=18;badge.fontStyle=FontStyle.Bold;badge.alignment=TextAnchor.MiddleCenter;badge.raycastTarget=false;badge.color=Ready;var r=badge.rectTransform;r.anchorMin=r.anchorMax=r.pivot=new Vector2(.5f,.5f);r.anchoredPosition=new Vector2(size.x*.68f,size.y*.28f);r.sizeDelta=new Vector2(40,26);
   var label=new GameObject("Action caption",typeof(RectTransform),typeof(Text));label.transform.SetParent(transform,false);caption=label.GetComponent<Text>();caption.font=font;caption.fontSize=17;caption.fontStyle=FontStyle.Bold;caption.alignment=TextAnchor.MiddleCenter;caption.raycastTarget=false;caption.color=Ready;
   var cr=caption.rectTransform;cr.anchorMin=cr.anchorMax=cr.pivot=new Vector2(.5f,.5f);cr.anchoredPosition=new Vector2(0,-size.y*.27f);cr.sizeDelta=new Vector2(size.x*.78f,28);
   var colors=button.colors;colors.normalColor=Color.white;colors.highlightedColor=new Color(1.3f,1.3f,1.3f);colors.pressedColor=new Color(.4f,.75f,.85f);colors.disabledColor=new Color(.6f,.6f,.6f,.7f);button.colors=colors;
  }
  public void Refresh(ActionSymbol symbol,bool available,string value="",float progress=1,bool active=false,bool locked=false){button.interactable=available;var tint=active?Amber:available?Ready:Dim;var sprite=ActionIconLibrary.Get(symbol);icon.sprite=sprite;icon.color=tint;launcherMark.gameObject.SetActive(symbol==ActionSymbol.Launcher);launcherMark.color=tint;icon.gameObject.SetActive(sprite!=null);glyph.gameObject.SetActive(sprite==null);if(!sprite)glyph.Set(symbol,tint);ring.Set(ActionSymbol.Ring,active?Amber:available||progress<1?Cyan:new Color(.4f,.5f,.55f,.4f),progress);caption.text=symbol==ActionSymbol.Launcher?"切换榴弹":symbol==ActionSymbol.Grenade?"手雷":symbol==ActionSymbol.Roll?"翻滚":symbol==ActionSymbol.Reload?"换弹":symbol==ActionSymbol.DoorOpen?"开门":symbol==ActionSymbol.DoorClosed?"关门":"切枪";caption.color=tint;bool hasCount=!string.IsNullOrEmpty(value);countPlate.gameObject.SetActive(hasCount);badge.text=hasCount?"×"+value:"";badge.color=value=="0"?Dim:Amber;lockGlyph.gameObject.SetActive(locked);}
 }
}
