using System;
using System.Collections;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.UI;
namespace DeadDistrict {
 public sealed class ActiveGrowthValidation:MonoBehaviour {
  static bool started;string output;SurvivalGame g;MobilePreferences.Data original;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var args=RuntimeLaunch.Arguments();if(started||Array.IndexOf(args,"-active-growth-smoke")<0)return;started=true;var v=new GameObject("Opt-in active growth validation").AddComponent<ActiveGrowthValidation>();DontDestroyOnLoad(v);int n=Array.IndexOf(args,"-validation-output");v.output=n>=0?args[n+1]:Application.persistentDataPath;Directory.CreateDirectory(v.output);v.StartCoroutine(v.Run());}
  void Check(bool ok,string why){if(!ok)throw new Exception(why);}
  void Click(string name){var b=GameObject.Find(name)?.GetComponent<Button>();Check(b&&b.interactable,"Missing/disabled "+name);b.onClick.Invoke();}
  IEnumerator Photo(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Application.isMobilePlatform?name:Path.Combine(output,name));yield return new WaitForSecondsRealtime(.2f);}
  IEnumerator Run(){var e=Core();while(true){bool more=false;object item=null;string fail=null;try{more=e.MoveNext();if(more)item=e.Current;}catch(Exception x){fail=x.ToString();}if(fail!=null){MobilePreferences.Set(original);MobilePreferences.Flush();Time.timeScale=1;File.WriteAllText(Path.Combine(output,"active-growth-failure.txt"),fail);Debug.LogError("ACTIVE_GROWTH_FAIL "+fail);Application.Quit(1);yield break;}if(!more)yield break;yield return item;}}
  IEnumerator Core(){yield return null;yield return null;g=SurvivalGame.Instance;g.CombatValidation=true;g.Growth.Enabled=true;g.config.aimRange=0;original=MobilePreferences.Current;
   foreach(var z in g.Enemies)if(z.Alive)z.Health.Kill();g.PlayerHealth.ResetForSpawn();
   int desired=g.Growth.Level+2;while(g.Growth.Level<desired)g.Growth.Award(EnemyKind.Normal);var growth=g.Growth;int points=growth.Points;int level=growth.Level;float before=g.Elapsed;yield return new WaitForSeconds(.12f);Check(!g.Paused&&!growth.Choosing&&g.Elapsed>before&&points>=2,"Award interrupted battle");Check(g.GrowthEffects.EarnPulses>0,"Missing point visual");
   Canvas.ForceUpdateCanvases();var button=GameObject.Find("Spend growth points").GetComponent<RectTransform>();var corners=new Vector3[4];button.GetWorldCorners(corners);Check(corners[0].x>Screen.width*.6f&&corners[0].y>Screen.height*.5f&&Screen.safeArea.Contains(corners[0])&&Screen.safeArea.Contains(corners[2]),"Point button unsafe/not upper right");yield return Photo("active-points-hud.png");
   g.ThrowGrenade();Check(g.GrenadeInFlight,"Grenade fixture");Click("Spend growth points");Check(!g.Paused&&growth.OpenRequested,"Request interrupted grenade flight");yield return new WaitForSeconds(1.1f);Check(!g.GrenadeInFlight&&!g.Paused&&!growth.Choosing,"Request interrupted explosion feedback");float wait=Time.realtimeSinceStartup+3;while(!growth.Choosing&&Time.realtimeSinceStartup<wait)yield return null;Check(growth.Choosing&&g.Paused,"Deferred manual request lost");
   var offers=growth.Offers.ToArray();int offer=growth.OfferId;Click("Defer growth");Check(!g.Paused&&growth.Points==points&&!g.PlayerHealth.GrowthProtected,"Deferring consumed point or granted free protection");yield return null;Click("Spend growth points");Check(growth.Offers.SequenceEqual(offers)&&growth.OfferId!=offer,"Defer rerolled choices/reused stale token");yield return new WaitForSecondsRealtime(.35f);Check(!growth.Choose(0,offer),"Old panel token accepted");yield return Photo("active-choice-panel.png");
   Check(growth.Choose(0,growth.OfferId)&&growth.Points==points-1&&growth.Level==level&&g.Paused,"Choice did not spend exactly one point");SurvivalInput.Move=Vector2.right;SurvivalInput.GrenadeRequested=true;Click("Defer growth");Check(!g.Paused&&SurvivalInput.Move==Vector2.zero&&!SurvivalInput.GrenadeRequested&&g.PlayerHealth.GrowthProtected,"Return did not clear touch/protect");float hp=g.PlayerHealth.CurrentHealth;g.PlayerHealth.Damage(10,g.gameObject,0,0,Vector3.forward);Check(g.PlayerHealth.CurrentHealth==hp,"Protection failed");yield return null;yield return new WaitForSeconds(.12f);yield return Photo("active-protection.png");yield return new WaitForSeconds(1.05f);Check(!g.PlayerHealth.GrowthProtected,"Protection did not expire");g.PlayerHealth.Damage(10,g.gameObject,0,0,Vector3.forward);Check(g.PlayerHealth.CurrentHealth<hp,"Damage not restored");
   Click("Spend growth points");Click("Defer growth");Check(!g.PlayerHealth.GrowthProtected&&growth.Points==points-1,"Repeated opening grants invulnerability");
   Check(g.TryRoll(),"Roll fixture");Check(growth.TryOpen()&&!g.Paused,"Roll interrupted");wait=Time.realtimeSinceStartup+2;while(!growth.Choosing&&Time.realtimeSinceStartup<wait)yield return null;Check(growth.Choosing&&!g.Rolling,"Roll never completed before opening");Click("Defer growth");
   var forward=Camera.main.transform.forward;forward.y=0;forward.Normalize();var right=Camera.main.transform.right;right.y=0;right.Normalize();
   foreach(EnemyKind kind in Enum.GetValues(typeof(EnemyKind))){var z=g.Enemies[(int)kind];var point=g.PlayerPosition+forward*6+right*((int)kind-1)*2.5f;Check(NavMesh.SamplePosition(point,out var nav,2,NavMesh.AllAreas),"Gait fixture floor");z.Spawn(nav.position,g.config.enemySpeed,kind);float expected=kind==EnemyKind.Normal?2.24f:kind==EnemyKind.Brute?1.482f:5.4f;Check(Mathf.Abs(z.Agent.speed-expected)<.02f,"Variant speed "+kind+" "+z.Agent.speed);}
   yield return new WaitForSeconds(.55f);yield return Photo("infected-gaits.png");foreach(var z in g.Enemies.Take(3)){Check(z.Kind==EnemyKind.Runner?z.Actor.Quadruped:z.Actor.Bone((int)HumanBodyBones.Spine)!=null,"Missing variant gait");z.Retire();}
   Check(new HordePressure(300,g.config,2).runnerChance==0&&new HordePressure(300,g.config,4).bruteChance==0&&new HordePressure(300,g.config,9).runnerChance<=.2f,"Variant gating/cap changed");
   for(int gun=0;gun<2;gun++){if(gun==1)g.CollectShotgun();g.config.aimRange=0;g.Sound.Reload(gun==1,g.WeaponReloadSeconds);var source=GameObject.Find("Reserved weapon reload").GetComponent<AudioSource>();Check(source.clip==Resources.Load<AudioClip>("DeadDistrict/Audio/Reload"),"Different reload clip");g.Sound.CancelReload();}
   for(int type=0;type<2;type++){g.VisualEffects.Bullet(g.PlayerPosition+Vector3.up*1.3f,g.PlayerPosition+forward*10+right*(type==0?-2:2)+Vector3.up*1.2f,type==1);yield return null;var lines=g.VisualEffects.GetComponentsInChildren<LineRenderer>().Where(l=>l.name=="Bullet core").ToArray();Check(lines.Length>0&&lines.All(l=>l.widthMultiplier>.06f),"Restored bullet core width missing");Check(g.VisualEffects.GetComponentsInChildren<ParticleSystem>().Where(p=>p.transform.root==g.transform).Any(),"Effect pools missing");}
   yield return Photo("warm-bullet-trails.png");var d=MobilePreferences.Current;d.reducedFlash=true;MobilePreferences.Set(d);g.GrowthEffects.Apply();yield return null;Check(GameObject.Find("Growth protection").GetComponent<LineRenderer>().startColor.a<.35f,"Reduced flash ignored");MobilePreferences.Set(original);MobilePreferences.Flush();
   g.Restart();yield return null;yield return null;Check(SurvivalGame.Instance.Growth.Points==0&&SurvivalGame.Instance.Growth.Level==1,"New run retained points");
   File.WriteAllText(Path.Combine(output,"active-growth-pass.json"),"{\"passed\":true,\"manualPointsOnly\":true,\"upperRightSafeButton\":true,\"grenadeAndRollDeferred\":true,\"deferPreservesPointsAndOffers\":true,\"staleChoiceGuard\":true,\"oneSecondProtectionAndNoReopenExploit\":true,\"inputReset\":true,\"slowerVariants\":true,\"runnerWaveGateAndCap\":true,\"sameReloadClip\":true,\"restoredBulletTrails\":true,\"reducedGrowthFlash\":true,\"newRunReset\":true}");Debug.Log("ACTIVE_GROWTH_PASS");Application.Quit(0);
  }
 }
}
