using System;
using System.Collections;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
namespace DeadDistrict {
 public sealed class CampValidation:MonoBehaviour {
  SurvivalGame g;string output;float clock;int total,peak,legs;static bool started;
  static readonly BindingFlags Private=BindingFlags.Instance|BindingFlags.NonPublic;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var a=RuntimeLaunch.Arguments();if(started||!a.Contains("-camp-smoke"))return;started=true;ChapterProgress.IsolatedValidation=true;SurvivalGame.Instance.CombatValidation=true;SceneManager.sceneLoaded+=(s,m)=>{if(SurvivalGame.Instance)SurvivalGame.Instance.CombatValidation=true;};var v=new GameObject("Opt-in camp validation").AddComponent<CampValidation>();DontDestroyOnLoad(v.gameObject);int n=Array.IndexOf(a,"-validation-output");v.output=n>=0?a[n+1]:Application.persistentDataPath;Directory.CreateDirectory(v.output);v.StartCoroutine(v.Run());}
  void Check(bool value,string why){if(!value)throw new Exception(why);}
  void Step(float dt=.025f){clock+=dt;typeof(SurvivalGame).GetProperty("Elapsed").SetValue(g,clock);typeof(SurvivalGame).GetMethod("SpawnDirector",Private).Invoke(g,new object[]{clock});Check(g.ActiveCount==g.Enemies.Count(z=>z.Alive)&&g.ActiveCount<=g.config.maxAlive,"Population accounting");peak=Mathf.Max(peak,g.ActiveCount);}
  void FillWave(int wave){
   float filledAt=clock,minAngle=180,maxAngle=-180;int[] mixture=new int[6];int seen=0;bool hitCap=false;var spawns=new System.Collections.Generic.HashSet<string>();
   Action record=()=>{foreach(var e in g.Enemies.Where(z=>z.Alive)){if(!spawns.Add(e.Slot+":"+e.SpawnCount))continue;seen++;if(wave==1&&e.Kind==EnemyKind.Normal&&e.Slot>=g.OpeningCount){var delta=e.transform.position-g.PlayerPosition;float angle=Mathf.DeltaAngle((float)typeof(SurvivalGame).GetField("hordeAngle",Private).GetValue(g)*Mathf.Rad2Deg,Mathf.Atan2(delta.z,delta.x)*Mathf.Rad2Deg);minAngle=Mathf.Min(minAngle,angle);maxAngle=Mathf.Max(maxAngle,angle);Check(Mathf.Abs(e.Health.CurrentHealth-g.config.enemyHealth*g.CurrentWave.health)<.02f&&e.Agent.speed<2.5f,"Wave health or zombie speed wrong");}mixture[(int)e.Kind+(e.IsElite?3:0)]++;Check(!Physics.CheckCapsule(e.transform.position+Vector3.up*.5f,e.transform.position+Vector3.up*1.4f,.35f,1<<8),"Enemy born inside cover");Check((e.transform.position-g.PlayerPosition).magnitude>(wave==1&&e.Slot<g.OpeningCount?7:g.MinimumReinforcementDistance-.1f),"Enemy born too close");if(!(wave==1&&e.Slot<g.OpeningCount))Check(g.IsReinforcementOffscreen(e.transform.position),"Enemy born on screen");}};
   record();
   for(int i=0;g.PendingEnemies>0&&i<4000;i++){
    if(g.ActiveCount==g.config.maxAlive){record();int pending=g.PendingEnemies;Step(2);Check(g.PendingEnemies==pending&&g.ActiveCount==g.config.maxAlive&&g.Wave==wave&&float.IsPositiveInfinity(g.NextHorde),"Full pool lost pending enemies or overlapped waves");hitCap=true;KillTo(75);}
    Step();record();
   }
   Check(g.PendingEnemies==0&&g.Wave==wave&&seen==g.CurrentWave.Count,"Increased wave queue or count wrong "+wave);total+=seen;
   if(wave==1){float duration=clock-filledAt,spread=maxAngle-minAngle;Check(duration<16&&spread>65,"Wave arrival pressure too weak: seconds="+duration+" spread="+spread);File.WriteAllText(Path.Combine(output,"arrival-pressure.json"),"{\"firstWaveFillSeconds\":"+duration.ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"approachSpanDegrees\":"+spread.ToString(System.Globalization.CultureInfo.InvariantCulture)+"}");}
   foreach(var group in g.CurrentWave.groups.GroupBy(x=>new{x.kind,x.elite}))Check(mixture[(int)group.Key.kind+(group.Key.elite?3:0)]==group.Sum(x=>x.count),"Increased wave mixture wrong");
   if(g.CurrentWave.Count>g.config.maxAlive)Check(hitCap,"Larger wave did not exercise queue refill");
  }
  void KillTo(int n){foreach(var e in g.Enemies.Where(z=>z.Alive).Skip(n).ToArray())e.Health.Kill();Check(g.ActiveCount==n,"Kill accounting");}
  void Move(Vector3 p){var c=g.PlayerHealth.GetComponent<CharacterController>();c.enabled=false;c.transform.position=p;c.enabled=true;Physics.SyncTransforms();Camera.main.transform.position=p+new Vector3(-14,21,-14);}
  IEnumerator Photo(string name){typeof(SurvivalHud).GetField("nextRefresh",Private).SetValue(g.hud,0f);g.hud.Refresh();yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(output,name+".png"));yield return new WaitForSecondsRealtime(.2f);}
  IEnumerator Run(){var stack=new System.Collections.Generic.Stack<IEnumerator>();stack.Push(Core());while(stack.Count>0){object item=null;bool more=false;string fail=null;try{more=stack.Peek().MoveNext();if(more)item=stack.Peek().Current;}catch(Exception e){fail=e.ToString();}if(fail!=null){Time.timeScale=1;File.WriteAllText(Path.Combine(output,"camp-failure.txt"),fail);Debug.LogError("CAMP_FAIL "+fail);Application.Quit(1);yield break;}if(!more){stack.Pop();continue;}if(item is IEnumerator nested)stack.Push(nested);else yield return item;}}
  IEnumerator Core(){yield return null;yield return null;g=SurvivalGame.Instance;Check(Mathf.Abs(Camera.main.orthographicSize-7.7f)<.001f&&Mathf.Abs(g.Chapter.eliteWindup-.7f)<.001f,"Camera or 0.7-second elite warning missing");g.enabled=false;g.Growth.Enabled=false;
   Check(g.Chapter.number==1&&g.Chapter.waves.Sum(w=>w.Count)==286,"First chapter changed");Check(!ChapterCatalog.Unlocked(1)&&!g.BeginChapter(1),"Locked camp can open");g.hud.OpenHome();GameObject.Find("Choose chapter").GetComponent<Button>().onClick.Invoke();Check(g.hud.MobilePage=="chapters"&&!GameObject.Find("Select chapter 1").GetComponent<Button>().interactable,"Locked card not disabled");yield return Photo("01-locked-selection");
   ChapterProgress.Complete(g.Chapter.id,300,286);g.hud.OpenHome();GameObject.Find("Choose chapter").GetComponent<Button>().onClick.Invoke();Check(ChapterCatalog.Unlocked(1)&&GameObject.Find("Select chapter 1").GetComponent<Button>().interactable,"Existing first clear does not unlock");yield return Photo("02-unlocked-selection");var old=g;Check(g.BeginChapter(1),"Camp load rejected");while(ReferenceEquals(old,SurvivalGame.Instance))yield return null;yield return null;g=SurvivalGame.Instance;Check(Mathf.Abs(Camera.main.orthographicSize-7.7f)<.001f&&Mathf.Abs(g.Chapter.eliteWindup-.7f)<.001f,"Camera or 0.7-second elite warning missing");g.enabled=false;g.Growth.Enabled=false;
   Check(g.Chapter.number==2&&SceneManager.GetActiveScene().name=="QuarantineCamp"&&g.Growth.Level==1&&g.Kills==0&&g.Ammo==100&&!g.Dead,"Camp start not fresh");Check(g.World.Props.All(x=>x.Kind!=WorldPropKind.Door),"Phantom street doors");foreach(var site in g.Chapter.weaponSites)typeof(WeaponLoot).GetMethod("SpawnNear",Private).Invoke(g.WeaponCrates,new object[]{site});Check(g.WeaponCrates.ActiveCount==3,"Opening weapons missing");
   var root=GameObject.Find("Quarantine camp");Check(root&&!GameObject.Find("Abandoned district"),"Camp map not independent");foreach(var renderer in root.GetComponentsInChildren<MeshRenderer>())foreach(var mat in renderer.sharedMaterials)Check(mat&&mat.shader.isSupported,"Unsupported camp material");
   Move(Vector3.zero);yield return Photo("03-camp-opening");Move(new Vector3(-9,0,7));yield return Photo("04-tent-route");Move(new Vector3(7,0,-21));yield return Photo("05-truck-route");
   var controller=g.PlayerHealth.GetComponent<CharacterController>();Move(Vector3.zero);
   foreach(var dest in new[]{new Vector3(0,0,36),new Vector3(36,0,12),new Vector3(28,0,-20),new Vector3(0,0,-36),new Vector3(-36,0,-12),new Vector3(-28,0,20),Vector3.zero}){var path=new NavMeshPath();Check(NavMesh.CalculatePath(controller.transform.position,dest,NavMesh.AllAreas,path)&&path.status==NavMeshPathStatus.PathComplete,"Disconnected camp route "+dest);foreach(var corner in path.corners.Skip(1)){float routeDeadline=Time.time+15;Vector3 delta;do{delta=corner-controller.transform.position;delta.y=0;if(delta.magnitude<.18f)break;controller.Move(delta.normalized*Mathf.Min(9*Time.deltaTime,delta.magnitude)+Vector3.down*2*Time.deltaTime);yield return null;}while(Time.time<routeDeadline);delta=corner-controller.transform.position;delta.y=0;Check(delta.magnitude<.2f,"Controller blocked: "+controller.transform.position+" toward "+corner);}legs++;}
   // Transparent cover retains physical walls and restores after the player leaves.
   foreach(var cover in root.GetComponentsInChildren<StreetOcclusion>().Take(2)){var b=cover.obstacle.bounds;Move(new Vector3(b.center.x,0,b.max.z+.8f));yield return new WaitForSeconds(1.2f);Check(cover.ObscuringPlayer&&cover.Opacity<.2f&&cover.obstacle.enabled,"Tent occlusion failed: "+cover.name);yield return Photo("06-occlusion-"+cover.name);Move(Vector3.zero);yield return new WaitForSeconds(1.4f);Check(cover.Opacity>.99f,"Tent opacity not restored");}
   Move(Vector3.zero);g.Supplies.Clear();g.WeaponCrates.Clear();clock=Time.time;g.StartChapter();
   for(int wave=1;wave<=8;wave++){FillWave(wave);Step(90);Check(g.Wave==wave,"Wave overlaps previous");if(wave==8)break;KillTo(1);Step(90);Check(g.Wave==wave&&float.IsPositiveInfinity(g.NextHorde),"Wave advances before full clear");KillTo(0);Step();Check(Mathf.Abs(g.NextHorde-clock-5)<.001f,"Break is not five seconds");if(wave==5)Check(g.RestSuppliesPlaced==2,"Recovery supplies missing");Step(4.8f);Check(g.Wave==wave&&g.ActiveCount==0,"Early wave");Step(.21f);yield return null;}
   Check(total==2040&&peak==270&&g.Elite&&g.Elite.ChargeAttack,"Camp budget or elite wrong");foreach(var e in g.Enemies.Where(z=>z.Alive&&!z.IsElite).Skip(1).ToArray())e.Health.Kill();var boss=g.Elite;var attack=boss.ChargeAttack;float hp=g.PlayerHealth.CurrentHealth;
   Move(Vector3.zero);boss.Agent.Warp(new Vector3(0,0,7));attack.Initialize(g,boss);float t=Time.time+2;attack.Tick(t);Check(attack.Phase==EliteCharge.Stage.Windup,"Charge does not telegraph");Vector3 locked=attack.LockedDirection;attack.Tick(t+g.Chapter.eliteWindup-.05f);Check(attack.Charges==0&&g.PlayerHealth.CurrentHealth==hp,"Charge hits before warning");yield return Photo("07-charge-warning");g.PauseForShell();float frozen=Time.time;yield return new WaitForSecondsRealtime(.2f);attack.Tick(t+4);Check(Time.time==frozen&&attack.Phase==EliteCharge.Stage.Windup,"Pause advanced charge");g.ResumeRun();
   Move(new Vector3(4,0,0));attack.Tick(t+g.Chapter.eliteWindup+.01f);float deadline=Time.time+3;while(attack.Phase==EliteCharge.Stage.Charging&&Time.time<deadline){attack.Tick(t+g.Chapter.eliteWindup+.02f);yield return null;}Check(attack.Phase==EliteCharge.Stage.Recovery&&attack.Hits==0&&g.PlayerHealth.CurrentHealth==hp&&attack.LockedDirection==locked,"Sidestep did not evade locked charge");float before=boss.Health.CurrentHealth;boss.TakeBullet(100,Vector3.forward,false);Check(Mathf.Abs(before-boss.Health.CurrentHealth-145)<.01f,"Recovery damage bonus missing");yield return Photo("08-charge-recovery");
   boss.Agent.Warp(new Vector3(0,0,7));Move(Vector3.zero);attack.Initialize(g,boss);t=Time.time+2;attack.Tick(t);attack.Tick(t+g.Chapter.eliteWindup+.01f);deadline=Time.time+3;while(attack.Phase==EliteCharge.Stage.Charging&&Time.time<deadline){attack.Tick(t+g.Chapter.eliteWindup+.02f);yield return null;}Check(attack.Phase==EliteCharge.Stage.Recovery&&attack.Hits==1&&Mathf.Abs(hp-g.PlayerHealth.CurrentHealth-g.Chapter.eliteDamage)<.01f,"Charge should hit once");float after=g.PlayerHealth.CurrentHealth;
   yield return new WaitForSeconds(.4f);boss.Agent.Warp(new Vector3(0,0,7));Move(Vector3.zero);attack.Initialize(g,boss);t=Time.time+2;attack.Tick(t);g.PlayerHealth.BeginDodge(3);attack.Tick(t+g.Chapter.eliteWindup+.01f);deadline=Time.time+3;while(attack.Phase==EliteCharge.Stage.Charging&&Time.time<deadline){attack.Tick(t+g.Chapter.eliteWindup+.02f);yield return null;}Check(attack.Hits==0&&g.PlayerHealth.CurrentHealth==after,"Dodge immunity ignored");g.PlayerHealth.ClearDodge();
   // A static obstacle in the lane must stop the real NavMeshAgent, not just shorten the graphic.
   var wall=GameObject.CreatePrimitive(PrimitiveType.Cube);wall.name="Validation charge wall";wall.layer=8;wall.transform.position=new Vector3(0,1,-4);wall.transform.localScale=new Vector3(6,2,1);Physics.SyncTransforms();boss.Agent.Warp(new Vector3(0,0,7));Move(Vector3.zero);attack.Initialize(g,boss);t=Time.time+2;attack.Tick(t);Check(attack.EndPoint.z>-3.6f,"Charge warning crosses wall");Move(new Vector3(4,0,0));attack.Tick(t+g.Chapter.eliteWindup+.01f);deadline=Time.time+3;while(attack.Phase==EliteCharge.Stage.Charging&&Time.time<deadline){attack.Tick(t+g.Chapter.eliteWindup+.02f);yield return null;}Check(attack.WallHits==1&&boss.transform.position.z>-3.6f&&attack.Phase==EliteCharge.Stage.Recovery,"Charge crosses wall or fails to stun");attack.Tick(t+g.Chapter.eliteWindup+.02f+1.5f);Check(attack.Phase==EliteCharge.Stage.Recovery,"Wall stun too short");yield return Photo("09-wall-stun");Destroy(wall);yield return null;
   attack.Initialize(g,boss);boss.Agent.Warp(new Vector3(0,0,7));Move(Vector3.zero);t=Time.time+2;attack.Tick(t);boss.Health.Kill();Check(!GameObject.Find("Charge danger lane")&&!GameObject.Find("Charge windup progress"),"Dead elite kept warning");attack.Tick(t+2);Check(attack.Charges==0,"Dead elite still charges");Step(5);Check(!g.Completed&&g.ActiveCount==1,"Victory before escort dies");KillTo(0);Step();Step(1.2f);Check(g.Completed&&g.Paused&&g.Kills==2040&&g.hud.MobilePage=="victory","Camp does not finish");Check(ChapterProgress.Read("quarantine-camp").clears==1&&ChapterProgress.Read("commercial-street").clears==1,"Chapter records not independent");Check(GameObject.Find("Next chapter")&&ChapterCatalog.Unlocked(2),"Camp clear did not unlock third chapter");Step(100);Check(g.Wave==8&&g.ActiveCount==0,"Ninth wave exists");yield return Photo("10-camp-victory");
   old=g;GameObject.Find("Replay chapter").GetComponent<Button>().onClick.Invoke();while(ReferenceEquals(old,SurvivalGame.Instance))yield return null;yield return null;g=SurvivalGame.Instance;Check(Mathf.Abs(Camera.main.orthographicSize-7.7f)<.001f&&Mathf.Abs(g.Chapter.eliteWindup-.7f)<.001f,"Camera or 0.7-second elite warning missing");g.enabled=false;Check(g.Chapter.number==2&&!g.Completed&&g.Growth.Level==1&&g.Kills==0,"Camp replay loaded wrong chapter");old=g;g.BeginChapter(0);while(ReferenceEquals(old,SurvivalGame.Instance))yield return null;yield return null;g=SurvivalGame.Instance;Check(Mathf.Abs(Camera.main.orthographicSize-7.7f)<.001f&&Mathf.Abs(g.Chapter.eliteWindup-.7f)<.001f,"Camera or 0.7-second elite warning missing");g.enabled=false;Check(g.Chapter.number==1&&g.Chapter.eliteName=="街区暴君"&&!g.Chapter.chargeElite&&g.World.Props.Count(x=>x.Kind==WorldPropKind.Door)==6,"First chapter lost original behavior");g.hud.OpenHome();yield return Photo("11-return-home");
   File.WriteAllText(Path.Combine(output,"camp-pass.json"),"{\"passed\":true,\"enemies\":2040,\"peakAlive\":270,\"fullPoolBackpressureAndRefill\":true,\"routeLegs\":"+legs+",\"lockedAndUnlockedSelection\":true,\"independentMapsAndRecords\":true,\"allClearFiveSecondBreak\":true,\"chargeTelegraphEscapeHitDodgeWallDeath\":true,\"replayAndReturn\":true}");Debug.Log("CAMP_PASS");Application.Quit(0);
  }
 }
}
