using System;
using System.IO;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;
namespace DeadDistrict {
 public sealed class ChapterAtmosphereValidation:MonoBehaviour {
  static bool started;string output;SurvivalGame g;MobilePreferences.Data original;readonly List<string> reports=new List<string>();
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var a=RuntimeLaunch.Arguments();if(started||Array.IndexOf(a,"-chapter-atmosphere-smoke")<0)return;started=true;ChapterProgress.IsolatedValidation=true;SurvivalGame.Instance.CombatValidation=true;SceneManager.sceneLoaded+=Ready;var v=new GameObject("Opt-in chapter ambience validation").AddComponent<ChapterAtmosphereValidation>();DontDestroyOnLoad(v);int i=Array.IndexOf(a,"-validation-output");v.output=i>=0?a[i+1]:Application.persistentDataPath;Directory.CreateDirectory(v.output);v.StartCoroutine(v.Run());}
  static void Ready(Scene s,LoadSceneMode m){if(SurvivalGame.Instance)SurvivalGame.Instance.CombatValidation=true;}
  void Check(bool ok,string why){if(!ok)throw new Exception(why);}
  void Move(Vector3 p){var c=g.PlayerHealth.GetComponent<CharacterController>();c.enabled=false;c.transform.position=new Vector3(p.x,0,p.z);c.enabled=true;Camera.main.transform.position=c.transform.position+new Vector3(-14,21,-14);Physics.SyncTransforms();}
  IEnumerator Photo(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(output,name+".png"));yield return new WaitForSecondsRealtime(.2f);}
  IEnumerator Run(){original=MobilePreferences.Current;var stack=new Stack<IEnumerator>();stack.Push(Core());while(stack.Count>0){object item=null;bool more=false;string fail=null;try{more=stack.Peek().MoveNext();if(more)item=stack.Peek().Current;}catch(Exception e){fail=e.ToString();}if(fail!=null){Time.timeScale=1;MobilePreferences.Set(original);File.WriteAllText(Path.Combine(output,"ambience-failure.txt"),fail);Debug.LogError(fail);Application.Quit(1);yield break;}if(!more){stack.Pop();continue;}if(item is IEnumerator nested)stack.Push(nested);else yield return item;}}
  IEnumerator Core(){
   for(int chapter=0;chapter<3;chapter++){
    Time.timeScale=1;if(chapter>0)SceneManager.LoadScene(ChapterCatalog.Get(chapter).sceneName);yield return null;yield return null;g=SurvivalGame.Instance;g.enabled=false;g.Growth.Enabled=false;g.Supplies.Clear();g.WeaponCrates.Clear();var pref=original;pref.music=0;pref.sfx=1;pref.reducedFlash=false;MobilePreferences.Set(pref);
    var root=GameObject.Find("Chapter ambience");Check(root,"Missing chapter ambience");var sites=root.GetComponentsInChildren<EnvironmentSite>();var particles=root.GetComponentsInChildren<ParticleSystem>();int cap=particles.Sum(p=>p.main.maxParticles);Check(cap<=320&&root.GetComponentsInChildren<Collider>().Length==0&&root.GetComponentsInChildren<Light>().Length==0,"Unbounded or blocking environment");foreach(var p in particles){Check(!p.collision.enabled&&!p.lights.enabled&&!p.main.useUnscaledTime,"Unsafe particle configuration");Check(p.GetComponent<Renderer>().sharedMaterials.All(m=>m&&m.shader.isSupported),"Unsupported material");}
    var bed=sites.First(s=>s.global);yield return new WaitForSeconds(1.5f);Check(bed.Voice&&bed.Voice.isPlaying&&bed.Voice.volume>.01f,"Missing audible ambient bed");float volume=bed.Voice.volume;g.Sound.Shot();typeof(SurvivalGame).GetProperty("ShotsFired").SetValue(g,g.ShotsFired+1);yield return new WaitForSeconds(.3f);Check(bed.Voice.volume<volume*.7f,"Combat did not duck ambience");yield return new WaitForSeconds(1);Check(bed.Voice.volume>volume*.9f,"Ambient level did not recover");
    var local=sites.First(s=>!s.global&&s.Voice&&!s.intermittent);Move(local.transform.position+Vector3.back*3);yield return new WaitForSeconds(1.5f);Check(local.Voice.isPlaying&&local.Voice.volume>.02f,"Local source inaudible close to prop");Move(local.transform.position+Vector3.right*(local.range+6));yield return new WaitForSeconds(.5f);Check(!local.Active&&!local.Voice.isPlaying,"Local source does not stop outside range");
    Move(Vector3.zero);yield return new WaitForSeconds(3);g.PauseForShell();yield return Photo("chapter-"+(chapter+1)+"-overview");g.ResumeRun();
    var landmark=chapter==0?local:sites.First(s=>s.name==(chapter==1?"Generator vibration":"Leaking pipe"));Move(landmark.transform.position+new Vector3(3,0,-5));yield return new WaitForSeconds(3);g.PauseForShell();yield return Photo("chapter-"+(chapter+1)+"-detail");float age=particles.FirstOrDefault(p=>p.isPaused)?.time??0;int sample=bed.Voice.timeSamples;yield return new WaitForSecondsRealtime(.3f);Check(bed.Voice.timeSamples==sample&&!bed.Voice.isPlaying,"Pause advances ambient audio");var frozen=particles.FirstOrDefault(p=>p.isPaused);Check(!frozen||Mathf.Abs(frozen.time-age)<.001f,"Pause advances ambient particles");g.ResumeRun();yield return new WaitForSeconds(.5f);Check(bed.Voice.isPlaying,"Ambient did not resume");
    pref.sfx=0;MobilePreferences.Set(pref);yield return null;Check(sites.Where(s=>s.Voice).All(s=>s.Voice.volume==0&&!s.Voice.isPlaying),"Mute leaves ambience playing");pref.sfx=1;pref.reducedFlash=true;MobilePreferences.Set(pref);yield return new WaitForSeconds(.6f);Check(bed.Voice.isPlaying,"Unmute did not restart ambience");g.PauseForShell();yield return Photo("chapter-"+(chapter+1)+"-comfort");g.ResumeRun();pref.reducedFlash=false;MobilePreferences.Set(pref);
    if(chapter==2){var electric=sites.First(s=>s.intermittent);Move(electric.transform.position+Vector3.back*3);int before=electric.BurstCount;yield return new WaitForSeconds(8.5f);Check(electric.BurstCount>before,"No intermittent electrical sparks");}
    Move(new Vector3(200,0,200));yield return new WaitForSeconds(.5f);Check(sites.Where(s=>!s.global).All(s=>!s.Active)&&particles.All(p=>p.particleCount==0),"Distant particles not cleared");Move(Vector3.zero);yield return new WaitForSeconds(.5f);Check(sites.Any(s=>!s.global&&s.Active),"Return did not restore local atmosphere");
    g.hud.OpenHome();yield return null;yield return null;Check(g.Paused&&sites.All(s=>!s.Voice||!s.Voice.isPlaying),"Menu leaks ambience");typeof(SurvivalGame).GetProperty("Completed").SetValue(g,true);yield return null;yield return null;Check(particles.All(p=>p.particleCount==0)&&sites.All(s=>!s.Active),"Victory leaves ambient effects active");reports.Add("{\"chapter\":"+(chapter+1)+",\"sites\":"+sites.Length+",\"particleCap\":"+cap+",\"distanceAudioAndCulling\":true,\"pauseMuteDuckMenu\":true}");
   }
   MobilePreferences.Set(original);SceneManager.sceneLoaded-=Ready;File.WriteAllText(Path.Combine(output,"ambience-pass.json"),"{\"passed\":true,\"chapters\":["+string.Join(",",reports)+"]}");Debug.Log("CHAPTER_AMBIENCE_PASS");Application.Quit(0);
  }
 }
}
