using System;
using System.Collections;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEngine;
using UnityEngine.UI;
namespace DeadDistrict {
 public sealed class FeedbackPolishValidation:MonoBehaviour {
  SurvivalGame g;string output;bool originalSfx;float audioPeak;
  const BindingFlags Private=BindingFlags.Instance|BindingFlags.NonPublic;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var a=RuntimeLaunch.Arguments();if(Array.IndexOf(a,"-feedback-polish-smoke")<0)return;var v=new GameObject("Opt-in feedback polish validation").AddComponent<FeedbackPolishValidation>();int n=Array.IndexOf(a,"-validation-output");v.output=n>=0?a[n+1]:Application.persistentDataPath;Directory.CreateDirectory(v.output);if(SurvivalGame.Instance)SurvivalGame.Instance.CombatValidation=true;v.StartCoroutine(v.Run());}
  void Check(bool ok,string why){if(!ok)throw new Exception(why);}
  void Set(string name,object value){typeof(SurvivalGame).GetProperty(name).SetValue(g,value);}
  void Refresh(){typeof(SurvivalHud).GetField("nextRefresh",Private).SetValue(g.hud,0f);g.hud.Refresh();}
  IEnumerator Photo(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Application.isMobilePlatform?name:Path.Combine(output,name));yield return new WaitForSecondsRealtime(.2f);}
  IEnumerator Run(){var core=Core();while(true){object item=null;bool more=false;string fail=null;try{more=core.MoveNext();if(more)item=core.Current;}catch(Exception e){fail=e.ToString();}if(fail!=null){Time.timeScale=1;if(g&&g.Sound.SfxEnabled!=originalSfx)g.Sound.ToggleSfx();File.WriteAllText(Path.Combine(output,"feedback-failure.txt"),fail);Debug.LogError("FEEDBACK_POLISH_FAIL "+fail);Application.Quit(1);yield break;}if(!more)yield break;yield return item;}}
  IEnumerator Core(){yield return null;yield return null;g=SurvivalGame.Instance;g.CombatValidation=true;g.Growth.Enabled=false;g.config.aimRange=0;g.Supplies.Clear();g.WeaponCrates.Clear();originalSfx=g.Sound.SfxEnabled;if(!originalSfx)g.Sound.ToggleSfx();
   Check(!g.TryReload(),"Full magazine accepts reload");Set("Ammo",70);Refresh();GameObject.Find("Reload").GetComponent<Button>().onClick.Invoke();Check(g.Reloading&&g.Ammo==70&&!g.TryReload(),"Manual rifle reload/duplicate guard");Check(Mathf.Abs(g.WeaponReloadSeconds-1f)<.01f,"Rifle reload duration");yield return new WaitForSeconds(1.08f);Check(!g.Reloading&&g.Ammo==100,"Manual rifle did not finish without enemies");
   Check(g.CollectShotgun(),"Shotgun fixture");Set("Ammo",12);Refresh();GameObject.Find("Reload").GetComponent<Button>().onClick.Invoke();Check(g.Reloading&&g.Sound.ShotgunReloadsPlayed==1,"Shotgun reload not requested");var voice=GameObject.Find("Reserved weapon reload").GetComponent<AudioSource>();Check(voice.clip.name=="Reload"&&voice.volume>.5f,"Full reload sound missing");
   Check(Mathf.Abs(g.WeaponReloadSeconds-1.3f)<.01f,"Shotgun reload duration");var ring=GameObject.Find("Reload").transform.Find("Availability ring").GetComponent<ActionGlyph>();int changedFrames=0;float lastProgress=ring.Progress;var samples=new float[256];for(int frame=0;frame<14;frame++){for(int i=0;i<20;i++)g.Sound.Shot();yield return null;if(ring.Progress>lastProgress)changedFrames++;lastProgress=ring.Progress;voice.GetOutputData(samples,0);foreach(float v in samples)audioPeak=Mathf.Max(audioPeak,Mathf.Abs(v));Check(voice.isPlaying&&voice.clip.name=="Reload","Combat voices interrupt reload");}
   Check(changedFrames>=10,"Reload ring is not updating each render frame: "+changedFrames);Check(audioPeak>.001f,"Reload audio output is silent");g.TogglePause();float progress=g.ReloadProgress;yield return new WaitForSecondsRealtime(.25f);Check(Mathf.Abs(g.ReloadProgress-progress)<.001f&&!g.TryReload()&&!voice.isPlaying,"Paused reload advanced");g.TogglePause();yield return new WaitForSeconds(1.4f);Check(g.Ammo==g.config.shotgunMagazineSize&&!g.Reloading&&!voice.isPlaying,"Shotgun completion failed");
   Set("Ammo",14);Check(g.TryReload(),"Second reload");Check(g.SwitchWeapon()&&!g.Reloading&&!voice.isPlaying,"Switch did not cancel reload sound");Check(g.Sound.WeaponSwitchesPlayed==1&&g.Sound.WeaponSwitchAudioPlaying,"Switch sound missing");for(int i=0;i<24;i++)g.Sound.Shot();Check(g.Sound.WeaponSwitchAudioPlaying,"Combat voices interrupted switch sound");Check(g.SwitchWeapon()&&g.Ammo==14&&!g.Reloading,"Switch gave free ammo");Check(g.BeginGrenadeAim()&&!g.TryReload(),"Aiming allowed reload");g.EndGrenadeAim(false);Check(g.TryRoll()&&!g.TryReload(),"Rolling allowed reload");Refresh();Check(GameObject.Find("Dodge").transform.Find("Count or cooldown").GetComponent<Text>().text=="","Numeric cooldown still visible");yield return new WaitForSeconds(.5f);Check(g.TryReload()&&g.ApplySupply(SupplyKind.Ammo)&&g.Ammo==g.config.shotgunMagazineSize&&!g.Reloading&&!voice.isPlaying,"Ammo pickup failed to cancel reload");
   g.enabled=false;Set("Wave",1);Set("Elapsed",60f);Set("NextHorde",float.PositiveInfinity);Refresh();Set("Elapsed",63f);Set("NextHorde",68f);Refresh();var banner=GameObject.Find("Wave announcement");Check(banner&&GameObject.Find("Wave title").GetComponent<Text>().text.Contains("2")&&GameObject.Find("Wave subtitle").GetComponent<Text>().text.Contains("5"),"Countdown missing");Check(banner.GetComponent<RectTransform>().anchorMax.y==1,"Banner is not at the top edge");Check(GameObject.Find("Help").GetComponent<Text>().text=="","Discovery tips still visible");Check(banner.GetComponentsInChildren<Graphic>().All(x=>!x.raycastTarget),"Wave banner captures controls");yield return Photo("wave-countdown.png");
   g.TogglePause();Refresh();Check(!banner.activeSelf,"Banner overlays pause menu");g.TogglePause();Set("Wave",2);Set("Elapsed",68f);Set("NextHorde",float.PositiveInfinity);Refresh();Check(!banner.activeSelf,"Redundant wave-start banner still visible");yield return Photo("wave-start-clear.png");Set("Elapsed",74f);Refresh();Check(!banner.activeSelf,"Start banner never hides");
   if(g.Sound.SfxEnabled!=originalSfx)g.Sound.ToggleSfx();File.WriteAllText(Path.Combine(output,"feedback-pass.json"),JsonUtility.ToJson(new Report{passed=true,manualRifleAndShotgunReload=true,fullDuplicatePauseAimRollGuards=true,switchAndPickupCancelSound=true,dedicatedReloadSurvivesCombatVoices=true,reloadAudioPeak=audioPeak,countdownOnlyNoStartBanner=true,smoothRingFrameChanges=changedFrames,weaponSwitchSoundSurvivesCombat=true,shorterReloads=true,bannerDoesNotCaptureInput=true},true));Debug.Log("FEEDBACK_POLISH_PASS");Application.Quit(0);
  }
  [Serializable]class Report{public bool passed,manualRifleAndShotgunReload,fullDuplicatePauseAimRollGuards,switchAndPickupCancelSound,dedicatedReloadSurvivesCombatVoices,countdownOnlyNoStartBanner,bannerDoesNotCaptureInput;public bool weaponSwitchSoundSurvivesCombat,shorterReloads;public int smoothRingFrameChanges;public float reloadAudioPeak;}
 }
}
