using System;
using System.Collections;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
namespace DeadDistrict {
 public sealed class FreightValidation:MonoBehaviour {
  SurvivalGame g;string output;float clock;int total,peak,legs;static bool started;
  static readonly BindingFlags Private=BindingFlags.Instance|BindingFlags.NonPublic;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var a=RuntimeLaunch.Arguments();if(started||!a.Contains("-freight-smoke"))return;started=true;ChapterProgress.IsolatedValidation=true;SurvivalGame.Instance.CombatValidation=true;SceneManager.sceneLoaded+=(s,m)=>{if(SurvivalGame.Instance)SurvivalGame.Instance.CombatValidation=true;};var v=new GameObject("Opt-in freight validation").AddComponent<FreightValidation>();DontDestroyOnLoad(v.gameObject);int n=Array.IndexOf(a,"-validation-output");v.output=n>=0?a[n+1]:Application.persistentDataPath;Directory.CreateDirectory(v.output);v.StartCoroutine(v.Run());}
  void Check(bool value,string why){if(!value)throw new Exception(why);}
  void Step(float dt=.025f){clock+=dt;typeof(SurvivalGame).GetProperty("Elapsed").SetValue(g,clock);typeof(SurvivalGame).GetMethod("SpawnDirector",Private).Invoke(g,new object[]{clock});Check(g.ActiveCount==g.Enemies.Count(z=>z.Alive)&&g.ActiveCount<=g.config.maxAlive,"Population accounting");peak=Mathf.Max(peak,g.ActiveCount);}
  void FillWave(int wave){
   float filledAt=clock,backpressureProbeSeconds=0,minAngle=180,maxAngle=-180;int[] mixture=new int[6];int seen=0;bool hitCap=false;var spawns=new System.Collections.Generic.HashSet<string>();
   Action record=()=>{foreach(var e in g.Enemies.Where(z=>z.Alive)){if(!spawns.Add(e.Slot+":"+e.SpawnCount))continue;seen++;if(wave==1&&e.Kind==EnemyKind.Normal&&e.Slot>=g.OpeningCount){var delta=e.transform.position-g.PlayerPosition;float angle=Mathf.DeltaAngle((float)typeof(SurvivalGame).GetField("hordeAngle",Private).GetValue(g)*Mathf.Rad2Deg,Mathf.Atan2(delta.z,delta.x)*Mathf.Rad2Deg);minAngle=Mathf.Min(minAngle,angle);maxAngle=Mathf.Max(maxAngle,angle);Check(Mathf.Abs(e.Health.CurrentHealth-g.config.enemyHealth*g.CurrentWave.health)<.02f&&e.Agent.speed<2.5f,"Wave health or zombie speed wrong");}mixture[(int)e.Kind+(e.IsElite?3:0)]++;Check(!Physics.CheckCapsule(e.transform.position+Vector3.up*.5f,e.transform.position+Vector3.up*1.4f,.35f,1<<8),"Enemy born inside cover");Check((e.transform.position-g.PlayerPosition).magnitude>(wave==1&&e.Slot<g.OpeningCount?7:g.MinimumReinforcementDistance-.1f),"Enemy born too close");if(!(wave==1&&e.Slot<g.OpeningCount))Check(g.IsReinforcementOffscreen(e.transform.position),"Enemy born on screen");}};
   record();
   for(int i=0;g.PendingEnemies>0&&i<4000;i++){
    if(g.ActiveCount==g.config.maxAlive){record();int pending=g.PendingEnemies;Step(2);backpressureProbeSeconds+=2;Check(g.PendingEnemies==pending&&g.ActiveCount==g.config.maxAlive&&g.Wave==wave&&float.IsPositiveInfinity(g.NextHorde),"Full pool lost pending enemies or overlapped waves");hitCap=true;KillTo(75);}
    Step();record();
   }
   Check(g.PendingEnemies==0&&g.Wave==wave&&seen==g.CurrentWave.Count,"Increased wave queue or count wrong "+wave);total+=seen;
   if(wave==1){// Exclude the deliberate full-pool hold used to test backpressure from arrival cadence.
    float duration=clock-filledAt-backpressureProbeSeconds,spread=maxAngle-minAngle;Check(duration<24&&spread>120,"Wave arrival pressure too weak: seconds="+duration+" spread="+spread);File.WriteAllText(Path.Combine(output,"arrival-pressure.json"),"{\"firstWaveFillSeconds\":"+duration.ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"approachSpanDegrees\":"+spread.ToString(System.Globalization.CultureInfo.InvariantCulture)+"}");}
   foreach(var group in g.CurrentWave.groups.GroupBy(x=>new{x.kind,x.elite}))Check(mixture[(int)group.Key.kind+(group.Key.elite?3:0)]==group.Sum(x=>x.count),"Increased wave mixture wrong");
   if(g.CurrentWave.Count>g.config.maxAlive)Check(hitCap,"Larger wave did not exercise queue refill");
  }
  void KillTo(int n){foreach(var e in g.Enemies.Where(z=>z.Alive).Skip(n).ToArray())e.Health.Kill();Check(g.ActiveCount==n,"Kill accounting");}
  void Move(Vector3 p){var c=g.PlayerHealth.GetComponent<CharacterController>();c.enabled=false;c.transform.position=p;c.enabled=true;Physics.SyncTransforms();Camera.main.transform.position=p+new Vector3(-14,21,-14);}
  IEnumerator Photo(string name){typeof(SurvivalHud).GetField("nextRefresh",Private).SetValue(g.hud,0f);g.hud.Refresh();yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(output,name+".png"));yield return new WaitForSecondsRealtime(.2f);}
  IEnumerator Run(){var stack=new System.Collections.Generic.Stack<IEnumerator>();stack.Push(Core());while(stack.Count>0){object item=null;bool more=false;string fail=null;try{more=stack.Peek().MoveNext();if(more)item=stack.Peek().Current;}catch(Exception e){fail=e.ToString();}if(fail!=null){Time.timeScale=1;File.WriteAllText(Path.Combine(output,"freight-failure.txt"),fail);Debug.LogError("FREIGHT_FAIL "+fail);Application.Quit(1);yield break;}if(!more){stack.Pop();continue;}if(item is IEnumerator nested)stack.Push(nested);else yield return item;}}
  IEnumerator Core(){yield return null;yield return null;g=SurvivalGame.Instance;Check(Mathf.Abs(Camera.main.orthographicSize-7.7f)<.001f&&Mathf.Abs(g.Chapter.eliteWindup-.7f)<.001f,"Camera or 0.7-second elite warning missing");g.enabled=false;g.Growth.Enabled=false;
   Check(ChapterCatalog.Count==3&&ChapterCatalog.Get(0).waves.Sum(w=>w.Count)==286&&ChapterCatalog.Get(1).waves.Sum(w=>w.Count)==2040,"Earlier chapter budgets changed");Check(!ChapterCatalog.Unlocked(2)&&!g.BeginChapter(2),"Third chapter not initially locked");ChapterProgress.Complete(ChapterCatalog.Get(0).id,300,286);Check(!ChapterCatalog.Unlocked(2),"First clear incorrectly unlocks third");
   g.hud.OpenHome();GameObject.Find("Choose chapter").GetComponent<Button>().onClick.Invoke();Check(!GameObject.Find("Select chapter 2").GetComponent<Button>().interactable,"Locked third card enabled");yield return Photo("01-locked-selection");
   ChapterProgress.Complete(ChapterCatalog.Get(1).id,360,342);g.hud.OpenHome();GameObject.Find("Choose chapter").GetComponent<Button>().onClick.Invoke();Check(ChapterCatalog.Unlocked(2)&&GameObject.Find("Select chapter 2").GetComponent<Button>().interactable,"Second clear does not unlock third");
   foreach(var size in new[]{new Vector2Int(1334,750),new Vector2Int(1800,830)}){Screen.SetResolution(size.x,size.y,false);for(int i=0;i<8;i++)yield return null;Canvas.ForceUpdateCanvases();for(int i=0;i<3;i++){var card=GameObject.Find("Chapter card "+i).GetComponent<RectTransform>();var points=new Vector3[4];card.GetWorldCorners(points);Check(points.All(p=>p.x>=0&&p.x<=Screen.width&&p.y>=0&&p.y<=Screen.height),"Chapter card off screen "+i);foreach(var text in card.GetComponentsInChildren<Text>())Check(text.preferredHeight<=text.rectTransform.rect.height+2,"Chapter text clips "+text.name);}yield return Photo("02-selection-"+size.x);}
   var old=g;Check(g.BeginChapter(2),"Freight load rejected");while(ReferenceEquals(old,SurvivalGame.Instance))yield return null;yield return null;g=SurvivalGame.Instance;Check(Mathf.Abs(Camera.main.orthographicSize-7.7f)<.001f&&Mathf.Abs(g.Chapter.eliteWindup-.7f)<.001f,"Camera or 0.7-second elite warning missing");g.enabled=false;g.Growth.Enabled=false;
   Check(g.Chapter.number==3&&SceneManager.GetActiveScene().name=="FreightDepot"&&g.Growth.Level==1&&g.Kills==0&&g.Ammo==100&&!g.Dead,"Third start not fresh");Check(g.World.Props.All(x=>x.Kind!=WorldPropKind.Door),"Phantom street doors");foreach(var site in g.Chapter.weaponSites)typeof(WeaponLoot).GetMethod("SpawnNear",Private).Invoke(g.WeaponCrates,new object[]{site});Check(g.WeaponCrates.ActiveCount==3,"Opening weapons missing");
   var root=GameObject.Find("Freight depot");Check(root&&!GameObject.Find("Quarantine camp")&&!GameObject.Find("Abandoned district"),"Freight map not independent");foreach(var r in root.GetComponentsInChildren<MeshRenderer>())foreach(var m in r.sharedMaterials)Check(m&&m.shader.isSupported,"Unsupported freight material");
   Move(Vector3.zero);yield return Photo("03-depot-opening");Move(new Vector3(-9,0,7));yield return Photo("04-warehouse-route");Move(new Vector3(-26,0,-20));yield return Photo("05-tanker-route");Move(new Vector3(8,0,22));yield return Photo("06-container-route");
   var controller=g.PlayerHealth.GetComponent<CharacterController>();Move(Vector3.zero);
   foreach(var dest in new[]{new Vector3(0,0,43),new Vector3(43,0,0),new Vector3(0,0,-43),new Vector3(-43,0,0),new Vector3(-8,0,-20),new Vector3(8,0,22),Vector3.zero}){var path=new NavMeshPath();Check(NavMesh.CalculatePath(controller.transform.position,dest,NavMesh.AllAreas,path)&&path.status==NavMeshPathStatus.PathComplete,"Disconnected freight route "+dest);foreach(var corner in path.corners.Skip(1)){float deadline=Time.time+15;Vector3 delta;do{delta=corner-controller.transform.position;delta.y=0;if(delta.magnitude<.18f)break;controller.Move(delta.normalized*Mathf.Min(12*Time.deltaTime,delta.magnitude)+Vector3.down*2*Time.deltaTime);yield return null;}while(Time.time<deadline);delta=corner-controller.transform.position;delta.y=0;Check(delta.magnitude<.2f,"Controller blocked: "+controller.transform.position+" toward "+corner);}legs++;}
   foreach(var cover in root.GetComponentsInChildren<StreetOcclusion>().Take(2)){var b=cover.obstacle.bounds;Move(new Vector3(b.center.x,0,b.max.z+.8f));yield return new WaitForSeconds(1.2f);Check(cover.ObscuringPlayer&&cover.Opacity<.2f&&cover.obstacle.enabled,"Warehouse occlusion failed: "+cover.name);yield return Photo("07-occlusion-"+cover.name);Move(Vector3.zero);yield return new WaitForSeconds(1.4f);Check(cover.Opacity>.99f,"Warehouse opacity not restored");}
   Move(Vector3.zero);g.Supplies.Clear();g.WeaponCrates.Clear();clock=Time.time;g.StartChapter();
   for(int wave=1;wave<=8;wave++){FillWave(wave);Step(90);Check(g.Wave==wave,"Wave overlaps previous");if(wave==8)break;KillTo(1);Step(90);Check(g.Wave==wave&&float.IsPositiveInfinity(g.NextHorde),"Wave advances before full clear");KillTo(0);Step();Check(Mathf.Abs(g.NextHorde-clock-5)<.001f,"Break not five seconds");if(wave==5)Check(g.RestSuppliesPlaced==2,"Recovery supplies missing");Step(4.8f);Check(g.Wave==wave&&g.ActiveCount==0,"Early wave");Step(.21f);yield return null;}
   Check(total==4262&&peak==320&&g.Elite&&g.Elite.AcidAttack&&!g.Elite.ChargeAttack&&!g.Elite.EliteAttack,"Freight budget or elite wrong");foreach(var e in g.Enemies.Where(z=>z.Alive&&!z.IsElite).Skip(1).ToArray())e.Health.Kill();var boss=g.Elite;var attack=boss.AcidAttack;g.PlayerHealth.ResetForSpawn();float hp=g.PlayerHealth.CurrentHealth;
   Move(Vector3.zero);boss.Agent.Warp(new Vector3(0,0,7));attack.Initialize(g,boss);Check(Mathf.Abs(g.Chapter.acidFlightTime-.22f)<.001f,"Acid flight timing changed");float fire=g.Chapter.eliteWindup+.01f,land=fire+g.Chapter.acidFlightTime+.01f;float t=Time.time+2;attack.Tick(t);Check(attack.Phase==EliteAcid.Stage.Windup&&attack.TargetCount>=5,"Acid volley must telegraph at least five reachable targets");var target=attack.TargetAt(0);Check(Vector3.Distance(target,g.PlayerPosition)<.7f,"First target misses initial player position");attack.Tick(t+g.Chapter.eliteWindup-.05f);Check(attack.Volleys==0&&g.PlayerHealth.CurrentHealth==hp&&attack.ActivePools==0,"Acid hits before warning");yield return Photo("08-acid-warning");g.PauseForShell();float frozen=Time.time;yield return new WaitForSecondsRealtime(.2f);attack.Tick(t+4);Check(Time.time==frozen&&attack.Phase==EliteAcid.Stage.Windup,"Pause advances acid");g.ResumeRun();
   Move(new Vector3(0,0,-4));attack.Tick(t+fire);Check(attack.Phase==EliteAcid.Stage.Flight&&attack.Volleys==1&&attack.TargetAt(0)==target,"Acid follows player or does not fly");attack.Tick(t+land);Check(attack.Phase==EliteAcid.Stage.Recovery&&attack.ActivePools==attack.TargetCount&&attack.Hits==0&&g.PlayerHealth.CurrentHealth==hp,"Sidestep cannot evade acid");float before=boss.Health.CurrentHealth;boss.TakeBullet(100,Vector3.forward,false);Check(Mathf.Abs(before-boss.Health.CurrentHealth-145)<.01f,"Acid recovery damage bonus missing");yield return Photo("09-acid-pools");attack.Tick(t+land+3.01f);Check(attack.ActivePools==0&&!GameObject.Find("Acid pool 0"),"Pools persist beyond lifetime");attack.Tick(t+land+3.28f);Check(attack.Phase==EliteAcid.Stage.Hunt,"Acid does not resume pursuit");
   Move(Vector3.zero);boss.Agent.Warp(new Vector3(0,0,7));attack.Initialize(g,boss);t=Time.time+2;attack.Tick(t);attack.Tick(t+fire);attack.Tick(t+land);Check(attack.Hits==1&&Mathf.Abs(hp-g.PlayerHealth.CurrentHealth-g.Chapter.eliteDamage)<.01f,"Acid impact damage wrong");float after=g.PlayerHealth.CurrentHealth;attack.Tick(t+land+.48f);Check(g.PlayerHealth.CurrentHealth==after,"Acid damage ticks every frame");yield return new WaitForSeconds(.35f);attack.Tick(t+land+.71f);Check(attack.Hits==2&&Mathf.Abs(after-g.PlayerHealth.CurrentHealth-g.Chapter.acidTickDamage)<.01f,"Acid tick damage wrong");after=g.PlayerHealth.CurrentHealth;
   g.PlayerHealth.BeginDodge(3);attack.Tick(t+land+1.42f);Check(g.PlayerHealth.CurrentHealth==after,"Dodge fails in acid");g.PlayerHealth.ClearDodge();g.PlayerHealth.BeginGrowthProtection(.5f);attack.Tick(t+land+2.13f);Check(g.PlayerHealth.CurrentHealth==after,"Growth protection fails in acid");yield return new WaitForSeconds(.6f);
   // A pool must not damage through a static wall even when the radius overlaps the player.
   var wall=GameObject.CreatePrimitive(PrimitiveType.Cube);wall.layer=8;wall.transform.position=new Vector3(0,1,-.7f);wall.transform.localScale=new Vector3(4,2,.2f);Physics.SyncTransforms();Move(new Vector3(0,0,-1.4f));attack.Tick(t+land+2.84f);Check(g.PlayerHealth.CurrentHealth==after,"Acid damages through wall");attack.Cancel();Check(attack.ActivePools==0&&!GameObject.Find("Acid danger boundary 0")&&!GameObject.Find("Acid projectile 0"),"Cancelled acid left effects");Destroy(wall);yield return null;
   var preferences=MobilePreferences.Current;var comfort=preferences;comfort.reducedFlash=true;MobilePreferences.Set(comfort);Move(Vector3.zero);boss.Agent.Warp(new Vector3(0,0,7));attack.Initialize(g,boss);t=Time.time+2;attack.Tick(t);Check(GameObject.Find("Acid danger boundary 0")&&GameObject.Find("Acid danger boundary 0").GetComponent<LineRenderer>().startColor.a>.8f,"Reduced flash hides essential warning");yield return Photo("10-reduced-flash-warning");MobilePreferences.Set(preferences);MobilePreferences.Flush();
   boss.Health.Kill();Check(attack.ActivePools==0&&!GameObject.Find("Acid danger boundary 0")&&!GameObject.Find("Acid pool 0")&&!GameObject.Find("Acid elite identity"),"Dead elite kept acid");attack.Tick(t+3);Check(attack.Volleys==0,"Dead elite still attacks");Step(5);Check(!g.Completed&&g.ActiveCount==1,"Victory before escort dies");KillTo(0);Step();Step(1.2f);Check(g.Completed&&g.Paused&&g.Kills==4262&&g.hud.MobilePage=="victory","Third chapter not complete");Check(ChapterProgress.Read("freight-depot").clears==1&&ChapterProgress.Read("quarantine-camp").clears==1&&ChapterProgress.Read("commercial-street").clears==1,"Third records not independent");Check(!GameObject.Find("Next chapter"),"Nonexistent fourth chapter offered");Step(100);Check(g.Wave==8&&g.ActiveCount==0,"Ninth wave exists");yield return Photo("11-freight-victory");
   old=g;GameObject.Find("Replay chapter").GetComponent<Button>().onClick.Invoke();while(ReferenceEquals(old,SurvivalGame.Instance))yield return null;yield return null;g=SurvivalGame.Instance;Check(Mathf.Abs(Camera.main.orthographicSize-7.7f)<.001f&&Mathf.Abs(g.Chapter.eliteWindup-.7f)<.001f,"Camera or 0.7-second elite warning missing");g.enabled=false;Check(g.Chapter.number==3&&!g.Completed&&g.Growth.Level==1&&g.Kills==0,"Freight replay wrong");old=g;g.BeginChapter(1);while(ReferenceEquals(old,SurvivalGame.Instance))yield return null;yield return null;g=SurvivalGame.Instance;Check(Mathf.Abs(Camera.main.orthographicSize-7.7f)<.001f&&Mathf.Abs(g.Chapter.eliteWindup-.7f)<.001f,"Camera or 0.7-second elite warning missing");g.enabled=false;Check(g.Chapter.number==2&&g.Chapter.chargeElite&&!g.Chapter.acidElite,"Camp elite changed");old=g;g.BeginChapter(0);while(ReferenceEquals(old,SurvivalGame.Instance))yield return null;yield return null;g=SurvivalGame.Instance;Check(Mathf.Abs(Camera.main.orthographicSize-7.7f)<.001f&&Mathf.Abs(g.Chapter.eliteWindup-.7f)<.001f,"Camera or 0.7-second elite warning missing");g.enabled=false;Check(g.Chapter.number==1&&!g.Chapter.acidElite&&!g.Chapter.chargeElite&&g.World.Props.Count(x=>x.Kind==WorldPropKind.Door)==6,"First chapter behavior changed");g.hud.OpenHome();GameObject.Find("Choose chapter").GetComponent<Button>().onClick.Invoke();yield return Photo("12-all-cleared");
   File.WriteAllText(Path.Combine(output,"freight-pass.json"),"{\"passed\":true,\"enemies\":4262,\"peakAlive\":320,\"fullPoolBackpressureAndRefill\":true,\"routeLegs\":"+legs+",\"threeChapterUnlocksAndRecords\":true,\"allClearFiveSecondBreak\":true,\"acidWarningFlightEscapeImpactTickDodgeWallDeath\":true,\"replayAndReturn\":true}");Debug.Log("FREIGHT_PASS");Application.Quit(0);
  }
 }
}
