using System;
using System.Collections;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.UI;
namespace DeadDistrict {
 public sealed class GrowthValidation:MonoBehaviour {
  static bool started;string output;bool capture;SurvivalGame g;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var args=RuntimeLaunch.Arguments();bool photo=Array.IndexOf(args,"-growth-capture")>=0;if(started||(!photo&&Array.IndexOf(args,"-growth-smoke")<0))return;started=true;var v=new GameObject("Opt-in growth validation").AddComponent<GrowthValidation>();DontDestroyOnLoad(v.gameObject);v.capture=photo;int n=Array.IndexOf(args,"-validation-output");v.output=n>=0?args[n+1]:Application.persistentDataPath;Directory.CreateDirectory(v.output);if(SurvivalGame.Instance)SurvivalGame.Instance.CombatValidation=true;v.StartCoroutine(v.Run());}
  void Check(bool ok,string why){if(!ok)throw new Exception(why);}
  IEnumerator Run(){var core=Core();while(true){object current=null;bool more=false;string fail=null;try{more=core.MoveNext();if(more)current=core.Current;}catch(Exception ex){fail=ex.ToString();}if(fail!=null){Time.timeScale=1;File.WriteAllText(Path.Combine(output,"growth-failure.txt"),fail);Debug.LogError("GROWTH_VALIDATION_FAIL "+fail);Application.Quit(1);yield break;}if(!more)yield break;yield return current;}}
  Vector3 Floor(Vector3 v){Check(NavMesh.SamplePosition(v,out var n,.7f,NavMesh.AllAreas),"Missing fixture floor "+v);return n.position;}
  IEnumerator Photo(string name){if(!capture)yield break;float scale=Time.timeScale;Time.timeScale=0;yield return new WaitForSecondsRealtime(.1f);yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Application.isMobilePlatform?name:Path.Combine(output,name));yield return new WaitForSecondsRealtime(.25f);Time.timeScale=scale;}
  void Fund(){while(g.Growth.Points==0)g.Growth.Award(EnemyKind.Normal);Check(g.Growth.TryOpen(),"Funded level did not open");}
  IEnumerator Core(){yield return null;yield return null;g=SurvivalGame.Instance;g.CombatValidation=true;g.Growth.Enabled=true;g.Supplies.Clear();g.WeaponCrates.Clear();var growth=g.Growth;var forward=Camera.main.transform.forward;forward.y=0;forward.Normalize();var right=Camera.main.transform.right;right.y=0;right.Normalize();
   Check(growth.Level==1&&growth.Experience==0&&growth.Required==300,"Initial growth state");var victim=g.Enemies[0];victim.Spawn(Floor(g.PlayerPosition+forward*4),0);victim.Health.SetHealth(26);float until=Time.time+2;while(victim.Alive&&Time.time<until)yield return null;Check(!victim.Alive&&growth.Experience==10&&g.ShotsFired==1,"Actual rifle kill did not grant XP");g.EnemyKilled(victim);Check(growth.Experience==10,"Duplicate retirement granted XP");g.config.aimRange=0;
   victim.Spawn(Floor(g.PlayerPosition+forward*4),0,EnemyKind.Runner);victim.Health.Kill();victim.Spawn(Floor(g.PlayerPosition+forward*4),0,EnemyKind.Brute);victim.Health.Kill();Check(growth.Experience==60&&!growth.Choosing,"Kill batch opened menu inside damage iteration");
   yield return null;Check(!growth.Choosing&&!g.Paused&&growth.Experience==60,"Old 60 XP threshold still opens upgrade");
   for(int i=0;i<9;i++){victim.Spawn(Floor(g.PlayerPosition+forward*4),0);victim.Health.Kill();}yield return null;Check(growth.Experience==150&&!growth.Choosing&&!g.Paused,"Old 150 XP threshold still opens upgrade");for(int i=0;i<14;i++){victim.Spawn(Floor(g.PlayerPosition+forward*4),0);victim.Health.Kill();}Check(growth.Experience==290&&!growth.TryOpen(),"Upgrade opened before 300 XP");victim.Spawn(Floor(g.PlayerPosition+forward*4),0);victim.Health.Kill();Check(growth.Experience==0&&growth.Level==2&&growth.Points==1&&!growth.Choosing,"300 XP kill opened menu mid-batch");
   Check(g.BeginGrenadeAim(),"Pending gesture fixture");g.SetGrenadeAim(Vector2.right);SurvivalInput.Move=Vector2.right;yield return null;Check(!growth.Choosing&&!g.Paused&&growth.Points==1,"Earned point interrupted battle");Check(growth.TryOpen()&&!growth.Choosing&&growth.OpenRequested,"Aim did not defer manual opening");g.EndGrenadeAim(false);yield return null;Check(growth.Choosing&&g.Paused&&Time.timeScale==0&&!g.IsGrenadeAiming&&SurvivalInput.Move==Vector2.zero,"Upgrade did not pause/cancel gameplay gestures");Check(growth.Offers.Count==3&&growth.Offers.Distinct().Count()==3&&!growth.Offers.Contains(UpgradeKind.Scatter),"Initial offers duplicate/locked shotgun");
   float elapsed=g.Elapsed;int ammo=g.Ammo,grenades=g.Grenades;g.TogglePause();Check(g.Paused&&!g.TryRoll()&&!g.SwitchWeapon()&&!g.BeginGrenadeAim()&&!g.World.Interact()&&!g.ApplySupply(SupplyKind.Ammo),"Upgrade overlay leaked an action");g.ThrowGrenade();yield return new WaitForSecondsRealtime(.4f);Check(g.Elapsed==elapsed&&g.Ammo==ammo&&g.Grenades==grenades,"Battle progressed in choice screen");yield return Photo("upgrade-choices.png");
   var safe=GameObject.Find("Safe area").GetComponent<RectTransform>();var oldMin=safe.anchorMin;var oldMax=safe.anchorMax;
   safe.anchorMin=new Vector2(.055f,.035f);safe.anchorMax=new Vector2(.945f,1);Canvas.ForceUpdateCanvases();
   var modal=GameObject.Find("Upgrade choices").GetComponent<RectTransform>();var corners=new Vector3[4];modal.GetWorldCorners(corners);
   Check(Vector2.Distance(corners[0],Vector2.zero)<1&&Vector2.Distance(corners[2],new Vector2(Screen.width,Screen.height))<1,"Upgrade dimmer does not cover full screen with safe-area insets");
   yield return Photo("upgrade-fullscreen-safe-area.png");safe.anchorMin=oldMin;safe.anchorMax=oldMax;Canvas.ForceUpdateCanvases();
   var first=growth.Offers[0];int offer=growth.OfferId;GameObject.Find("Upgrade card 0").GetComponent<Button>().onClick.Invoke();Check(growth.Level==2&&growth.Experience==0&&growth.Required==450&&growth.Rank(first)==1&&growth.Points==0&&!g.Paused&&!growth.Choosing&&Time.timeScale==1,"UI choice did not apply once/resume");Check(!growth.Choose(0,offer)&&growth.Level==2,"Duplicate choice accepted");Check(g.CollectShotgun(),"Shotgun unlock fixture");
   int selections=1;for(int iteration=0;iteration<100;iteration++){
    bool complete=Enum.GetValues(typeof(UpgradeKind)).Cast<UpgradeKind>().All(k=>RunGrowth.Cap(k)>0?growth.Rank(k)==RunGrowth.Cap(k):growth.Rank(k)>0);if(complete)break;
    Fund();Check(growth.Offers.Distinct().Count()==3&&growth.Offers.All(growth.Eligible),"Unavailable/duplicate upgrade offered");Check(!growth.Choose(0,growth.OfferId),"Opening guard accepted same-frame tap");yield return new WaitForSecondsRealtime(.32f);
    int chosen=0;float best=-1;for(int i=0;i<3;i++){var k=growth.Offers[i];float score=growth.Rank(k)==0?100:RunGrowth.Cap(k)>0?50-growth.Rank(k):0;if(score>best){best=score;chosen=i;}}
    Check(growth.Choose(chosen,growth.OfferId),"Valid choice rejected");selections++;
   }
   Check(Enum.GetValues(typeof(UpgradeKind)).Cast<UpgradeKind>().All(k=>RunGrowth.Cap(k)>0?growth.Rank(k)==RunGrowth.Cap(k):growth.Rank(k)>0),"Upgrade coverage/caps not reached");Check(g.config.shotgunPellets==13&&Mathf.Abs(g.config.roundsPerSecond-19.2f)<.01f&&Mathf.Abs(g.config.reloadSeconds-.5f)<.01f&&Mathf.Abs(g.config.grenadeRadius-6.4f)<.01f,"Capped stats incorrect");Check(g.config.playerHealth==g.PlayerHealth.MaximumHealth&&g.PlayerHealth.CurrentHealth<=g.PlayerHealth.MaximumHealth,"Max health/healing inconsistent");
   // Saturating the capped pool must still leave three useful, distinct choices.
   Fund();Check(growth.Offers.All(k=>RunGrowth.Cap(k)==0),"Capped upgrades reappeared");yield return new WaitForSecondsRealtime(.32f);growth.Choose(0,growth.OfferId);selections++;
   // Bank enough XP for two levels, and verify the second choice cannot reuse the first tap.
   int targetLevel=growth.Level+2;while(growth.Level<targetLevel)growth.Award(EnemyKind.Normal);Check(growth.TryOpen(),"Multi-level queue missing");int oldLevel=growth.Level;offer=growth.OfferId;yield return new WaitForSecondsRealtime(.32f);Check(growth.Choose(0,offer)&&growth.Choosing&&g.Paused&&growth.Level==oldLevel&&growth.Points==1&&!growth.Choose(0,offer)&&!growth.Choose(0,growth.OfferId),"Multi-level queue replay/guard");yield return new WaitForSecondsRealtime(.32f);Check(growth.Choose(0,growth.OfferId)&&!growth.Choosing&&growth.Level==oldLevel&&growth.Points==0,"Queued level lost");
   g.TogglePause();yield return Photo("run-upgrades.png");g.TogglePause();
   if(g.CurrentWeapon!=WeaponKind.Rifle)g.SwitchWeapon();g.config.aimRange=20;victim.Spawn(Floor(g.PlayerPosition+forward*4),0);victim.Health.SetHealth(1000000);int shots=g.ShotsFired;float hp=victim.Health.CurrentHealth;until=Time.time+2;while(g.ShotsFired==shots&&Time.time<until)yield return null;Check(g.ShotsFired==shots+1&&Mathf.Abs((hp-victim.Health.CurrentHealth)-g.config.bulletDamage)<.1f,"Upgraded rifle damage not used");
   until=Time.time+8;while(!g.Reloading&&Time.time<until)yield return null;Check(g.Reloading&&g.Ammo==0,"Upgraded gun did not empty/reload");float began=Time.time;while(g.Reloading&&Time.time-began<2)yield return null;float reload=Time.time-began;Check(Mathf.Abs(reload-g.WeaponReloadSeconds)<.12f,"Upgraded reload duration "+reload);victim.Retire();g.config.aimRange=0;
   Check(g.SwitchWeapon(),"Switch to upgraded shotgun");victim.Spawn(Floor(g.PlayerPosition+forward*3),0);victim.Health.SetHealth(1000000);int pellets=g.PelletVisuals;ammo=g.Ammo;until=Time.time+2;while(g.PelletVisuals==pellets&&Time.time<until)yield return null;Check(g.PelletVisuals-pellets==13&&g.Ammo==ammo-1&&victim.Health.CurrentHealth<1000000,"Upgraded pellet count or shell consumption");victim.Retire();g.SwitchWeapon();
   var center=g.PlayerPosition+forward*6;Vector3 blastVictim=Vector3.zero;bool found=false;for(int i=0;i<16;i++){var point=center+Quaternion.Euler(0,i*22.5f,0)*right*5.8f;if(NavMesh.SamplePosition(point,out var nav,.3f,NavMesh.AllAreas)&&!Physics.Linecast(center+Vector3.up*.7f,nav.position+Vector3.up*.9f,1<<8)){blastVictim=nav.position;found=true;break;}}Check(found,"Expanded blast fixture unavailable");victim.Spawn(blastVictim,0,EnemyKind.Brute);Check(g.BeginGrenadeAim(),"Upgraded grenade start");g.SetGrenadeAim(Vector2.up*(.16f+.84f*.4f));g.EndGrenadeAim(true);yield return new WaitForSeconds(1);Check(Mathf.Abs(victim.Health.CurrentHealth-30)<.01f,"Expanded grenade radius/damage not applied: "+victim.Health.CurrentHealth);victim.Retire();
   Check(g.TryRoll(),"Upgraded dodge start");began=Time.time;while(!g.CanRoll&&Time.time-began<3)yield return null;float cooldown=Time.time-began;Check(cooldown>1.55f&&cooldown<1.8f,"Upgraded dodge cooldown "+cooldown);
   Fund();g.PlayerHealth.Kill();Check(g.Dead&&!growth.Choosing&&!g.Paused&&Time.timeScale==1,"Death trapped upgrade overlay");g.Restart();yield return null;yield return null;g=SurvivalGame.Instance;Check(g.Growth.Level==1&&g.Growth.Experience==0&&g.config.bulletDamage==26&&g.config.roundsPerSecond==12&&g.config.shotgunPellets==7&&g.config.rollCooldown==3.2f&&g.config.playerHealth==100&&g.PlayerHealth.MaximumHealth==100&&g.Ammo==100&&g.ShotgunAmmo==g.config.shotgunMagazineSize,"New run retained upgrades/config mutation");yield return Photo("growth-hud.png");
   File.WriteAllText(Path.Combine(output,"growth-pass.json"),"{\"passed\":true,\"device\":\""+SystemInfo.deviceModel+"\",\"firstUpgradeAt300Not60Or150Or290\":true,\"nextUpgradeRequires450\":true,\"realKillExperience\":true,\"variantExperience\":true,\"duplicateDeathGuard\":true,\"threeDistinctEligibleOffers\":true,\"pauseAndGestureGuards\":true,\"fullScreenDimmerWithSafeAreaInsets\":true,\"uiChoiceApplied\":true,\"allNineUpgradesAndCaps\":true,\"queuedPointsAndReplayGuard\":true,\"manualOpeningOnly\":true,\"actualUpgradedRifleDamage\":true,\"actualReloadTimer\":true,\"thirteenPelletsOneShell\":true,\"expandedGrenadeDamageRadius\":true,\"actualDodgeCooldown\":true,\"deathAndRestartReset\":true}");Debug.Log("GROWTH_VALIDATION_PASS");Application.Quit(0);
  }
 }
}
