using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.UI;
namespace DeadDistrict {
 public sealed class LauncherImpactValidation:MonoBehaviour {
  string output;SurvivalGame g;MobilePreferences.Data original;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var a=RuntimeLaunch.Arguments();if(Array.IndexOf(a,"-launcher-impact-smoke")<0)return;SurvivalGame.Instance.CombatValidation=true;var v=new GameObject("Opt-in launcher impact validation").AddComponent<LauncherImpactValidation>();int n=Array.IndexOf(a,"-validation-output");v.output=n>=0?a[n+1]:Application.persistentDataPath;Directory.CreateDirectory(v.output);v.StartCoroutine(v.Run());}
  void Check(bool ok,string why){if(!ok)throw new Exception(why);}
  IEnumerator Photo(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(output,name+".png"));yield return new WaitForSecondsRealtime(.15f);}
  IEnumerator Run(){original=MobilePreferences.Current;var stack=new Stack<IEnumerator>();stack.Push(Core());while(stack.Count>0){object item=null;bool more=false;string fail=null;try{more=stack.Peek().MoveNext();if(more)item=stack.Peek().Current;}catch(Exception e){fail=e.ToString();}if(fail!=null){Time.timeScale=1;MobilePreferences.Set(original);File.WriteAllText(Path.Combine(output,"launcher-impact-failure.txt"),fail);Debug.LogError(fail);Application.Quit(1);yield break;}if(!more){stack.Pop();continue;}if(item is IEnumerator nested)stack.Push(nested);else yield return item;}}
  IEnumerator Core(){yield return null;yield return null;g=SurvivalGame.Instance;g.enabled=false;g.Growth.Enabled=false;g.Supplies.Clear();g.WeaponCrates.Clear();var pref=original;pref.reducedFlash=false;MobilePreferences.Set(pref);
   var grenade=GameObject.Find("Grenade").GetComponent<ActionButtonView>();
   for(int setting=0;setting<3;setting++){pref.buttons=setting;MobilePreferences.Set(pref);grenade.Refresh(ActionSymbol.Grenade,true,"2");Canvas.ForceUpdateCanvases();var badge=grenade.transform.Find("Count badge").GetComponent<RectTransform>();var icon=grenade.transform.Find("Action icon").GetComponent<RectTransform>();Check(badge.anchoredPosition.x-badge.rect.width/2>56,"Count overlaps button ring");Check(badge.anchoredPosition.x-badge.rect.width/2>icon.anchoredPosition.x+icon.rect.width/2,"Count overlaps grenade artwork");var corners=new Vector3[4];badge.GetWorldCorners(corners);foreach(var c in corners)Check(Screen.safeArea.Contains(RectTransformUtility.WorldToScreenPoint(null,c)),"Count outside safe area");Check(grenade.transform.Find("Count or cooldown").GetComponent<Text>().text=="×2","Count ambiguous");}
   pref.buttons=1;MobilePreferences.Set(pref);g.hud.Refresh();g.PauseForShell();yield return Photo("01-grenade-count");g.ResumeRun();
   var forward=Camera.main.transform.forward;forward.y=0;forward.Normalize();Check(NavMesh.SamplePosition(g.PlayerPosition+forward*5,out var nav,1,NavMesh.AllAreas),"Target floor missing");var enemy=g.Enemies[0];enemy.Spawn(nav.position,0);enemy.Health.SetHealth(10000);int hits=g.Launcher.VictimsHit;Check(g.Launcher.Launch(g.PlayerPosition+forward*2+Vector3.up*1.2f,enemy.AimPoint,220,3.2f),"Launch failed");float until=Time.time+1;while(g.Launcher.VictimsHit==hits&&Time.time<until)yield return null;Check(g.Launcher.VictimsHit>hits,"No actual impact");yield return new WaitForSeconds(.06f);g.PauseForShell();
   var fire=g.VisualEffects.GetComponentsInChildren<ParticleSystem>().First(p=>p.name=="Grenade Fire"&&p.particleCount>0);var fx=fire.transform.parent;var source=Resources.Load<PackVisuals>("DeadDistrict/PackVisuals").explosion.GetComponentsInChildren<ParticleSystem>().First(p=>p.name=="Fire");Check(fire.GetComponent<ParticleSystemRenderer>().sharedMaterial==source.GetComponent<ParticleSystemRenderer>().sharedMaterial,"Not grenade fire material");Check(!fire.rotationOverLifetime.enabled&&!fire.rotationBySpeed.enabled&&fire.main.startRotation.constant==0,"Fire still spins");Check(fire.main.simulationSpace==ParticleSystemSimulationSpace.World&&!fx.IsChildOf(enemy.transform),"Blast attached to enemy");var before=new ParticleSystem.Particle[2];int count=fire.GetParticles(before);var point=fx.position;var rot=fx.rotation;enemy.transform.rotation=Quaternion.Euler(85,140,65);enemy.transform.position+=Vector3.right*1.8f;yield return null;var after=new ParticleSystem.Particle[2];Check(fire.GetParticles(after)==count&&fx.position==point&&Quaternion.Angle(fx.rotation,rot)<.001f,"Blast follows turning victim");for(int i=0;i<count;i++)Check(Vector3.Distance(before[i].position,after[i].position)<.001f&&Mathf.Abs(before[i].rotation-after[i].rotation)<.001f,"Flame rotated with victim");yield return Photo("02-grenade-style-impact");g.ResumeRun();yield return new WaitForSeconds(.8f);
   var smoke=fx.GetComponentsInChildren<ParticleSystem>().First(p=>p.name=="Rolling blast smoke");Check(smoke.particleCount>=10,"Smoke not sustained at 0.9 s");Check(fire.particleCount==0,"Fire persists behind smoke");g.PauseForShell();yield return Photo("03-stronger-smoke");g.ResumeRun();yield return new WaitForSeconds(1.1f);Check(g.VisualEffects.ActiveLauncherExplosions==0,"Blast did not expire");MobilePreferences.Set(original);File.WriteAllText(Path.Combine(output,"launcher-impact-pass.json"),"{\"passed\":true,\"actualLauncherImpact\":true,\"grenadeFireMaterial\":true,\"noFireSpin\":true,\"independentOfVictimTranslationAndRotation\":true,\"sustainedSmoke\":true,\"countSeparatedFromRingAndIconAtAllButtonSizes\":true}");Debug.Log("LAUNCHER_IMPACT_PASS");Application.Quit(0);
  }
 }
}
