using UnityEngine;
namespace DeadDistrict {
 // Fixed pool; swept flight segments prevent tunnelling through thin cover at low frame rates.
 public sealed class LauncherProjectiles : MonoBehaviour {
  sealed class Round {public GameObject root;public TrailRenderer trail;public LineRenderer core;public ParticleSystem[] glow;public ParticleSystem smoke;public Vector3 from,to,previous;public float age,duration,damage,radius;public bool active;}
  readonly Round[] rounds=new Round[6];readonly Collider[] overlaps=new Collider[16];SurvivalGame game;
  const float BodyRadius=.11f;const int Mask=(1<<0)|(1<<8)|(1<<24);
  public int ShotsLaunched {get;private set;}public int Detonations {get;private set;}public int VictimsHit {get;private set;}public Vector3 LastBlast {get;private set;}
  public int ActiveCount {get {int n=0;foreach(var s in rounds)if(s!=null&&s.active)n++;return n;}}
  public bool ApplyingBlast {get;private set;}
  public int SmokeParticles {get {int n=0;foreach(var s in rounds)if(s!=null)n+=s.smoke.particleCount;return n;}}
  public bool CanLaunch=>ActiveCount<rounds.Length;
  public Vector3 FirstActivePosition {get {foreach(var s in rounds)if(s!=null&&s.active)return s.root.transform.position;return Vector3.zero;}}
  public void Initialize(SurvivalGame owner,GameObject prefab){game=owner;if(!prefab)throw new System.InvalidOperationException("Launcher projectile missing");for(int i=0;i<rounds.Length;i++){var root=Instantiate(prefab,transform);root.name="Pooled launcher round "+i;var trail=root.AddComponent<TrailRenderer>();trail.sharedMaterial=Resources.Load<Material>("DeadDistrict/BulletGlow");trail.time=.09f;trail.startWidth=.18f;trail.endWidth=0;trail.minVertexDistance=.04f;trail.numCapVertices=2;trail.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;trail.receiveShadows=false;var core=root.AddComponent<LineRenderer>();core.sharedMaterial=trail.sharedMaterial;core.useWorldSpace=true;core.positionCount=2;core.startWidth=.015f;core.endWidth=.085f;core.numCapVertices=3;core.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;core.receiveShadows=false;var glow=root.GetComponentsInChildren<ParticleSystem>(true);var smoke=Instantiate(Resources.Load<GameObject>("DeadDistrict/LauncherTrailSmoke"),transform).GetComponent<ParticleSystem>();smoke.name="Pooled launcher smoke "+i;smoke.Stop(false,ParticleSystemStopBehavior.StopEmittingAndClear);root.SetActive(false);rounds[i]=new Round{root=root,trail=trail,core=core,glow=glow,smoke=smoke};}}
  public bool Launch(Vector3 from,Vector3 destination,float damage,float radius){if(!CanLaunch||game.Dead||game.Completed||game.Paused)return false;Round s=null;foreach(var item in rounds)if(!item.active){s=item;break;}if(s==null)return false;
   ShotsLaunched++;s.damage=damage;s.radius=radius;s.from=from;s.to=destination;s.age=0;s.duration=Mathf.Clamp(Vector3.Distance(from,destination)/24,.18f,.8f);s.previous=from;s.active=true;s.root.transform.position=from;if((destination-from).sqrMagnitude>.0001f)s.root.transform.rotation=Quaternion.LookRotation(destination-from);s.root.SetActive(true);s.smoke.Stop(false,ParticleSystemStopBehavior.StopEmittingAndClear);s.smoke.transform.position=from;s.smoke.Play(false);s.trail.Clear();s.trail.startColor=MobilePreferences.Current.reducedFlash?new Color(.8f,.45f,.12f,.55f):new Color(2.0f,1.1f,.2f,.85f);s.trail.endColor=new Color(1,.35f,0,0);s.core.SetPosition(0,from);s.core.SetPosition(1,from);s.core.startColor=new Color(1,.45f,.08f,0);s.core.endColor=MobilePreferences.Current.reducedFlash?new Color(.95f,.52f,.15f,.7f):new Color(2.8f,1.6f,.3f,1);foreach(var ps in s.glow){ps.Stop(false,ParticleSystemStopBehavior.StopEmittingAndClear);var main=ps.main;main.startColor=MobilePreferences.Current.reducedFlash?new Color(.9f,.45f,.08f,.45f):new Color(2,.9f,.1f,.8f);ps.Play(false);}
   // A long barrel may visually reach through a wall before the body does.
   if(Physics.Linecast(game.PlayerPosition+Vector3.up*1.15f,from,out var wall,1<<8,QueryTriggerInteraction.Ignore)){Explode(s,wall.point+wall.normal*.14f);return true;}
   int count=Physics.OverlapSphereNonAlloc(from,BodyRadius,overlaps,Mask,QueryTriggerInteraction.Ignore);if(count>0){Explode(s,from);return true;}return true;
  }
  Vector3 Point(Round s,float age){float t=Mathf.Clamp01(age/s.duration);return Vector3.Lerp(s.from,s.to,t);}
  void Update(){if(!game)return;if(game.Dead||game.Completed){Clear();return;}if(game.Paused)return;Advance(Time.deltaTime);}
  void Advance(float dt){foreach(var s in rounds){if(!s.active)continue;float end=Mathf.Min(s.age+dt,s.duration);int steps=Mathf.Max(1,Mathf.CeilToInt((end-s.age)*32/.2f));float start=s.age;for(int j=1;j<=steps&&s.active;j++){float age=Mathf.Lerp(start,end,(float)j/steps);Vector3 next=Point(s,age),delta=next-s.previous;float distance=delta.magnitude;if(distance>.0001f&&Physics.SphereCast(s.previous,BodyRadius,delta/distance,out var hit,distance,Mask,QueryTriggerInteraction.Ignore)){Explode(s,hit.point+hit.normal*.14f);break;}s.root.transform.position=next;s.smoke.transform.position=next-(s.to-s.from).normalized*.25f;var back=(s.to-s.from).normalized*Mathf.Min(1.25f,Vector3.Distance(s.from,next));s.core.SetPosition(0,next-back);s.core.SetPosition(1,next);if(distance>.0001f)s.root.transform.rotation=Quaternion.LookRotation(delta);s.previous=next;s.age=age;}if(s.active&&s.age>=s.duration-.00001f)Explode(s,s.to);}}
  void Explode(Round s,Vector3 point){s.active=false;s.smoke.Stop(false,ParticleSystemStopBehavior.StopEmitting);s.trail.Clear();s.root.SetActive(false);Detonations++;LastBlast=point;game.VisualEffects.LauncherExplosion(point);game.Sound.LauncherBlast();
   ApplyingBlast=true;try{foreach(var enemy in game.Enemies){if(!enemy.Alive)continue;float distance=Vector3.Distance(enemy.AimPoint,point);if(distance>s.radius)continue;if(Physics.Linecast(point,enemy.AimPoint,1<<8,QueryTriggerInteraction.Ignore))continue;float damage=s.damage*Mathf.Lerp(1,.55f,Mathf.Clamp01(distance/s.radius));VictimsHit++;game.VisualEffects.EnemyImpact(enemy.AimPoint,(enemy.AimPoint-point).normalized,.35f);enemy.TakeBlast(damage,point);}
   game.World.DamageProps(point,s.radius,s.damage);}finally{ApplyingBlast=false;}
  }
  public void Clear(){foreach(var s in rounds)if(s!=null){s.smoke.Stop(false,ParticleSystemStopBehavior.StopEmittingAndClear);s.active=false;s.trail.Clear();s.root.SetActive(false);}}
 }
}
