using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.SceneManagement;
using UnityEngine.UI;
namespace DeadDistrict {
 public sealed class LauncherValidation:MonoBehaviour {
  static bool started;const BindingFlags Private=BindingFlags.Instance|BindingFlags.NonPublic;SurvivalGame g;string output;int photos;float interval;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var args=RuntimeLaunch.Arguments();if(started||!args.Contains("-launcher-smoke"))return;started=true;ChapterProgress.IsolatedValidation=true;if(SurvivalGame.Instance)SurvivalGame.Instance.CombatValidation=true;SceneManager.sceneLoaded+=(s,m)=>{if(SurvivalGame.Instance)SurvivalGame.Instance.CombatValidation=true;};var v=new GameObject("Opt-in launcher validation").AddComponent<LauncherValidation>();DontDestroyOnLoad(v.gameObject);int n=Array.IndexOf(args,"-validation-output");v.output=n>=0?args[n+1]:Application.persistentDataPath;Directory.CreateDirectory(v.output);v.StartCoroutine(v.Run());}
  void Check(bool ok,string why){if(!ok)throw new Exception(why);}
  void SetAmmo(int n){typeof(SurvivalGame).GetProperty("Ammo").SetValue(g,n);}
  void Move(Vector3 p){var c=g.PlayerHealth.GetComponent<CharacterController>();c.enabled=false;c.transform.position=p;c.enabled=true;Physics.SyncTransforms();Camera.main.transform.position=p+new Vector3(-14,21,-14);}
  void Clear(){g.Launcher.Clear();foreach(var e in g.Enemies)if(e.Alive)e.Retire();}
  void Advance(float dt){typeof(LauncherProjectiles).GetMethod("Advance",Private).Invoke(g.Launcher,new object[]{dt});}
  SurvivalEnemy Enemy(int i,Vector3 p){Check(NavMesh.SamplePosition(p,out var h,1,NavMesh.AllAreas),"Fixture lacks floor "+p);var e=g.Enemies[i];e.Spawn(h.position,0,EnemyKind.Normal);e.Health.SetHealth(10000);return e;}
  void Sites(){g.WeaponCrates.Clear();foreach(var p in g.Chapter.weaponSites.Length>0?g.Chapter.weaponSites:new[]{new Vector3(4,0,1),new Vector3(12,0,6),new Vector3(-12,0,-6)})typeof(WeaponLoot).GetMethod("SpawnNear",Private).Invoke(g.WeaponCrates,new object[]{p});Check(g.WeaponCrates.ActiveCount==3,"Missing weapon sites");}
  void Switch(){GameObject.Find("Switch weapon").GetComponent<Button>().onClick.Invoke();}
  IEnumerator Photo(string name){yield return new WaitForSecondsRealtime(.09f);typeof(SurvivalHud).GetField("nextRefresh",Private).SetValue(g.hud,0f);g.hud.Refresh();yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(output,name+".png"));yield return new WaitForSecondsRealtime(.2f);photos++;}
  // Freeze a known early phase so screenshot latency cannot skip the short impact flash.
  IEnumerator BlastPhoto(string name,ParticleSystem[] systems){g.PauseForShell();yield return null;foreach(var ps in systems){ps.Simulate(.07f,false,true,true);ps.Pause(false);}Check(systems.Sum(x=>x.particleCount)>0,"Launcher blast emitted no particles");yield return Photo(name);foreach(var ps in systems)ps.Play(false);g.ResumeRun();}
  IEnumerator Run(){var stack=new Stack<IEnumerator>();stack.Push(Core());while(stack.Count>0){object item=null;bool more=false;string fail=null;try{more=stack.Peek().MoveNext();if(more)item=stack.Peek().Current;}catch(Exception e){fail=e.ToString();}if(fail!=null){Time.timeScale=1;File.WriteAllText(Path.Combine(output,"launcher-failure.txt"),fail);Debug.LogError("LAUNCHER_FAIL "+fail);Application.Quit(1);yield break;}if(!more){stack.Pop();continue;}if(item is IEnumerator nested)stack.Push(nested);else yield return item;}}
  IEnumerator Core(){yield return null;yield return null;g=SurvivalGame.Instance;g.enabled=false;g.Growth.Enabled=false;Sites();Check(!GameObject.Find("Pooled launcher crate"),"Launcher leaked into chapter one");Check(!g.HasAlternateWeapon&&!g.SwitchWeapon(),"Locked weapon switch");ChapterProgress.Complete(g.Chapter.id,300,286);var old=g;Check(g.BeginChapter(1),"Second chapter blocked");while(ReferenceEquals(old,SurvivalGame.Instance))yield return null;yield return null;g=SurvivalGame.Instance;g.enabled=false;g.Growth.Enabled=false;g.ResumeRun();Sites();var loot=GameObject.Find("Pooled launcher crate");Check(loot,"Second chapter launcher missing");Move(loot.transform.position+new Vector3(-2,0,-2));yield return Photo("01-launcher-crate");Move(loot.transform.position);g.PauseForShell();g.WeaponCrates.Tick(Time.time);Check(!g.LauncherUnlocked,"Paused auto pickup");g.ResumeRun();g.WeaponCrates.Tick(Time.time);Check(g.LauncherUnlocked&&g.CurrentWeapon==WeaponKind.Launcher&&g.Ammo==12&&g.WeaponCrates.Collected==1,"Actual launcher pickup");g.WeaponCrates.Tick(Time.time+76);Check(loot.activeSelf,"Full launcher crate consumed");g.WeaponCrates.Clear();g.Supplies.Clear();Move(Vector3.zero);
   var actor=g.PlayerHealth.GetComponentInChildren<LoftActor>();yield return null;yield return new WaitForEndOfFrame();Check(actor.LauncherVisible,"Launcher model missing");Check(g.Sound.HasDistinctLauncherAudio,"Launcher still reuses shotgun/grenade audio");var gun=actor.transform.Find("Grenade launcher");foreach(var r in gun.GetComponentsInChildren<Renderer>())foreach(var m in r.sharedMaterials)Check(m&&m.shader&&m.shader.isSupported,"Unsupported launcher material");Check(Vector3.Distance(actor.Bone((int)HumanBodyBones.RightHand).position,gun.TransformPoint(new Vector3(0,.05f,-.16f)))<.04f,"Launcher right-hand grip");Check(Vector3.Distance(actor.Bone((int)HumanBodyBones.LeftHand).position,gun.TransformPoint(new Vector3(-.02f,.12f,.10f)))<.04f,"Launcher left-hand grip");yield return Photo("02-launcher-equipped");var cam=Camera.main;cam.orthographicSize=2.3f;cam.transform.position=new Vector3(-3,2.7f,4);cam.transform.LookAt(Vector3.up*.9f);yield return Photo("03-launcher-close");cam.orthographicSize=SurvivalGame.GameplayCameraSize;cam.transform.rotation=Quaternion.Euler(48,45,0);Move(Vector3.zero);
   SetAmmo(7);Check(g.CollectShotgun(),"Shotgun pickup after launcher");Check(g.CurrentWeapon==WeaponKind.Shotgun&&g.Ammo==60,"Shotgun state");Switch();Check(g.CurrentWeapon==WeaponKind.Launcher&&g.Ammo==7,"Launcher rounds lost on switch");Check(g.TryReload()&&g.Reloading,"Manual launcher reload");yield return null;Check(g.Sound.ReloadAudioPlaying||!g.Sound.SfxEnabled,"Launcher reload audio missing");Switch();Check(g.CurrentWeapon==WeaponKind.Rifle&&g.Ammo==100,"Rifle magazine changed");yield return new WaitForSeconds(1.6f);Switch();Switch();Check(g.CurrentWeapon==WeaponKind.Launcher&&g.Ammo==7&&!g.Reloading,"Cancelled reload refilled launcher");Check(g.ApplySupply(SupplyKind.Ammo)&&g.Ammo==12&&!g.Reloading,"Launcher ammo supply");g.PauseForShell();Check(!g.SwitchWeapon()&&!g.TryReload()&&!g.CollectLauncher(),"Pause guards");g.ResumeRun();Check(g.BeginGrenadeAim()&&!g.SwitchWeapon(),"Aiming switch guard");g.EndGrenadeAim(false);
   Check(g.TryRoll(),"Launcher roll");yield return null;Check(!actor.LauncherVisible&&!g.SwitchWeapon(),"Roll gun visibility/guard");g.enabled=true;yield return new WaitForSeconds(.6f);g.enabled=false;Check(actor.LauncherVisible,"Launcher did not return after roll");Move(Vector3.zero);
   // Pause and switching preserve a launched round; no damage is applied on launch.
   var a=Enemy(0,new Vector3(0,0,7));var b=Enemy(1,new Vector3(1.2f,0,7));g.Launcher.enabled=false;Check(g.Launcher.Launch(new Vector3(0,1.3f,0),a.AimPoint,220,3.2f),"Round launch");var flightFrom=new Vector3(0,1.3f,0);var flightTo=a.AimPoint;var flightDirection=(flightTo-flightFrom).normalized;float travelled=0;
   for(int sample=0;sample<4;sample++){Advance(.02f);var displacement=g.Launcher.FirstActivePosition-flightFrom;Check(Vector3.Cross(displacement,flightDirection).magnitude<.002f,"Launcher must travel straight without lob arc");Check(Vector3.Dot(displacement,flightDirection)>travelled,"Launcher flight did not advance");travelled=Vector3.Dot(displacement,flightDirection);}
   Check(a.Health.CurrentHealth==10000&&g.Launcher.ActiveCount==1,"Hitscan instead of flight");yield return Photo("04-projectile-flight");g.Launcher.enabled=true;g.PauseForShell();var position=g.Launcher.FirstActivePosition;yield return new WaitForSecondsRealtime(.25f);Check(g.Launcher.FirstActivePosition==position&&a.Health.CurrentHealth==10000,"Pause advanced round");g.ResumeRun();g.Launcher.enabled=false;Switch();Check(g.CurrentWeapon==WeaponKind.Rifle&&g.Launcher.ActiveCount==1,"Switch cancelled in-flight round");Advance(1);Check(g.Launcher.ActiveCount==0&&a.Health.CurrentHealth<10000&&b.Health.CurrentHealth<10000,"Area blast misses group");yield return Photo("05-area-blast");Clear();
   // Single low-frame-rate step must still hit a thin wall, and splash cannot cross it.
   a=Enemy(0,new Vector3(0,0,7));var wall=GameObject.CreatePrimitive(PrimitiveType.Cube);wall.name="Validation thin wall";wall.layer=8;wall.transform.position=new Vector3(0,2,4);wall.transform.localScale=new Vector3(8,4,.12f);Physics.SyncTransforms();int blasts=g.Launcher.Detonations;g.Launcher.Launch(new Vector3(0,1.3f,0),a.AimPoint,220,3.2f);Advance(1);Check(g.Launcher.Detonations==blasts+1&&g.Launcher.LastBlast.z<4&&a.Health.CurrentHealth==10000,"Thin wall tunnelling or splash leak");Destroy(wall);yield return null;Clear();
   // Low cover intersects the direct line but would be cleared by the former lob arc.
   a=Enemy(0,new Vector3(0,0,7));wall=GameObject.CreatePrimitive(PrimitiveType.Cube);wall.layer=8;wall.transform.position=new Vector3(0,.8f,4);wall.transform.localScale=new Vector3(8,1.6f,.12f);Physics.SyncTransforms();blasts=g.Launcher.Detonations;g.Launcher.Launch(new Vector3(0,1.3f,0),a.AimPoint,220,3.2f);Advance(1);Check(g.Launcher.Detonations==blasts+1&&g.Launcher.LastBlast.z<4&&a.Health.CurrentHealth==10000,"Direct-fire round must strike low cover instead of flying over it");Destroy(wall);yield return null;Clear();
   a=Enemy(0,new Vector3(0,0,7));b=Enemy(1,new Vector3(1.2f,0,7));var hidden=Enemy(2,new Vector3(0,0,9));wall=GameObject.CreatePrimitive(PrimitiveType.Cube);wall.layer=8;wall.transform.position=new Vector3(0,2,8);wall.transform.localScale=new Vector3(8,4,.12f);Physics.SyncTransforms();g.Launcher.Launch(new Vector3(0,1.3f,0),a.AimPoint,220,3.2f);Advance(1);Check(a.Health.CurrentHealth<10000&&b.Health.CurrentHealth<10000&&hidden.Health.CurrentHealth==10000,"Blast should hit exposed enemies only");Destroy(wall);yield return null;Clear();
   for(int i=0;i<6;i++)Check(g.Launcher.Launch(new Vector3(0,1.3f,0),new Vector3(0,1,10),220,3.2f),"Pool slot "+i);Check(!g.Launcher.CanLaunch&&!g.Launcher.Launch(Vector3.up,Vector3.forward*10,220,3.2f)&&g.Launcher.ActiveCount==6,"Pool overwrite");Clear();
   // Independent blast pool, readable flash mode, pause freeze and short effect lifetime.
   yield return new WaitForSeconds(2f);var prefs=MobilePreferences.Current;var bright=prefs;bright.reducedFlash=false;MobilePreferences.Set(bright);
   g.VisualEffects.LauncherExplosion(new Vector3(0,1.1f,5));var fx=GameObject.Find("LauncherBlast(Clone)");Check(fx,"Dedicated launcher blast missing");var systems=fx.GetComponentsInChildren<ParticleSystem>(true);Check(systems.Sum(x=>x.main.maxParticles)<=40&&fx.GetComponentsInChildren<Light>().Length==0,"Unbounded launcher effects or extra light");float luminance=systems.Sum(x=>x.main.startColor.color.maxColorComponent);yield return BlastPhoto("07-new-impact",systems);
   g.PauseForShell();Check(g.Paused&&Time.timeScale==0,"Blast pause state");yield return null;yield return new WaitForEndOfFrame();float frozenAge=systems[0].time;yield return new WaitForSecondsRealtime(.25f);Check(Mathf.Abs(systems[0].time-frozenAge)<.001f,"Paused blast keeps animating "+frozenAge+" -> "+systems[0].time);g.ResumeRun();yield return new WaitForSeconds(2f);Check(g.VisualEffects.ActiveLauncherExplosions==0,"Launcher blast lingers");
   var low=bright;low.reducedFlash=true;MobilePreferences.Set(low);g.VisualEffects.LauncherExplosion(new Vector3(0,1.1f,5));fx=GameObject.Find("LauncherBlast(Clone)");Check(fx.GetComponentsInChildren<ParticleSystem>(true).Sum(x=>x.main.startColor.color.maxColorComponent)<luminance*.5f,"Reduced flash not applied");yield return BlastPhoto("08-reduced-impact",fx.GetComponentsInChildren<ParticleSystem>(true));for(int i=0;i<8;i++)g.VisualEffects.LauncherExplosion(new Vector3(i*.2f,1,5));Check(g.VisualEffects.ActiveLauncherExplosions==4,"Launcher blast pool grew");yield return new WaitForSeconds(2f);MobilePreferences.Set(prefs);MobilePreferences.Flush();
   // Exercise real targeting, ammo decrement, cadence and automatic reload for a full magazine.
   while(g.CurrentWeapon!=WeaponKind.Launcher)Switch();g.CollectLauncher();Move(Vector3.zero);a=Enemy(0,new Vector3(0,0,5.5f));Check(g.CanAutoTarget(a),"Cadence target outside firing viewport");g.Launcher.enabled=true;g.enabled=true;int shots=g.LauncherShotsFired;float first=-1,last=-1,deadline=Time.time+18;int observed=shots;
   while(g.LauncherShotsFired<shots+12&&Time.time<deadline){a.Agent.Warp(new Vector3(0,0,5.5f));if(g.LauncherShotsFired!=observed){if(first<0)first=Time.time;observed=g.LauncherShotsFired;}yield return null;}last=Time.time;Check(g.LauncherShotsFired==shots+12&&g.Ammo==0,"Launcher full magazine automatic fire: shots="+(g.LauncherShotsFired-shots)+" ammo="+g.Ammo+" visible="+g.CanAutoTarget(a));interval=(last-first)/11;Check(interval>.85f&&interval<1.15f,"Launcher rate "+interval);Clear();yield return null;Check(g.Reloading,"Empty launcher did not auto reload");yield return new WaitForSeconds(1.55f);Check(g.Ammo==12&&!g.Reloading&&g.Sound.LauncherSoundsPlayed==g.LauncherShotsFired,"Launcher refill/sounds");g.enabled=false;
   // Existing generic upgrades must apply to the new weapon even when acquired afterwards.
   var ranks=(int[])typeof(RunGrowth).GetField("ranks",Private).GetValue(g.Growth);float damage=g.config.launcherDamage,rate=g.config.launcherRoundsPerSecond,reload=g.config.launcherReloadSeconds;foreach(var k in new[]{UpgradeKind.Damage,UpgradeKind.FireRate,UpgradeKind.Reload}){ranks[(int)k]=1;typeof(RunGrowth).GetMethod("Apply",Private).Invoke(g.Growth,new object[]{k});}Check(Mathf.Abs(g.config.launcherDamage-damage*1.2f)<.001f&&Mathf.Abs(g.WeaponFireRate-rate*1.12f)<.001f&&Mathf.Abs(g.WeaponReloadSeconds-reload*.9f)<.001f,"Launcher generic upgrades");
   g.Launcher.Launch(Vector3.up*1.3f,new Vector3(0,1,10),220,3.2f);g.PlayerHealth.Kill();yield return null;Check(g.Dead&&g.Launcher.ActiveCount==0&&!g.SwitchWeapon()&&g.WeaponCrates.ActiveCount==0,"Death cleanup");ChapterProgress.Complete(g.Chapter.id,300,342);old=g;g.BeginChapter(2);while(ReferenceEquals(old,SurvivalGame.Instance))yield return null;yield return null;g=SurvivalGame.Instance;g.enabled=false;g.Growth.Enabled=false;Sites();Check(!g.LauncherUnlocked&&g.CurrentWeapon==WeaponKind.Rifle&&g.LauncherAmmo==12&&g.config.launcherDamage==220&&GameObject.Find("Pooled launcher crate"),"Third chapter fresh state/launcher location");loot=GameObject.Find("Pooled launcher crate");Move(loot.transform.position+new Vector3(-2,0,-2));yield return Photo("06-third-chapter-crate");
   File.WriteAllText(Path.Combine(output,"launcher-pass.json"),"{\"passed\":true,\"laterChapterLootOnly\":true,\"automaticPickup\":true,\"threeWeaponCycleIndependentAmmo\":true,\"reloadCancelSupplyAudio\":true,\"holdAndRoll\":true,\"flightPauseSwitch\":true,\"straightFlightSamples\":4,\"lowCoverCollision\":true,\"areaDamage\":true,\"thinWallAndSplashProtection\":true,\"boundedPool\":6,\"independentAudio\":true,\"blastPoolPauseComfortLifetime\":true,\"fullMagazine\":12,\"meanShotInterval\":"+interval.ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"autoReload\":true,\"growth\":true,\"deathAndNextChapterReset\":true,\"screenshots\":"+photos+"}");Debug.Log("LAUNCHER_PASS");Application.Quit(0);
  }
 }
}
