using System;
using System.Collections;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEngine.UI;
using UnityEngine.EventSystems;
using UnityEngine.Rendering;
using UnityEngine.Rendering.Universal;
using System.Reflection;
namespace DeadDistrict {
 public sealed class MobileUXValidation:MonoBehaviour {
  static bool started;string output;SurvivalGame g;MobilePreferences.Data original;bool captured;int shotsBefore;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var a=RuntimeLaunch.Arguments();if(started||Array.IndexOf(a,"-mobile-ux-smoke")<0)return;started=true;var v=new GameObject("Opt-in mobile UX validation").AddComponent<MobileUXValidation>();DontDestroyOnLoad(v.gameObject);int n=Array.IndexOf(a,"-validation-output");v.output=n>=0?a[n+1]:Application.persistentDataPath;Directory.CreateDirectory(v.output);v.StartCoroutine(v.Run());}
  void Check(bool value,string message){if(!value)throw new Exception(message);}
  void Click(string name){var o=GameObject.Find(name);Check(o!=null,"Missing visible button: "+name);var b=o.GetComponent<Button>();Check(b&&b.interactable,"Disabled button: "+name);b.onClick.Invoke();}
  IEnumerator Photo(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Application.isMobilePlatform?name:Path.Combine(output,name));yield return new WaitForSecondsRealtime(.2f);}
  void Inside(RectTransform rect){var corners=new Vector3[4];rect.GetWorldCorners(corners);foreach(var c in corners){var p=RectTransformUtility.WorldToScreenPoint(null,c);Check(p.x>=Screen.safeArea.xMin-2&&p.x<=Screen.safeArea.xMax+2&&p.y>=Screen.safeArea.yMin-2&&p.y<=Screen.safeArea.yMax+2,"Outside safe area: "+rect.name+" "+p);}}
  void CheckPage(){Canvas.ForceUpdateCanvases();foreach(var b in GameObject.Find("Mobile shell").GetComponentsInChildren<Button>())Inside(b.GetComponent<RectTransform>());foreach(var t in GameObject.Find("Mobile shell").GetComponentsInChildren<Text>()){var mask=t.GetComponentInParent<RectMask2D>();if(mask)Inside(mask.rectTransform);else Inside(t.rectTransform);}}
  IEnumerator Run(){var core=Core();while(true){object item=null;bool more=false;string failure=null;try{more=core.MoveNext();if(more)item=core.Current;}catch(Exception e){failure=e.ToString();}if(failure!=null){if(captured){MobilePreferences.Set(original);MobilePreferences.Flush();}Time.timeScale=1;File.WriteAllText(Path.Combine(output,"mobile-ux-failure.txt"),failure);Debug.LogError("MOBILE_UX_FAIL "+failure);Application.Quit(1);yield break;}if(!more)yield break;yield return item;}}
  IEnumerator Core(){
   yield return null;yield return null;g=SurvivalGame.Instance;original=MobilePreferences.Current;captured=true;MobilePreferences.Set(MobilePreferences.Defaults);
   Check(g.hud.MobilePage=="home"&&g.Paused&&!g.RunStarted&&g.ActiveCount==0&&g.Elapsed==0,"Cold launch started combat");yield return new WaitForSecondsRealtime(.5f);Check(g.ShotsFired==0&&g.Elapsed==0&&g.ActiveCount==0,"Menu advances combat");Check(!GameObject.Find("Continue current run"),"Cold launch offers nonexistent save");CheckPage();yield return Photo("mobile-home.png");
   var volume=FindObjectsByType<Volume>(FindObjectsSortMode.None).First(v=>v.isGlobal);volume.profile.TryGet<Bloom>(out var bloom);float normalBloom=bloom.intensity.value;float grenadeDamage=g.config.grenadeDamage,grenadeRadius=g.config.grenadeRadius;Click("Home settings");GameObject.Find("Music volume").GetComponent<Slider>().value=.27f;GameObject.Find("Sound volume").GetComponent<Slider>().value=.63f;Click("Joystick 1");Click("Button size 2");Click("Shake 0");Click("Flash 1");
   yield return new WaitForSecondsRealtime(.6f);MobilePreferences.Reload();var d=MobilePreferences.Current;Check(Mathf.Abs(d.music-.27f)<.001f&&Mathf.Abs(d.sfx-.63f)<.001f&&d.joystick==1&&d.buttons==2&&d.shake==0&&d.reducedFlash,"Settings failed round-trip persistence");Check(bloom.intensity.value<normalBloom&&g.config.grenadeDamage==grenadeDamage&&g.config.grenadeRadius==grenadeRadius,"Comfort setting changed gameplay or did not lower bloom");CheckPage();yield return Photo("mobile-settings.png");
   if(!Application.isMobilePlatform){Screen.SetResolution(1334,750,false);yield return new WaitForSecondsRealtime(.5f);CheckPage();yield return Photo("mobile-settings-small.png");Screen.SetResolution(1800,830,false);yield return new WaitForSecondsRealtime(.4f);}
   Click("Settings back");Click("Start new run");Check(g.hud.MobilePage=="help"&&!g.RunStarted,"First-run help missing");CheckPage();yield return Photo("mobile-help.png");g.CombatValidation=true;Click("Help back");Check(g.RunStarted&&!g.Paused&&g.hud.MobilePage==""&&MobilePreferences.Current.helpSeen,"First-run start failed");g.Growth.Enabled=false;g.config.aimRange=0;yield return null;var cam=Camera.main;var cameraPosition=cam.transform.position;typeof(SurvivalGame).GetField("cameraKick",BindingFlags.Instance|BindingFlags.NonPublic).SetValue(g,.2f);yield return new WaitForEndOfFrame();Check(Vector3.Distance(cam.transform.position,cameraPosition)<.001f,"Disabled shake still moves camera");
   var input=GameObject.Find("Movement joystick").GetComponent<SurvivalInput>();Check(input.Floating,"Floating joystick not applied");foreach(string name in new[]{"Grenade","Dodge","Reload","Switch weapon"}){var button=GameObject.Find(name);Inside(button.GetComponent<RectTransform>());var icon=button.transform.Find("Action icon").GetComponent<Image>();Check(icon.sprite&&!icon.raycastTarget&&icon.preserveAspect,"Imported action icon missing or intercepts touch: "+name);Check(!button.transform.Find("Fallback action icon").gameObject.activeSelf,"Old hand-drawn action icon still visible");}
   var left=new PointerEventData(EventSystem.current){pointerId=11,position=new Vector2(Screen.width*.18f,Screen.height*.24f)};input.OnPointerDown(left);left.position+=new Vector2(45,25);input.OnDrag(left);Check(SurvivalInput.Move.magnitude>.1f,"Floating joystick cannot move");Vector2 movement=SurvivalInput.Move;Vector3 center=input.transform.position;
   var right=new PointerEventData(EventSystem.current){pointerId=22,position=RectTransformUtility.WorldToScreenPoint(null,GameObject.Find("Grenade").transform.position)};input.OnPointerDown(right);Check(input.transform.position==center,"Second finger stole joystick");var grenade=GameObject.Find("Grenade").GetComponent<GrenadeAimInput>();grenade.OnPointerDown(right);right.position+=new Vector2(-95,45);grenade.OnDrag(right);Check(g.GrenadeAimValid&&SurvivalInput.Move==movement,"Grenade and joystick interfere");input.OnPointerUp(right);grenade.OnPointerUp(left);Check(g.IsGrenadeAiming&&SurvivalInput.Move==movement,"Wrong pointer released a gesture");
   g.TogglePause();Check(g.Paused&&!g.IsGrenadeAiming&&SurvivalInput.Move==Vector2.zero,"Pause retained gesture state");Click("Mobile resume");grenade.OnPointerUp(right);input.OnPointerUp(left);Check(g.GrenadesThrown==0&&SurvivalInput.Move==Vector2.zero,"Stale touch threw grenade after resume");yield return Photo("mobile-controls-large.png");
   g.Sound.Shot();yield return null;var voice=FindObjectsByType<AudioSource>(FindObjectsSortMode.None).First(x=>x.name.StartsWith("Combat voice")&&x.isPlaying);Check(voice.volume>0&&voice.volume<.4f,"SFX slider did not attenuate");d=MobilePreferences.Current;d.sfx=0;MobilePreferences.Set(d);yield return null;Check(voice.volume==0,"Active sound did not mute");d.sfx=.63f;MobilePreferences.Set(d);
   g.TogglePause();Click("Pause upgrades");Check(g.hud.MobilePage=="upgrades"&&GameObject.Find("Run upgrades").GetComponent<Text>().text.Length>0,"Run upgrade overview missing");Click("Upgrades back");Click("Pause settings");Click("Joystick 0");Click("Button size 0");Click("Settings back");Click("Mobile resume");Check(!input.Floating,"Fixed joystick did not restore");left.position=RectTransformUtility.WorldToScreenPoint(null,input.transform.position);input.OnPointerDown(left);left.position+=Vector2.right*40;input.OnDrag(left);Check(SurvivalInput.Move.x>.1f,"Fixed joystick cannot move");input.OnPointerUp(left);Check(SurvivalInput.Move==Vector2.zero,"Fixed stick did not release");
   g.TogglePause();Click("Pause home");Check(GameObject.Find("Continue current run")&&g.hud.MobilePage=="home","Current run missing on home");CheckPage();yield return Photo("mobile-home-continue.png");shotsBefore=g.ShotsFired;Click("Start new run");Check(g.hud.MobilePage=="confirm","New run silently discards progress");Click("Keep current run");Click("Continue current run");Check(!g.Paused&&g.ShotsFired==shotsBefore,"Continue reset or advanced paused run");
   g.PlayerHealth.Kill();Click("Death home");Check(!GameObject.Find("Continue current run"),"Dead run can continue");Click("Start new run");yield return new WaitForSecondsRealtime(.6f);g=SurvivalGame.Instance;Check(g&&!g.Dead&&g.RunStarted&&!g.Paused&&MobilePreferences.Current.buttons==0&&MobilePreferences.Current.joystick==0&&g.config.shotgunMagazineSize==60,"Restart/settings persistence failed");
   g.TogglePause();Click("Pause settings");Click("Reset mobile settings");d=MobilePreferences.Current;Check(d.music==1&&d.sfx==1&&d.shake==1&&d.buttons==1&&d.joystick==0&&!d.reducedFlash,"Reset defaults failed");
   MobilePreferences.Set(original);MobilePreferences.Flush();File.WriteAllText(Path.Combine(output,"mobile-ux-pass.json"),"{\"passed\":true,\"coldMenuStopsCombat\":true,\"preferencesPersist\":true,\"safeAreaAndSmallLandscape\":true,\"fixedAndFloatingJoystick\":true,\"independentTouchPointers\":true,\"pauseClearsGestures\":true,\"liveSfxVolume\":true,\"firstRunHelp\":true,\"continueAndNewRunGuard\":true,\"restartKeepsPreferences\":true,\"restoreDefaults\":true,\"comfortReducesBloomAndDisablesShake\":true,\"combatValuesUnchanged\":true}");Debug.Log("MOBILE_UX_PASS");Application.Quit(0);
  }
 }
}
