using UnityEngine;
namespace DeadDistrict {
 public sealed class PackEffects : MonoBehaviour {
  sealed class Slot {public GameObject root;public ParticleSystem[] systems;public ParticleSystem.MinMaxGradient[] colors;public float until;public Vector3 from,to,baseScale;public float began,flight;public LineRenderer core,glow,shock;}
  sealed class Stain {public GameObject root;public Renderer renderer;public MaterialPropertyBlock block=new MaterialPropertyBlock();public float until,began;}
  Stain[] stains;int stainIndex;Material stainMaterial;
  public int StainsPlayed {get;private set;}
  Slot[] impacts,enemyImpacts,deaths,explosions,bullets,launcherExplosions;int launcherBlastIndex;int hitIndex,enemyHitIndex,deathIndex,blastIndex,bulletIndex;
  public int ImpactsPlayed {get;private set;}
  public int EnemyImpactsPlayed {get;private set;}
  public int ExplosionsPlayed {get;private set;}
  public int DeathsPlayed {get;private set;}
  public void Initialize(PackVisuals pack){CreateStains();impacts=Pool(pack.impact,16);enemyImpacts=Pool(pack.enemyImpact,16);deaths=Pool(pack.death,12);explosions=Pool(pack.explosion,3);launcherExplosions=Pool(pack.launcherExplosion,4);foreach(var s in launcherExplosions)s.shock=BlockVisuals.Ring("Launcher ground shock",s.root.transform,1,Color.white,Resources.Load<Material>("DeadDistrict/BulletGlow"));bullets=Pool(pack.bullet,24);foreach(var s in bullets){s.core=Ribbon(s.root,"Bullet core",.065f,new Color(4,2.4f,.75f,1));s.glow=Ribbon(s.root,"Bullet halo",.22f,new Color(2.2f,.85f,.2f,.5f));}}
  void CreateStains(){
   stainMaterial=new Material(Resources.Load<Material>("DeadDistrict/BulletGlow"));stainMaterial.SetFloat("_Blend",0);stainMaterial.SetFloat("_DstBlend",(float)UnityEngine.Rendering.BlendMode.OneMinusSrcAlpha);stainMaterial.SetColor("_BaseColor",Color.white);
   stains=new Stain[24];for(int i=0;i<stains.Length;i++){var o=GameObject.CreatePrimitive(PrimitiveType.Quad);o.name="Pooled infected splash "+i;o.transform.SetParent(transform,false);o.GetComponent<Collider>().enabled=false;Destroy(o.GetComponent<Collider>());var r=o.GetComponent<Renderer>();r.sharedMaterial=stainMaterial;r.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;r.receiveShadows=false;o.SetActive(false);stains[i]=new Stain{root=o,renderer=r};}
  }
  void StainAt(Vector3 position,float size){var s=stains[stainIndex++%stains.Length];StainsPlayed++;s.root.transform.SetPositionAndRotation(new Vector3(position.x,Physics.Raycast(position+Vector3.up*.1f,Vector3.down,out var ground,3,1<<8)?ground.point.y+.025f:.025f,position.z),Quaternion.Euler(90,0,Random.Range(0,360)));s.root.transform.localScale=new Vector3(size,size*.7f,1);s.began=Time.time;s.until=Time.time+4;s.root.SetActive(true);}
  void OnDestroy(){if(stainMaterial)Destroy(stainMaterial);}
  Slot[] Pool(GameObject prefab,int count){var a=new Slot[count];for(int i=0;i<count;i++){var g=Instantiate(prefab,transform);var ps=g.GetComponentsInChildren<ParticleSystem>(true);foreach(var p in ps)p.Stop(false,ParticleSystemStopBehavior.StopEmittingAndClear);g.SetActive(false);a[i]=new Slot{root=g,systems=ps,colors=System.Array.ConvertAll(ps,p=>p.main.startColor),baseScale=g.transform.localScale};}return a;}
  void Play(Slot slot,Vector3 pos,Quaternion rot,float lifetime,float scale){slot.root.SetActive(true);slot.root.transform.SetPositionAndRotation(pos,rot);slot.root.transform.localScale=slot.baseScale*scale;foreach(var p in slot.systems){p.Stop(false,ParticleSystemStopBehavior.StopEmittingAndClear);p.Play(false);}slot.until=Time.time+lifetime;}
  LineRenderer Ribbon(GameObject parent,string name,float width,Color color){var g=new GameObject(name);g.transform.SetParent(parent.transform,false);var l=g.AddComponent<LineRenderer>();l.sharedMaterial=Resources.Load<Material>("DeadDistrict/BulletGlow");l.useWorldSpace=true;l.positionCount=2;l.widthMultiplier=width;l.widthCurve=AnimationCurve.Linear(0,.08f,1,1);l.startColor=new Color(color.r,color.g,color.b,0);l.endColor=color;l.numCapVertices=3;l.shadowCastingMode=UnityEngine.Rendering.ShadowCastingMode.Off;l.receiveShadows=false;return l;}
  void SetStrength(Slot slot,float strength){for(int i=0;i<slot.systems.Length;i++){var main=slot.systems[i].main;main.startColor=strength<1?new ParticleSystem.MinMaxGradient(slot.colors[i].color*strength):slot.colors[i];}}
  public void Impact(Vector3 pos,Vector3 normal){ImpactsPlayed++;Play(impacts[hitIndex++%impacts.Length],pos,Quaternion.LookRotation(normal.sqrMagnitude>.01f?normal:Vector3.up),1.1f,.65f);}
  public void EnemyImpact(Vector3 pos,Vector3 direction,float scale=1){ImpactsPlayed++;EnemyImpactsPlayed++;var outward=direction+Vector3.up*.35f;var slot=enemyImpacts[enemyHitIndex++%enemyImpacts.Length];SetStrength(slot,scale<.5f?.35f:1);Play(slot,pos,Quaternion.LookRotation(outward),1.2f,scale);StainAt(pos,.85f*scale);}
  public void Death(Vector3 pos,float scale=1){DeathsPlayed++;var slot=deaths[deathIndex++%deaths.Length];SetStrength(slot,scale<1?.3f:1);Play(slot,pos+Vector3.up*.8f,Quaternion.LookRotation(Vector3.up),1.8f,scale);StainAt(pos,2.6f*scale);}
  public void Explosion(Vector3 pos){ExplosionsPlayed++;Play(explosions[blastIndex++%explosions.Length],pos+Vector3.up*.1f,Quaternion.identity,3.5f,1.0f);}
  public int ActiveLauncherExplosions {get {int n=0;foreach(var s in launcherExplosions)if(s.root.activeSelf)n++;return n;}}
  public void LauncherExplosion(Vector3 pos){ExplosionsPlayed++;var s=launcherExplosions[launcherBlastIndex++%launcherExplosions.Length];for(int i=0;i<s.systems.Length;i++){var main=s.systems[i].main;var original=s.colors[i];main.startColor=MobilePreferences.Current.reducedFlash?new ParticleSystem.MinMaxGradient(original.color*.42f):original;}Play(s,pos,Quaternion.identity,1.85f,1);s.began=Time.time;float groundY=Physics.Raycast(pos+Vector3.up*.1f,Vector3.down,out var hit,4,(1<<0)|(1<<8))?hit.point.y:0;s.shock.transform.localPosition=new Vector3(0,groundY-pos.y+.03f,0);s.shock.transform.localScale=Vector3.one*.12f;s.shock.widthMultiplier=.04f;s.shock.startColor=s.shock.endColor=Color.clear; }
  Color Comfortable(Color color){if(!MobilePreferences.Current.reducedFlash)return color;return new Color(color.r*.42f,color.g*.42f,color.b*.42f,color.a);}
  public void Bullet(Vector3 from,Vector3 to,bool shotgun=false){var s=bullets[bulletIndex++%bullets.Length];s.from=from;s.to=to;s.began=Time.time;s.flight=Mathf.Clamp(Vector3.Distance(from,to)/95,.09f,.18f);Play(s,from,Quaternion.LookRotation(to-from),s.flight+.045f,1);s.core.SetPosition(0,from);s.core.SetPosition(1,from);s.glow.SetPosition(0,from);s.glow.SetPosition(1,from);s.core.startColor=new Color(1,1,1,0);s.core.endColor=Comfortable(shotgun?new Color(4,3.3f,1.8f):new Color(4,2.4f,.75f));s.glow.endColor=Comfortable(shotgun?new Color(3,1.7f,.3f,.65f):new Color(2.2f,.85f,.2f,.5f));}
  void Update(){if(stains!=null)foreach(var s in stains)if(s.root.activeSelf){if(Time.time>s.until){s.root.SetActive(false);continue;}float alpha=Mathf.Clamp01((s.until-Time.time)/1.3f)*.72f;s.block.SetColor("_BaseColor",new Color(.12f,.3f,.025f,alpha));s.renderer.SetPropertyBlock(s.block);}
   Tick(impacts);Tick(enemyImpacts);Tick(deaths);Tick(explosions);Tick(launcherExplosions);foreach(var s in launcherExplosions)if(s.root.activeSelf){float t=Mathf.Clamp01((Time.time-s.began)/.3f);s.shock.transform.localScale=Vector3.one*Mathf.Lerp(.12f,3.2f,t);s.shock.startColor=s.shock.endColor=new Color(1.5f,.72f,.15f,(1-t)*(MobilePreferences.Current.reducedFlash?.22f:.55f));}Tick(bullets);if(bullets!=null)foreach(var s in bullets)if(s.root.activeSelf){
   float t=Mathf.Clamp01((Time.time-s.began)/s.flight);Vector3 head=Vector3.Lerp(s.from,s.to,t),tail=Vector3.Lerp(s.from,s.to,Mathf.Max(0,t-3.2f/Mathf.Max(.1f,Vector3.Distance(s.from,s.to))));
   s.root.transform.position=head;s.core.SetPosition(0,tail);s.core.SetPosition(1,head);s.glow.SetPosition(0,tail);s.glow.SetPosition(1,head);
   float fade=1-Mathf.Clamp01((Time.time-s.began-s.flight)/.045f);s.core.widthMultiplier=.065f*fade;s.glow.widthMultiplier=.22f*fade;
  }}
  void Tick(Slot[] a){if(a==null)return;foreach(var s in a)if(s.root.activeSelf&&Time.time>s.until)s.root.SetActive(false);}
 }
}
