using System;
using System.Collections;
using System.IO;
using System.Linq;
using UnityEngine;
namespace DeadDistrict {
 public sealed class PresentationPolishValidation:MonoBehaviour {
  string output;SurvivalGame g;LoftActor actor;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var a=RuntimeLaunch.Arguments();if(Array.IndexOf(a,"-presentation-polish-capture")<0)return;var v=new GameObject("Opt-in presentation capture").AddComponent<PresentationPolishValidation>();int n=Array.IndexOf(a,"-validation-output");v.output=n>=0?a[n+1]:Application.persistentDataPath;Directory.CreateDirectory(v.output);if(SurvivalGame.Instance)SurvivalGame.Instance.CombatValidation=true;v.StartCoroutine(v.Run());}
  IEnumerator Photo(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Application.isMobilePlatform?name:Path.Combine(output,name));yield return new WaitForSecondsRealtime(.25f);}
  IEnumerator Run(){var core=Core();while(true){object item=null;bool more=false;string fail=null;try{more=core.MoveNext();if(more)item=core.Current;}catch(Exception e){fail=e.ToString();}if(fail!=null){File.WriteAllText(Path.Combine(output,"presentation-failure.txt"),fail);Debug.LogError("PRESENTATION_POLISH_FAIL "+fail);Application.Quit(1);yield break;}if(!more)yield break;yield return item;}}
  void Check(bool ok,string message){if(!ok)throw new Exception(message);}
  void CheckHands(){var gun=actor.transform.Find(g.CurrentWeapon==WeaponKind.Rifle?"Weapon":"Shotgun weapon");Check(Vector3.Distance(actor.Bone((int)HumanBodyBones.RightHand).position,gun.TransformPoint(new Vector3(0,.05f,-.16f)))<.035f,"Right hand missed grip");Check(Vector3.Distance(actor.Bone((int)HumanBodyBones.LeftHand).position,gun.TransformPoint(new Vector3(-.02f,.12f,.10f)))<.035f,"Left hand missed fore-end");Check(Vector3.Dot(actor.Muzzle.forward,actor.transform.forward)>.98f,"Muzzle direction mismatch");}
  IEnumerator Core(){yield return null;yield return null;g=SurvivalGame.Instance;g.Growth.Enabled=false;g.CombatValidation=true;g.config.aimRange=0;g.Supplies.Clear();g.WeaponCrates.Clear();actor=GameObject.Find("Survivor").GetComponentInChildren<LoftActor>();yield return new WaitForSeconds(.3f);
   var lines=new System.Collections.Generic.List<string>();foreach(var bone in new[]{HumanBodyBones.Head,HumanBodyBones.Chest,HumanBodyBones.RightUpperArm,HumanBodyBones.RightLowerArm,HumanBodyBones.RightHand,HumanBodyBones.LeftUpperArm,HumanBodyBones.LeftLowerArm,HumanBodyBones.LeftHand}){var t=actor.Bone((int)bone);lines.Add(bone+" "+(t?actor.transform.InverseTransformPoint(t.position).ToString("F4"):"unmapped"));}
   var gun=actor.transform.Find("Weapon");lines.Add("gun="+gun.localPosition.ToString("F4"));foreach(var renderer in gun.GetComponentsInChildren<MeshRenderer>()){lines.Add(renderer.name+" center "+actor.transform.InverseTransformPoint(renderer.bounds.center).ToString("F4")+" size "+renderer.bounds.size.ToString("F4"));}File.WriteAllLines(Path.Combine(output,"pose-diagnostics.txt"),lines);
   foreach(string button in new[]{"Grenade","Dodge","Reload","Switch weapon"})Check(GameObject.Find(button).GetComponent<RectTransform>().sizeDelta==Vector2.one*112,"Action diameter mismatch");CheckHands();yield return Photo("gameplay-controls.png");g.enabled=false;var cam=Camera.main;cam.orthographicSize=2.1f;cam.transform.position=g.PlayerPosition+new Vector3(-3,2.7f,4);cam.transform.LookAt(g.PlayerPosition+Vector3.up*.9f);yield return Photo("rifle-close.png");
   g.CollectShotgun();yield return new WaitForSeconds(.15f);yield return Photo("shotgun-close.png");cam.transform.position=g.PlayerPosition+new Vector3(4,2.6f,0);cam.transform.LookAt(g.PlayerPosition+Vector3.up*.9f);yield return Photo("shotgun-side.png");CheckHands();actor.Move(5);actor.transform.rotation=Quaternion.Euler(0,73,0);yield return new WaitForSeconds(.3f);yield return new WaitForEndOfFrame();CheckHands();actor.SetRolling(true);yield return new WaitForEndOfFrame();Check(!actor.transform.Find("Weapon").gameObject.activeSelf&&!actor.transform.Find("Shotgun weapon").gameObject.activeSelf,"Rolling weapon visibility");actor.SetRolling(false);yield return new WaitForSeconds(.3f);yield return new WaitForEndOfFrame();CheckHands();Check(g.SwitchWeapon(),"Switch after roll");yield return new WaitForEndOfFrame();CheckHands();
   File.WriteAllText(Path.Combine(output,"presentation-pass.json"),"{\"passed\":true,\"equalButtonDiameters\":true,\"handsFollowBothWeaponsWhileWalkingAndTurning\":true,\"rollAndSwitchRestorePose\":true}");Debug.Log("PRESENTATION_POLISH_PASS");Application.Quit(0);
  }
 }
}
