using System;
using System.Collections;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEngine.SceneManagement;
namespace DeadDistrict {
 public sealed class ProgressionFeedbackValidation:MonoBehaviour {
  static bool started;string output;SurvivalGame g;MobilePreferences.Data preferences;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var a=RuntimeLaunch.Arguments();if(started||!a.Contains("-progression-feedback-smoke"))return;started=true;ChapterProgress.IsolatedValidation=true;SurvivalGame.Instance.CombatValidation=true;SceneManager.sceneLoaded+=(s,m)=>{if(SurvivalGame.Instance)SurvivalGame.Instance.CombatValidation=true;};var v=new GameObject("Progression feedback validation").AddComponent<ProgressionFeedbackValidation>();DontDestroyOnLoad(v.gameObject);int n=Array.IndexOf(a,"-validation-output");v.output=a[n+1];Directory.CreateDirectory(v.output);v.StartCoroutine(v.Run());}
  void Check(bool ok,string why){if(!ok)throw new Exception(why);}
  IEnumerator Run(){preferences=MobilePreferences.Current;var e=Core();while(true){bool more=false;object item=null;string fail=null;try{more=e.MoveNext();if(more)item=e.Current;}catch(Exception x){fail=x.ToString();}if(fail!=null){MobilePreferences.Set(preferences);Time.timeScale=1;File.WriteAllText(Path.Combine(output,"progression-feedback-failure.txt"),fail);Debug.LogError(fail);Application.Quit(1);yield break;}if(!more)yield break;yield return item;}}
  IEnumerator Photo(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(output,name+".png"));yield return new WaitForSecondsRealtime(.15f);}
  void Setup(){g=SurvivalGame.Instance;g.CombatValidation=true;g.enabled=false;foreach(var e in g.Enemies)if(e.Alive)e.Health.Kill();g.Supplies.Clear();g.WeaponCrates.Clear();g.ResumeRun();}
  IEnumerator Core(){yield return null;yield return null;Setup();
   Check(!g.CollectShotgun()&&!g.CollectLauncher()&&!g.SwitchWeapon()&&!g.WeaponCrates.TrySpawn(Vector3.zero)&&g.CurrentWeapon==WeaponKind.Rifle,"First chapter weapon gate failed");
   g.Growth.Enabled=true;while(g.Growth.Points==0)g.Growth.Award(EnemyKind.Normal);Check(!g.Paused&&!g.Growth.Choosing,"XP interrupted combat");yield return new WaitForSeconds(.18f);Check(GameObject.Find("Pooled GrowthEarn").GetComponent<PackBurst>().ParticleCount>0,"Earn prefab emitted nothing");yield return Photo("01-earned-point");
   Check(g.Growth.TryOpen(),"Manual upgrade rejected");yield return new WaitForSecondsRealtime(.4f);Check(g.Growth.Choose(0,g.Growth.OfferId)&&!g.Paused&&g.PlayerHealth.GrowthProtected,"Upgrade return/protection changed");yield return new WaitForSeconds(.18f);Check(GameObject.Find("Pooled GrowthApply").GetComponent<PackBurst>().ParticleCount>0,"Upgrade prefab emitted nothing");yield return Photo("02-upgrade-applied");yield return new WaitForSeconds(1.15f);Check(!g.PlayerHealth.GrowthProtected,"Growth shield outlived gameplay protection");
   int count=g.Feedback.PickupsPlayed;g.PlayerHealth.SetHealth(30);Check(g.ApplySupply(SupplyKind.Medkit),"Medical fixture");yield return new WaitForSeconds(.18f);Check(g.Feedback.PickupsPlayed==count+1&&GameObject.Find("Pooled HealPickup").GetComponent<PackBurst>().ParticleCount>0,"Pickup feedback missing");yield return Photo("03-heal-pickup");g.ApplySupply(SupplyKind.Armor);yield return new WaitForSeconds(.15f);yield return Photo("04-supply-pickup");
   ChapterProgress.Complete(g.Chapter.id,300,286);var old=g;Check(g.BeginChapter(1),"Camp load");while(ReferenceEquals(old,SurvivalGame.Instance))yield return null;yield return null;Setup();
   Check(!g.CollectLauncher()&&g.CollectShotgun()&&g.CurrentWeapon==WeaponKind.Shotgun&&g.Ammo==60,"Camp weapon gate");Check(g.SwitchWeapon()&&g.CurrentWeapon==WeaponKind.Rifle&&g.SwitchWeapon()&&g.CurrentWeapon==WeaponKind.Shotgun,"Camp switch includes locked gun");
   foreach(var site in g.Chapter.weaponSites)g.WeaponCrates.TrySpawn(site);var hints=new LootHint[5];int n=g.WeaponCrates.AppendHints(hints,0);Check(n==3&&hints.Take(n).All(h=>h.weaponKind==WeaponKind.Shotgun),"Camp spawns launcher crates");Check(g.Chapter.eliteCooldown==1.25f&&g.Chapter.eliteRecovery==1.1f&&g.Chapter.eliteWindup==.7f,"Camp pace wrong");yield return new WaitForSeconds(.15f);yield return Photo("05-camp-shotgun");
   var boss=g.Enemies[0];boss.Spawn(new Vector3(0,0,7),0,EnemyKind.Brute,true);boss.Health.SetHealth(g.Chapter.eliteHealth*.4f);var charge=boss.ChargeAttack;float t=Time.time+2;charge.Tick(t);Check(charge.Phase==EliteCharge.Stage.Windup,"Charge windup");charge.Tick(t+.65f);Check(charge.Charges==0,"Charge too early");charge.Tick(t+.71f);var finish=typeof(EliteCharge).GetMethod("Finish",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance);finish.Invoke(charge,new object[]{t+.8f,false});charge.Tick(t+1.41f);Check(charge.Phase==EliteCharge.Stage.Hunt,"Low-health followup recovery missing");boss.Agent.Warp(new Vector3(0,0,7));charge.Tick(t+1.68f);Check(charge.Phase==EliteCharge.Stage.Windup&&charge.Charges==1,"Followup must start a fresh telegraph");charge.Cancel();boss.Retire();
   ChapterProgress.Complete(g.Chapter.id,300,2040);old=g;Check(g.BeginChapter(2),"Freight load");while(ReferenceEquals(old,SurvivalGame.Instance))yield return null;yield return null;Setup();
   Check(g.CollectShotgun()&&g.CollectLauncher()&&g.CurrentWeapon==WeaponKind.Launcher,"Third chapter guns unavailable");Check(g.SwitchWeapon()&&g.CurrentWeapon==WeaponKind.Rifle&&g.SwitchWeapon()&&g.CurrentWeapon==WeaponKind.Shotgun&&g.SwitchWeapon()&&g.CurrentWeapon==WeaponKind.Launcher,"Three-gun cycle wrong");
   foreach(var site in g.Chapter.weaponSites)g.WeaponCrates.TrySpawn(site);n=g.WeaponCrates.AppendHints(hints,0);Check(n==3&&hints.Take(n).Count(h=>h.weaponKind==WeaponKind.Launcher)==1,"Third launcher crate missing");g.WeaponCrates.Clear();
   boss=g.Enemies[0];boss.Spawn(new Vector3(0,0,7),0,EnemyKind.Brute,true);var acid=boss.AcidAttack;t=Time.time+2;acid.Tick(t);Check(acid.TargetCount>=5&&acid.TargetCount<=7,"Wider acid volley too sparse: "+acid.TargetCount);Check(g.Chapter.acidRadius==2.6f&&g.Chapter.eliteCooldown==.75f,"Acid tuning missing");var targets=Enumerable.Range(0,acid.TargetCount).Select(acid.TargetAt).ToArray();yield return Photo("06-acid-warning");acid.Tick(t+.71f);yield return new WaitForSeconds(.06f);acid.Tick(t+.80f);yield return Photo("07-acid-flight");acid.Tick(t+.95f);yield return new WaitForSeconds(.2f);Check(acid.ActivePools==targets.Length&&targets.SequenceEqual(Enumerable.Range(0,acid.TargetCount).Select(acid.TargetAt)),"Targets moved / pool budget wrong");Check(FindObjectsByType<PackBurst>(FindObjectsSortMode.None).Any(b=>b.name=="Pooled AcidSplash"&&b.ParticleCount>0),"No purchased acid impact");yield return Photo("08-acid-impact");yield return new WaitForSeconds(.65f);yield return Photo("09-acid-residue");
   var settings=preferences;settings.reducedFlash=true;MobilePreferences.Set(settings);g.Feedback.Apply(g.PlayerPosition);yield return new WaitForSeconds(.15f);yield return Photo("10-reduced-flash");acid.Cancel();Check(acid.ActivePools==0&&!FindObjectsByType<PackBurst>(FindObjectsSortMode.None).Any(b=>b.name.StartsWith("Pooled Acid")),"Cancelled acid leaks particles");MobilePreferences.Set(preferences);
   foreach(var ps in Resources.FindObjectsOfTypeAll<ParticleSystem>().Where(p=>p.GetComponentInParent<PackBurst>())){Check(ps.main.maxParticles<=26,"Unbounded particle preset");var r=ps.GetComponent<ParticleSystemRenderer>();Check(r.sharedMaterials.All(m=>m&&m.shader.isSupported&&m.shader.name.StartsWith("Universal Render Pipeline")),"Unsupported particle material");}
   old=g;Check(g.BeginChapter(0),"Return to first chapter");while(ReferenceEquals(old,SurvivalGame.Instance))yield return null;yield return null;Setup();Check(!g.ShotgunUnlocked&&!g.LauncherUnlocked&&!g.CollectLauncher()&&!g.CollectShotgun()&&!g.SwitchWeapon(),"Weapon ownership leaked backwards");
   File.WriteAllText(Path.Combine(output,"progression-feedback-pass.json"),"{\"passed\":true,\"chapterWeaponGatesAndLoot\":true,\"returnResetsWeapons\":true,\"manualUpgradeProtection\":true,\"pickupAndUpgradeParticles\":true,\"acidTargets\":"+targets.Length+",\"acidTelegraphAndCleanup\":true,\"chargeFollowupTelegraphed\":true,\"boundedURPParticles\":true}");Debug.Log("PROGRESSION_FEEDBACK_PASS");Application.Quit(0);
  }
 }
}
