using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEngine.AI;
namespace DeadDistrict {
 public sealed class SmokeHoundValidation:MonoBehaviour {
  string output;SurvivalGame g;float dogDistance;MobilePreferences.Data original;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var a=RuntimeLaunch.Arguments();if(Array.IndexOf(a,"-smoke-hound-smoke")<0)return;var v=new GameObject("Opt-in smoke and hound validation").AddComponent<SmokeHoundValidation>();int n=Array.IndexOf(a,"-validation-output");v.output=n>=0?a[n+1]:Application.persistentDataPath;Directory.CreateDirectory(v.output);SurvivalGame.Instance.CombatValidation=true;v.StartCoroutine(v.Run());}
  void Check(bool ok,string why){if(!ok)throw new Exception(why);}
  IEnumerator Photo(string name){yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(output,name+".png"));yield return new WaitForSecondsRealtime(.16f);}
  IEnumerator Run(){original=MobilePreferences.Current;var stack=new Stack<IEnumerator>();stack.Push(Core());while(stack.Count>0){object item=null;bool more=false;string fail=null;try{more=stack.Peek().MoveNext();if(more)item=stack.Peek().Current;}catch(Exception e){fail=e.ToString();}if(fail!=null){Time.timeScale=1;MobilePreferences.Set(original);File.WriteAllText(Path.Combine(output,"smoke-hound-failure.txt"),fail);Debug.LogError("SMOKE_HOUND_FAIL "+fail);Application.Quit(1);yield break;}if(!more){stack.Pop();continue;}if(item is IEnumerator nested)stack.Push(nested);else yield return item;}}
  IEnumerator Core(){yield return null;yield return null;g=SurvivalGame.Instance;g.enabled=false;g.Growth.Enabled=false;g.Supplies.Clear();g.WeaponCrates.Clear();var pref=original;pref.reducedFlash=false;MobilePreferences.Set(pref);var forward=Camera.main.transform.forward;forward.y=0;forward.Normalize();var right=Camera.main.transform.right;right.y=0;right.Normalize();
   var from=g.PlayerPosition+forward*2+Vector3.up*1.2f;Check(g.Launcher.Launch(from,from+forward*12,220,3.2f),"Smoke flight launch failed");yield return new WaitForSeconds(.13f);Check(g.Launcher.ActiveCount==1&&g.Launcher.SmokeParticles>3,"Moving shell has no smoke trail");
   var systems=g.Launcher.GetComponentsInChildren<ParticleSystem>().Where(p=>p.name.StartsWith("Pooled launcher smoke")).ToArray();Check(systems.Length==6&&systems.All(p=>p.main.maxParticles==48&&p.main.simulationSpace==ParticleSystemSimulationSpace.World),"Unbounded smoke pool or smoke follows projectile");
   var ps=systems.First(p=>p.particleCount>0);var particles=new ParticleSystem.Particle[48];int n=ps.GetParticles(particles);float spread=0;for(int i=1;i<n;i++)spread=Mathf.Max(spread,Vector3.Distance(particles[0].position,particles[i].position));Check(spread>.7f,"Smoke is a point cloud instead of a trail");
   g.PauseForShell();yield return null;float age=ps.time;var shellPosition=g.Launcher.FirstActivePosition;yield return Photo("01-smoke-trail");Check(Mathf.Abs(ps.time-age)<.001f&&g.Launcher.FirstActivePosition==shellPosition,"Pause advances smoke or shell");g.ResumeRun();float deadline=Time.time+1;while(g.Launcher.ActiveCount>0&&Time.time<deadline)yield return null;Check(g.Launcher.ActiveCount==0&&g.Launcher.SmokeParticles>0,"Smoke disappears instantly at detonation");yield return new WaitForSeconds(.55f);Check(g.Launcher.SmokeParticles==0,"Smoke trail does not dissipate");
   for(int i=0;i<3;i++){var spot=forward*5+right*(i-1)*.8f;Check(NavMesh.SamplePosition(spot,out var nav,.6f,NavMesh.AllAreas),"Explosion crowd lacks floor");g.Enemies[i].Spawn(nav.position,0);g.Enemies[i].Health.SetHealth(26);}int kills=g.Kills;int detonations=g.Launcher.Detonations;Check(g.Launcher.Launch(from,g.Enemies[1].AimPoint,220,3.2f),"Crowd blast launch failed");deadline=Time.time+1;while(g.Launcher.Detonations==detonations&&Time.time<deadline)yield return null;Check(g.Kills==kills+3,"Blast did not kill crowd");yield return new WaitForSeconds(.07f);g.PauseForShell();yield return Photo("02-crowd-explosion");g.ResumeRun();yield return new WaitForSeconds(.48f);var smoke=g.VisualEffects.GetComponentsInChildren<ParticleSystem>().Where(p=>p.name=="Rolling blast smoke").ToArray();Check(smoke.Any(p=>p.particleCount>0),"Blast smoke tail is missing after the flash");g.PauseForShell();yield return Photo("03-lingering-blast-smoke");g.ResumeRun();yield return new WaitForSeconds(1.5f);Check(g.VisualEffects.ActiveLauncherExplosions==0,"Blast pool not recycled");
   var dog=g.Enemies[5];Check(NavMesh.SamplePosition(forward*8,out var start,.6f,NavMesh.AllAreas),"Hound fixture lacks floor");dog.Spawn(start.position,g.config.enemySpeed,EnemyKind.Runner);Check(dog.Agent.speed>=5.4f,"Hound speed not increased");var actor=dog.GetComponentsInChildren<LoftActor>().First(x=>x.Quadruped);var animator=dog.GetComponentInChildren<Animator>();var began=Time.time;while(Time.time-began<.4f){dog.Tick(Time.time);yield return null;}var runningStart=dog.transform.position;began=Time.time;while(Time.time-began<.5f){dog.Tick(Time.time);yield return null;}dogDistance=Vector3.Distance(runningStart,dog.transform.position);Check(dogDistance>2.35f,"Hound does not actually run faster: distance="+dogDistance);Check(animator.GetCurrentAnimatorClipInfo(0).Any(c=>c.clip.name=="Hound Bound Run"),"Hound still uses walking clip");dog.Agent.isStopped=true;
   var leg=actor.GetComponentsInChildren<Transform>().First(t=>t.name=="Bone.014");Quaternion previous=leg.localRotation;float legAngle=0;var cam=Camera.main;cam.orthographicSize=2;cam.transform.position=dog.transform.position+actor.transform.right*3.5f+Vector3.up*1.65f+actor.transform.forward*.4f;cam.transform.LookAt(dog.transform.position+Vector3.up*.5f);
   for(int frame=0;frame<3;frame++){for(int i=0;i<6;i++){actor.MoveInfected(5.4f,1);yield return null;legAngle=Mathf.Max(legAngle,Quaternion.Angle(previous,leg.localRotation));}yield return Photo("04-hound-run-"+frame);}Check(legAngle>15,"Hound limbs do not show running motion");
   MobilePreferences.Set(original);File.WriteAllText(Path.Combine(output,"smoke-hound-pass.json"),"{\"passed\":true,\"worldSpaceSmokeTrail\":true,\"pauseAndNaturalDissipation\":true,\"crowdBlastSmokeVisibleAfterFlash\":true,\"houndUsesRunClip\":true,\"houndTravelMetresInHalfSecondAfterAcceleration\":"+dogDistance.ToString(System.Globalization.CultureInfo.InvariantCulture)+",\"legRotationDegrees\":"+legAngle.ToString(System.Globalization.CultureInfo.InvariantCulture)+"}");Debug.Log("SMOKE_HOUND_PASS");Application.Quit(0);
  }
 }
}
