using System;
using System.Collections;
using System.IO;
using UnityEngine;
namespace DeadDistrict {
 public sealed class SupplyValidation : MonoBehaviour {
  string output;bool capture;static bool started;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]
  static void Boot(){var args=Environment.GetCommandLineArgs();bool capture=Array.IndexOf(args,"-supply-capture")>=0;if(started||(!capture&&Array.IndexOf(args,"-supply-smoke")<0))return;started=true;var v=new GameObject("Opt-in supply validation").AddComponent<SupplyValidation>();DontDestroyOnLoad(v.gameObject);v.capture=capture;int n=Array.IndexOf(args,"-validation-output");v.output=n>=0?args[n+1]:Application.persistentDataPath;Directory.CreateDirectory(v.output);if(SurvivalGame.Instance)SurvivalGame.Instance.CombatValidation=true;v.StartCoroutine(v.Run());}
  void Require(bool result,string reason){if(!result)throw new Exception(reason);}
  IEnumerator Run(){var routine=Core();while(true){object current=null;bool moved=false;string failure=null;try{moved=routine.MoveNext();if(moved)current=routine.Current;}catch(Exception e){failure=e.ToString();}if(failure!=null){Time.timeScale=1;File.WriteAllText(Path.Combine(output,"supply-failure.txt"),failure);Debug.LogError("SUPPLY_VALIDATION_FAIL "+failure);Application.Quit(1);yield break;}if(!moved)yield break;yield return current;}}
  IEnumerator Core(){
   yield return null;yield return null;var g=SurvivalGame.Instance;g.CombatValidation=true;var s=g.Supplies;var hp=g.PlayerHealth;Vector3 pos=g.PlayerPosition;
   if(capture){
    Require(s.TrySpawn(SupplyKind.Medkit,pos+new Vector3(3,0,3)),"medkit visual spawn");Require(s.TrySpawn(SupplyKind.Ammo,pos+new Vector3(-3,0,5)),"ammo visual spawn");Require(s.TrySpawn(SupplyKind.Grenade,pos+new Vector3(6,0,-3)),"grenade visual spawn");Require(s.TrySpawn(SupplyKind.Armor,pos+new Vector3(-5,0,-4)),"armor visual spawn");
    yield return new WaitForSeconds(.15f);ScreenCapture.CaptureScreenshot(Path.Combine(output,"supplies.png"));yield return new WaitForSeconds(.3f);Require(File.Exists(Path.Combine(output,"supplies.png")),"supply screenshot missing");s.Clear();
   }
   Require(s.TrySpawn(SupplyKind.Medkit,pos),"full-health supply spawn");yield return new WaitForSeconds(.15f);Require(s.ActiveCount==1&&hp.CurrentHealth==100,"full health wastes pickup");hp.SetHealth(50);yield return new WaitForSeconds(.15f);Require(s.ActiveCount==0&&hp.CurrentHealth==80,"automatic heal pickup");Require(s.TrySpawn(SupplyKind.Medkit,pos),"capped heal spawn");yield return new WaitForSeconds(.15f);Require(hp.CurrentHealth==100&&s.ActiveCount==0,"heal cap");
   Require(s.TrySpawn(SupplyKind.Ammo,pos),"full ammo spawn");yield return new WaitForSeconds(.15f);Require(s.ActiveCount==1&&g.Ammo==g.config.magazineSize,"full ammo wastes pickup");s.Clear();
   Require(s.TrySpawn(SupplyKind.Grenade,pos),"full grenades spawn");yield return new WaitForSeconds(.15f);Require(s.ActiveCount==1&&g.Grenades==2,"full grenades wastes pickup");g.ThrowGrenade();yield return new WaitForSeconds(.15f);Require(s.ActiveCount==0&&g.Grenades==2,"grenade automatic pickup");
   hp.SetHealth(50);Require(s.TrySpawn(SupplyKind.Medkit,pos+Vector3.right*1.2f),"blocked pickup spawn");var wall=GameObject.CreatePrimitive(PrimitiveType.Cube);wall.layer=8;wall.transform.position=pos+Vector3.right*.6f+Vector3.up;wall.transform.localScale=new Vector3(.12f,2,2);yield return new WaitForSeconds(.2f);Require(s.ActiveCount==1&&hp.CurrentHealth==50,"wall allowed pickup");Destroy(wall);yield return new WaitForSeconds(.15f);Require(s.ActiveCount==0&&hp.CurrentHealth==80,"unblocked pickup does not resume");
   Require(s.TrySpawn(SupplyKind.Armor,pos),"armor pickup spawn");yield return new WaitForSeconds(.15f);Require(hp.Armor==25,"armor auto pickup");float remaining=hp.ArmorSeconds;g.TogglePause();yield return new WaitForSecondsRealtime(.3f);Require(Mathf.Abs(hp.ArmorSeconds-remaining)<.03f,"pause consumed armor time");Require(!g.ApplySupply(SupplyKind.Medkit),"paused item consumption");g.TogglePause();
   hp.SetHealth(100);hp.Damage(8,g.gameObject,0,.22f,Vector3.forward);Require(hp.Armor==17&&hp.CurrentHealth==100,"armor first absorption");hp.Damage(8,g.gameObject,0,.22f,Vector3.forward);Require(hp.Armor==17&&hp.CurrentHealth==100,"invulnerability drains armor");yield return new WaitForSeconds(.3f);hp.Damage(20,g.gameObject,0,0,Vector3.forward);Require(hp.Armor==0&&hp.CurrentHealth==97,"armor spillover");
   hp.GrantArmor();hp.Damage(5,g.gameObject,0,0,Vector3.forward);hp.GrantArmor();Require(hp.Armor==25&&hp.ArmorSeconds>11.9f,"armor stacking or refresh");
   if(capture){yield return null;ScreenCapture.CaptureScreenshot(Path.Combine(output,"armor-hud.png"));yield return new WaitForSeconds(.3f);Require(File.Exists(Path.Combine(output,"armor-hud.png")),"armor screenshot missing");}
   Time.timeScale=6;yield return new WaitForSeconds(12.2f);Time.timeScale=1;Require(hp.Armor==0&&hp.CurrentHealth==97,"armor expiration");
   // Exercise the real weapon/reload loop, then verify an ammo pickup cancels its old timer.
   var z=g.Enemies[0];z.Spawn(pos+new Vector3(3,0,3),0);z.Health.SetHealth(10000);float deadline=Time.time+g.config.magazineSize/g.config.roundsPerSecond+2;while(!g.Reloading&&Time.time<deadline)yield return null;Require(g.Reloading&&g.Ammo==0,"actual rifle never entered reload");Require(s.TrySpawn(SupplyKind.Ammo,pos),"reload ammo spawn");yield return new WaitForSeconds(.12f);Require(!g.Reloading&&g.Ammo>=g.config.magazineSize-3,"ammo did not cancel reload");int ammo=g.Ammo;z.Retire();yield return new WaitForSeconds(2);Require(!g.Reloading&&g.Ammo==ammo,"old reload timer overwrote pickup state");
   s.Clear();Require(!s.TrySpawn(SupplyKind.Ammo,new Vector3(999,0,999)),"outside map accepted");var poolPoints=new[]{new Vector3(3,0,3),new Vector3(-3,0,5),new Vector3(6,0,-3),new Vector3(-5,0,-4),new Vector3(0,0,6),new Vector3(0,0,-6)};for(int i=0;i<6;i++)Require(s.TrySpawn((SupplyKind)(i%4),pos+poolPoints[i]),"pool slot spawn "+i);Require(s.ActiveCount==6&&!s.TrySpawn(SupplyKind.Medkit,pos+new Vector3(3,0,7)),"pool cap broken");
   remaining=Time.time;g.TogglePause();yield return new WaitForSecondsRealtime(.3f);Require(s.ActiveCount==6&&Time.time==remaining,"pause expired supplies");g.TogglePause();Time.timeScale=6;yield return new WaitForSeconds(25.2f);Time.timeScale=1;Require(s.ActiveCount==0,"supply expiry cleanup");Require(s.TrySpawn(SupplyKind.Armor,pos),"pool reuse spawn");yield return new WaitForSeconds(.15f);Require(hp.Armor==25,"pool reuse pickup");Require(s.TrySpawn(SupplyKind.Medkit,pos+Vector3.forward*3),"death cleanup fixture");hp.Kill();Require(g.Dead&&s.ActiveCount==0&&hp.Armor==0,"death retained supplies or armor");
   // Inspect reset as soon as the new run initializes, before opening enemies consume ammunition.
   g.Restart();yield return null;g=SurvivalGame.Instance;while(!g||!g.PlayerHealth||!g.Supplies){yield return null;g=SurvivalGame.Instance;}g.TogglePause();Require(g&&!g.Dead&&g.PlayerHealth.CurrentHealth==100&&g.PlayerHealth.Armor==0&&g.Ammo==g.config.magazineSize&&g.Grenades==2&&g.Kills==0&&g.Supplies.ActiveCount==4&&g.PickupMessage=="","restart retained run state");
   File.WriteAllText(Path.Combine(output,"supply-pass.json"),"{\"passed\":true,\"automaticPickup\":true,\"fullStatesPreserveItems\":true,\"healingCap\":true,\"wallBlocksPickup\":true,\"ammoCancelsRealReload\":true,\"armorFirstAndSpillover\":true,\"invulnerabilityPreserved\":true,\"armorRefreshAndExpiry\":true,\"pauseFreezesDurations\":true,\"sixItemPoolCap\":true,\"spawnAndExpiry\":true,\"deathAndRestartReset\":true,\"tutorialItems\":4}");Debug.Log("SUPPLY_VALIDATION_PASS");Application.Quit(0);
  }
 }
}
