using System;
using System.Reflection;
using System.Collections;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEngine.AI;
using UnityEngine.UI;
namespace DeadDistrict {
 public sealed class WorldValidation:MonoBehaviour {
  static bool started;string output;bool capture;SurvivalGame g;
  [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.AfterSceneLoad)]static void Boot(){var a=RuntimeLaunch.Arguments();bool c=Array.IndexOf(a,"-world-capture")>=0;if(started||(!c&&Array.IndexOf(a,"-world-smoke")<0))return;started=true;var v=new GameObject("Opt-in world validation").AddComponent<WorldValidation>();DontDestroyOnLoad(v.gameObject);v.capture=c;int i=Array.IndexOf(a,"-validation-output");v.output=i>=0?a[i+1]:Application.persistentDataPath;Directory.CreateDirectory(v.output);if(SurvivalGame.Instance)SurvivalGame.Instance.CombatValidation=true;v.StartCoroutine(v.Run());}
  void Check(bool ok,string why){if(!ok)throw new Exception(why);}
  IEnumerator Run(){var core=Core();while(true){object current=null;bool more=false;string failure=null;try{more=core.MoveNext();if(more)current=core.Current;}catch(Exception ex){failure=ex.ToString();}if(failure!=null){File.WriteAllText(Path.Combine(output,"world-failure.txt"),failure);Debug.LogError("WORLD_VALIDATION_FAIL "+failure);Application.Quit(1);yield break;}if(!more)yield break;yield return current;}}
  void Move(Vector3 point){var t=g.PlayerHealth.transform;var c=t.GetComponent<CharacterController>();c.enabled=false;t.position=point;c.enabled=true;}
  IEnumerator Photo(string name){if(!capture)yield break;Time.timeScale=0;yield return new WaitForSecondsRealtime(.1f);yield return new WaitForEndOfFrame();ScreenCapture.CaptureScreenshot(Path.Combine(output,name));yield return new WaitForSecondsRealtime(.25f);Time.timeScale=1;}
  bool HasPath(Vector3 from,Vector3 to){var p=new NavMeshPath();return NavMesh.CalculatePath(from,to,NavMesh.AllAreas,p)&&p.status==NavMeshPathStatus.PathComplete;}
  void FireAt(WorldProp prop){typeof(SurvivalGame).GetMethod("FireWeapon",BindingFlags.Instance|BindingFlags.NonPublic).Invoke(g,new object[]{(Vector3?)prop.AimPoint});}
  IEnumerator Core(){yield return null;yield return null;g=SurvivalGame.Instance;g.CombatValidation=true;g.Supplies.Clear();g.WeaponCrates.Clear();
   Check(g.World.Props.Count==16,"World prop count");var box=g.World.Props.First(p=>p.Kind==WorldPropKind.SupplyCrate);Move(box.transform.position+Vector3.back*3);yield return new WaitForSeconds(.7f);Check(g.World.Nearest()==null&&!g.World.Interact(),"Crate still exposes a special interaction");yield return Photo("supply-crate.png");FireAt(box);Check(box.Health==26&&!box.Broken,"First ordinary bullet did not hit crate");FireAt(box);Check(box.Broken,"Second ordinary bullet did not break crate");float deadline;
   yield return new WaitForSeconds(.5f);Check(g.World.SuppliesReleased==1&&g.Supplies.ActiveCount==1,"Crate reward lost");g.PlayerHealth.SetHealth(50);Move(box.transform.position);yield return new WaitForSeconds(.3f);Check(g.PlayerHealth.CurrentHealth==80&&g.Supplies.Collected==1,"Crate medkit pickup");
   var door=g.World.Props.First(p=>p.Kind==WorldPropKind.Door&&p.transform.position.x>0&&Mathf.Abs(p.transform.position.z)<1);var outside=new Vector3(21.9f,0,0);var inside=new Vector3(27,0,0);Move(outside);yield return new WaitForSeconds(.8f);Check(!HasPath(outside,inside),"Closed door did not carve entrance");Check(g.World.Nearest()==door&&g.World.Interact(),"Door context unavailable");yield return new WaitForSeconds(.65f);Check(door.Open&&!door.Moving&&HasPath(outside,inside),"Open door did not restore path");yield return Photo("residence-open.png");Move(door.transform.position);yield return new WaitForSeconds(.2f);Check(!door.Toggle()&&door.Open,"Door closed onto player");Move(outside);yield return new WaitForSeconds(.4f);Check(door.Toggle(),"Door close rejected with clear entrance");yield return new WaitForSeconds(.65f);Check(!door.Open&&!HasPath(outside,inside),"Door close retained navigation route");Check(door.Toggle(),"Door reopen");yield return new WaitForSeconds(.65f);
   // Each entrance and central reward aisle must become reachable when opened.
   foreach(var d in g.World.Props.Where(p=>p.Kind==WorldPropKind.Door)){if(!d.Open)Check(d.Toggle(),"Door open fixture");}yield return new WaitForSeconds(.7f);
   foreach(var d in g.World.Props.Where(p=>p.Kind==WorldPropKind.Door)){int s=d.transform.position.x<0?-1:1;Check(HasPath(new Vector3(s*21,0,d.transform.position.z),new Vector3(s*27,0,d.transform.position.z)),"Room inaccessible "+d.transform.position);}
   foreach(int z in new[]{0,24,-24}){Move(new Vector3(28,0,z));yield return new WaitForSeconds(.6f);yield return Photo(z==0?"residence.png":z>0?"office.png":"shop.png");}
   Move(inside);yield return new WaitForSeconds(.3f);Check(door.Toggle(),"Door siege close");yield return new WaitForSeconds(.7f);float previousRange=g.config.aimRange;g.config.aimRange=0;var attacker=g.Enemies[1];Check(NavMesh.SamplePosition(outside,out var attackFloor,1,NavMesh.AllAreas),"Siege floor");attacker.Spawn(attackFloor.position,g.config.enemySpeed);deadline=Time.time+10;while(!door.Broken&&Time.time<deadline)yield return null;Check(door.Broken,"Zombies cannot break closed doors");attacker.Retire();g.config.aimRange=previousRange;
   var bomb=g.World.Props.First(p=>p.Kind==WorldPropKind.Explosive);Move(bomb.transform.position+new Vector3(0,0,-6));yield return new WaitForSeconds(.7f);g.PlayerHealth.SetHealth(100);var victim=g.Enemies[0];Check(NavMesh.SamplePosition(bomb.transform.position+Vector3.right*2.3f,out var floor,1,NavMesh.AllAreas),"Explosion victim floor");victim.Spawn(floor.position,0,EnemyKind.Brute);Check(g.World.Visible(bomb,12),"Explosive out of view");g.TogglePause();Check(!g.World.Interact(),"Paused interaction");g.TogglePause();Check(g.World.Nearest()!=bomb,"Explosive still offers interaction");FireAt(bomb);FireAt(bomb);deadline=Time.time+2;while(!bomb.Broken&&Time.time<deadline)yield return null;Check(bomb.Broken&&g.World.Explosions==2,"Explosion chain missing/duplicate");Check(victim.Health.CurrentHealth<390&&victim.KnockedBack,"Explosion missed brute");Check(g.PlayerHealth.CurrentHealth==100,"Explosion damaged safe distance");yield return Photo("explosive-chain.png");victim.Retire();
   // Cover blocks blast propagation and ammunition never hits through solid cover.
   var protectedBox=g.World.Props.First(p=>p.Kind==WorldPropKind.SupplyCrate&&!p.Broken);var origin=protectedBox.transform.position+Vector3.back*3;var wall=GameObject.CreatePrimitive(PrimitiveType.Cube);wall.layer=8;wall.transform.position=origin+Vector3.forward*1.5f+Vector3.up;wall.transform.localScale=new Vector3(4,3,.3f);yield return null;Physics.SyncTransforms();g.World.DamageProps(origin,5,200);Check(!protectedBox.Broken&&protectedBox.Health==52,"Blast passed wall: health="+protectedBox.Health+" point="+protectedBox.transform.position);Destroy(wall);
   g.Restart();yield return new WaitForSeconds(.4f);g=SurvivalGame.Instance;Check(g.World.Props.Count==16&&g.World.Explosions==0&&g.World.CratesBroken==0&&g.World.Props.All(p=>!p.Broken&&!p.Open),"World restart reset");
   File.WriteAllText(Path.Combine(output,"world-pass.json"),"{\"passed\":true,\"device\":\""+SystemInfo.deviceModel+"\",\"actualRifleBreaksCrate\":true,\"rewardPickedUp\":true,\"doorCarvesAndRestoresPath\":true,\"doorDoesNotCloseOnPlayer\":true,\"sixRoomEntrancesReachable\":true,\"zombiesBreakClosedDoors\":true,\"explosiveChain\":true,\"explosiveDamagesAndKnocksBackEnemy\":true,\"coverBlocksBlast\":true,\"pauseAndRestart\":true}");Debug.Log("WORLD_VALIDATION_PASS");Application.Quit(0);
  }
 }
}
